### PR TITLE
txpool: fix tx removal from unlocks set

### LINKED ISSUE #8498: `fatxpool`: fix incomplete removal for tx subtree
The logic here: https://github.com/paritytech/polkadot-sdk/blob/f73c228b7a1a4a6b7d80ae7917a61df62f2359b8/substrate/client/transaction-pool/src/graph/ready.rs#L299-L303 where we remove a tx from the unlocks set of other txs, should look more like here:

Image

Existing txpool unit tests are still passing after the fix, so the impact is not noticeable if any. 
We should include a test for this if possible after the fix, and test it under heavy load with 5 million txs.

### PR DESCRIPTION
**Pull request by iulianbarbu**
# Description

Removing a tx subtree means partly removing some txs from the unlocks set of other txs. This logic is buggy and the PR attempts to fix it.

Closes #8498 

## Integration

N/A

## Review Notes

This doesn't seem to be an important bug. Unit tests for txpool still pass after the fix, so txpool behavior isn't changing much.

### TODOs

- [x] test with a heavy load test (5 millions txs) - all txs were validated successfully
- [x] added a unit test

### CODE REVIEW

File: substrate/client/transaction-pool/src/graph/ready.rs [hunk 1]
```diff
@@ -298,8 +298,11 @@ impl<Hash: hash::Hash + Member + Serialize, Ex> ReadyTransactions<Hash, Ex> {
 				// remove from unlocks
 				for tag in &tx.transaction.transaction.requires {
 					if let Some(hash) = self.provided_tags.get(tag) {
-						if let Some(tx) = ready.get_mut(hash) {
-							remove_item(&mut tx.unlocks, hash);
+						if let Some(tx_unlocking) = ready.get_mut(hash) {
+							remove_item(
+								&mut tx_unlocking.unlocks,
+								&tx.transaction.transaction.hash,
```
Comment (michalkucharczyk) [inline substrate/client/transaction-pool/src/graph/ready.rs:304]: could be just `tx_hash` ?:
```suggestion
								&tx_hash,
```

File: substrate/client/transaction-pool/src/graph/ready.rs [hunk 2]
```diff
@@ -298,8 +298,11 @@ impl<Hash: hash::Hash + Member + Serialize, Ex> ReadyTransactions<Hash, Ex> {
 				// remove from unlocks
 				for tag in &tx.transaction.transaction.requires {
 					if let Some(hash) = self.provided_tags.get(tag) {
-						if let Some(tx) = ready.get_mut(hash) {
-							remove_item(&mut tx.unlocks, hash);
+						if let Some(tx_unlocking) = ready.get_mut(hash) {
```
Comment (michalkucharczyk) [inline substrate/client/transaction-pool/src/graph/ready.rs:301]: Like the name change here :+1:

File: substrate/client/transaction-pool/src/graph/ready.rs [hunk 3]
```diff
@@ -788,4 +791,30 @@ mod tests {
...
+		populate_pool(&mut ready);
+
+		// when
+		let mut it = ready.get();
+		let tx1 = it.next().unwrap();
+		let tx2 = it.next().unwrap();
+		let tx3 = it.next().unwrap();
+		let lock = ready.ready.read();
+		let tx1_unlocks = &lock.get(&tx1.hash).unwrap().unlocks;
+		assert_eq!(tx1_unlocks[0], tx2.hash);
```
Comment (michalkucharczyk) [inline substrate/client/transaction-pool/src/graph/ready.rs:808]: we could check tx3 is unlocked by tx1.

**Review by michalkucharczyk — APPROVED** [review]

**Comment by michalkucharczyk** [comment]
_note_ - just for the record - I think this bug was not causing any user-facing problems. Not removing transactions from unlocks set deep in `graph` module should not have been causing any issue with validity of ready set iterator, (or other graph related problems). At least these problems were not identified.

File: substrate/client/transaction-pool/src/graph/ready.rs [hunk 4]
```diff
@@ -788,4 +791,30 @@ mod tests {
...
+		drop(lock);
+
+		// then consider tx2 invalid, and hence, remove it.
+		let removed = ready.remove_subtree(&[tx2.hash]);
+		assert_eq!(removed.len(), 2);
+		assert_eq!(removed[0].hash, tx2.hash);
+		assert_eq!(removed[1].hash, tx3.hash);
+		let lock = ready.ready.read();
+		let tx1_unlocks = &lock.get(&tx1.hash).unwrap().unlocks;
+		assert!(!tx1_unlocks.contains(&tx2.hash));
```
[the remark this answers is not in the document]
Comment (iulianbarbu) [reply substrate/client/transaction-pool/src/graph/ready.rs:821]: Seems like not, tx3 requires tx2 provides tag, so it should be removed given tx2 is removed.

File: substrate/client/transaction-pool/src/graph/ready.rs (hunk 3 above)
Comment (iulianbarbu) [reply substrate/client/transaction-pool/src/graph/ready.rs:807]: Done.

File: substrate/client/transaction-pool/src/graph/ready.rs (hunk 4 above)
[the remark this answers is not in the document]
Comment (michalkucharczyk) [reply substrate/client/transaction-pool/src/graph/ready.rs:821]: oh, missed that. Anyway I would add test which checks if the non-related unlocks stay untouched. Seems it was not tested well.

**Review by skunert — APPROVED** [review]
