### PR TITLE
Fix slot-based collator panic during warp sync (#11072)

### LINKED ISSUE #11072: [polkadot-assethub] warp sync with `--authoring=slot-based` panics with `AuraApi_slot_duration` not found
This is what ocured at @mosonyi's collator 

```
[Parachain] Starting slot-based block-builder task.
[Parachain] Failed to fetch slot duration from runtime. error=Error at calling runtime api: Execution failed: Other: Exported method AuraApi_slot_duration is not found
[Parachain] Unable to wait for next slot.
[Parachain] Essential task `slot-based-block-builder` failed. Shutting down service.
[Parachain] Essential task `txpool-background` failed. Shutting down service.
[Relaychain] Unable to send AnnouncePin worker message for import: sending into a closed channel
[Relaychain] Essential task `txpool-background` failed. Shutting down service.
```

Solution: Remove `--authoring=slot-based` and start warp syncing. Add the flag after the warp sync finished.

### Steps to reproduce

Start from a fresh parachain db and add the `--authoring=slot-based` to the parachain.

### PR DESCRIPTION
**Pull request by clangenb**
When a parachain collator starts with `--authoring=slot-based` and performs warp sync, the `slot-based-block-builder` essential task immediately calls `slot_duration()` which requires `AuraApi_slot_duration`. During warp sync the runtime isn't ready, so this fails and the task returns, shutting down the node.

The lookahead collator avoids this by calling `wait_for_aura()` before starting. This PR adds an equivalent guard to the slot-based collator.

### Manual test
Before the fix the collator panicked after the relay chain warp sync with AuraApi_slot_duration not available, which does not occur anymore now.
```
 ./target/release/polkadot-parachain \                                                                                                                                                                                                                                                                          
    --chain asset-hub-polkadot \
    --sync warp \
    --authoring=slot-based \
    --tmp -- --sync warp
```
Closes #11072.

### CODE REVIEW

File: cumulus/client/consensus/aura/src/collators/slot_based/block_builder_task.rs [hunk 1]
```diff
@@ -167,6 +167,24 @@ where
...
+				.unwrap_or(false)
+			{
+				break;
+			}
+			tracing::info!(
+				target: LOG_TARGET,
+				"Aura runtime API not yet available. Waiting..."
+			);
+			tokio::time::sleep(Duration::from_secs(2)).await;
+		}
```
Comment (clangenb) [inline cumulus/client/consensus/aura/src/collators/slot_based/block_builder_task.rs]: Design note: polling vs finality notifications

The lookahead collator's `wait_for_aura` uses finality_notification_stream() to react instantly when warp sync completes. This implementation polls has_api every 2s instead, because run_block_builder uses a generic Client bound that doesn't include BlockchainEvents<Block>.

Adding BlockchainEvents<Block> to the Client bound on both run_block_builder and the public run function would allow using the notification-based approach.

The actual callsite passes ParachainClient which already implements it, so no downstream breakage. Happy to switch if reviewers prefer that — kept it minimal for now since the polling approach is functionally equivalent (2s max delay after sync completes).

**Comment by clangenb** [comment]
Thanks you are right, makes much more sense, then we can also re-use the existing wait for aura.

File: cumulus/client/consensus/aura/src/collators/slot_based/block_builder_task.rs (hunk 1 above)
Comment (clangenb) [reply cumulus/client/consensus/aura/src/collators/slot_based/block_builder_task.rs]: This code has been deleted in https://github.com/paritytech/polkadot-sdk/pull/11381/commits/9154f97b7586363782d0c7c69f92d054723da4a5.

**Comment by clangenb** [comment]
/cmd prdoc --audience node_dev --bump patch --force

**Comment by clangenb** [comment]
/cmd prdoc --audience node_dev --bump patch --force

**Comment by clangenb** [comment]
@bkchr may I ask you to take a look at it again? :)

**Review by bkchr — APPROVED** [review]
