### PR TITLE
short-term fix for para inherent weight overestimation

### LINKED ISSUE #849: `paraInclusion` is massively overestimating its weight
Take a look at some recent [Polkadot blocks](https://polkadot.js.org/apps/#/explorer/query/). Even empty blocks consume ~500ms of weight.   
Benchmarking such blocks shows that only a fraction (~4%) of the weight is actually needed.  
That means `paraInclusion` is massively overestimating its weight cost.  
@shawntabrizi noted that we could think about refunding weight here.
Screenshot from 2022-03-23 15-57-10

Output from [benchmark-block](https://github.com/paritytech/substrate/pull/11091) on reference hardware with production profile and wasm executor:
```pre
Block 9556370 with     2 tx used   4.29% of its weight (    21,509,600 of    501,617,735 ns)    
Block 9556371 with     3 tx used   4.08% of its weight (    20,643,956 of    505,412,849 ns)    
Block 9556372 with     2 tx used   3.94% of its weight (    19,750,293 of    501,617,735 ns)    
Block 9556373 with     2 tx used   3.98% of its weight (    20,368,847 of    511,839,008 ns)    
Block 9556374 with     3 tx used   3.97% of its weight (    19,920,982 of    501,891,126 ns)    
Block 9556375 with     3 tx used   3.98% of its weight (    20,114,849 of    505,370,681 ns)    
```

### PR DESCRIPTION
**Pull request by ordian**
closes #849

## Context

For the background on this and the long-term fix, see https://github.com/paritytech/polkadot-sdk/issues/849#issuecomment-2247895862.

## Changes

* The weigh files are renamed from `runtime_(parachains|common).*` to `polkadot_runtime_(parachains|common).*`. The reason for it is the renaming introduced in #4633. The new weight command and files are generated now include `polkadot_` prefix.
* The WeightInfo for `paras_inherent` now includes `enter_empty` which calculates the cost of processing an empty parachains inherent. This cost is subtracted dynamically when calculating other weights (so the other weights remain the same)

## Benefits

See https://github.com/paritytech/polkadot-sdk/issues/849#issuecomment-2247895862, but TL;DR is that we are not blocked on weights for scaling the number of validators and cores further.

Resolved questions:
- [x] why new benchmarks for westend are doing fewer db IOPS?
Is it due polkadot-sdk update (db IOPS diff)?
or the bench setup is no longer valid?
https://github.com/polkadot-fellows/runtimes/blob/7723274a2c5cbb10213379271094d5180716ca7d/relay/polkadot/src/weights/runtime_parachains_paras_inherent.rs#L131-L196
Answer: see background section of #5270 

TODOs:
- [x] Rerun benchmarks for Rococo and Westend
- [x] PRDoc

### CODE REVIEW

**Comment by ordian** [comment]
bot bench polkadot-pallet --pallet=polkadot_runtime_parachains::paras_inherent --runtime=westend
bot bench polkadot-pallet --pallet=polkadot_runtime_parachains::paras_inherent --runtime=rococo
bot clean

**Comment by kianenigma** [comment]
What is the long term fix?

File: polkadot/runtime/parachains/src/paras_inherent/benchmarking.rs [hunk 1]
```diff
@@ -26,6 +26,20 @@ use polkadot_primitives::v7::GroupIndex;
...
 benchmarks! {
+	enter_empty {
+		let scenario = BenchBuilder::<T>::new()
+			.build();
+
+		let mut benchmark = scenario.data.clone();
+
+		benchmark.bitfields.clear();
+		benchmark.backed_candidates.clear();
+		benchmark.disputes.clear();
```
Comment (sandreim) [inline polkadot/runtime/parachains/src/paras_inherent/benchmarking.rs:37]: Are these really needed if we just called `build()` on a default `BenchBuilder` instance?

File: polkadot/runtime/parachains/src/paras_inherent/benchmarking.rs [hunk 2]
```diff
@@ -26,6 +26,20 @@ use polkadot_primitives::v7::GroupIndex;
 use crate::builder::BenchBuilder;
 
 benchmarks! {
+	enter_empty {
+		let scenario = BenchBuilder::<T>::new()
```
[the remark this answers is not in the document]
Comment (sandreim) [reply polkadot/runtime/parachains/src/paras_inherent/benchmarking.rs:30]: This is supposed to be the weight of an empty inherent, no bitfields, not backed candidates and no disputes.

File: polkadot/runtime/rococo/src/weights/runtime_parachains_paras_inherent.rs [hunk 3]
```diff
@@ -45,9 +45,50 @@
...
+	/// Proof: `ParasShared::ActiveValidatorIndices` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
+	/// Storage: `Session::DisabledValidators` (r:1 w:0)
+	/// Proof: `Session::DisabledValidators` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
+	/// The range of component `v` is `[10, 200]`.
+	fn enter_empty() -> Weight {
+		// Proof Size summary in bytes:
+		//  Measured:  `8967`
+		//  Estimated: `12432`
+		// Minimum execution time: 111_675_000 picoseconds.
+		Weight::from_parts(126_295_131, 0)
```
Comment (sandreim) [inline polkadot/runtime/rococo/src/weights/runtime_parachains_paras_inherent.rs:87]: So, expect all weights to drop by up to 126 usec, but we don't actually see this in the weights file.

File: polkadot/runtime/parachains/src/paras_inherent/weights.rs [hunk 4]
```diff
@@ -123,7 +131,8 @@ where
 	set_proof_size_to_tx_size(
 		<<T as Config>::WeightInfo as WeightInfo>::enter_variable_disputes(
 			statement_set.as_ref().statements.len() as u32,
-		),
+		)
+		.saturating_sub(<<T as Config>::WeightInfo as WeightInfo>::enter_empty()),
```
Comment (sandreim) [inline polkadot/runtime/parachains/src/paras_inherent/weights.rs:135]: Can't we perform the `saturating_sub` during weight generation, instead of the helpers during execution ?

File: polkadot/runtime/rococo/src/weights/runtime_parachains_paras_inherent.rs [hunk 5]
```diff
@@ -245,15 +264,13 @@ impl<T: frame_system::Config> polkadot_runtime_parachains::paras_inherent::Weigh
...
-		//  Estimated: `48769`
-		// Minimum execution time: 1_305_254_000 picoseconds.
-		Weight::from_parts(1_347_160_667, 0)
-			.saturating_add(Weight::from_parts(0, 48769))
-			// Standard Error: 22_128
-			.saturating_add(Weight::from_parts(57_229, 0).saturating_mul(v.into()))
+		//  Measured:  `42830`
+		//  Estimated: `48770`
+		// Minimum execution time: 1_401_417_000 picoseconds.
+		Weight::from_parts(1_461_289_202, 0)
```
[the remark this answers is not in the document]
Comment (ordian) [reply polkadot/runtime/rococo/src/weights/runtime_parachains_paras_inherent.rs:272]: As mentioned on a call, the total weight didn't go up, instead the cost of verifying the backing signatures (v) is now included in total (seems like it's lost in the noise and in practice we have up to 5 of them).

**Comment by ordian** [comment]
bot bench polkadot-pallet --pallet=polkadot_runtime_parachains::paras_inherent --runtime=westend
bot bench polkadot-pallet --pallet=polkadot_runtime_parachains::paras_inherent --runtime=rococo
bot clean

**Review by alexggh — COMMENTED** [review]
Looks good to me, but there is something I don't clearly understand, as far as I can tell we are using `fallback_max_validators()` in a lot of places, don't we need to adjust those to get realistic results for 1000 validators ?

**Review by tdimitrov — APPROVED** [review]
I think for a short term fix this is good. @alexggh do have a point about the 1000 validators but it can be a follow up or part of the proper fix.

**Review by sandreim — APPROVED** [review]

**Comment by ordian** [comment]
bot bench polkadot-pallet --pallet=polkadot_runtime_parachains::paras_inherent --runtime=westend
bot bench polkadot-pallet --pallet=polkadot_runtime_parachains::paras_inherent --runtime=rococo
bot clean

**Review by kianenigma — APPROVED** [review]
Empirically, how much is the weight consumed by paras inherent in Polkadot and Kusama RC now, vs. how much will it be when this is deployed? (and which one is closer to reality -- although this is hard to measure 🙈)

**Review by AndreiEres — APPROVED** [review]

**Comment by ordian** [comment]
> Empirically, how much is the weight consumed by paras inherent in Polkadot and Kusama RC now, vs. how much will it be when this is deployed? (and which one is closer to reality -- although this is hard to measure 🙈)

I've provided some back-of-the-envelope calculations in this comment: https://github.com/paritytech/polkadot-sdk/issues/849#issuecomment-2247895862, but TL;DR is that the dominant cost are from `enter_bitfields` (which we multiply by the number of para validators, which is 500 on Kusama at the moment and will grow to 1k). This number was already reduced in https://github.com/polkadot-fellows/runtimes/pull/433 by 55% and the reasoning is explained in background section of https://github.com/paritytech/polkadot-sdk/pull/5270. This PR will further reduce it cost by more than a half (need to rerun the benches on Kusama, but you can see the cost for westend for comparison). Please note, that the cost of `enter_bitfields` by itself will remain the same, but subtract dynamically the cost of `enter_empty`. These and other annoyances will be addressed with a long-term refactoring mentioned in the first comment.
However, https://github.com/paritytech/polkadot-sdk/pull/5270 will bring some (a lot) of the costs back by properly accounting for e.g. processed messages in enacted candidates.
