### PR TITLE
`fatxpool`: add fallback for ready at light

### LINKED ISSUE #6056: `fatxpool`: `ready_at_light` optimization
I still think that the following should be faster:
```
let mut to_process = Vec::new();
while at.number() > last_finalized.number() {
    if self.view_exists(at.hash()) { break }
    to_process.push(at.hash());
   at = at.parent();
}
```

No need to get a tree route down to the finalized block.

_Originally posted by @bkchr in https://github.com/paritytech/polkadot-sdk/pull/4639#discussion_r1791663895_

### LINKED ISSUE #8213: `fatxpool`: add one more fallback for `ready_at_light`
In general we need one more fallback in [`ready_at_light`](https://github.com/paritytech/polkadot-sdk/blob/27fbb06d4b17178da50cc043ef5ec60b0cdfead8/substrate/client/transaction-pool/src/fork_aware_txpool/fork_aware_txpool.rs#L558-L565). We should blindly provide `txs` from [`most_recent_view`](https://github.com/paritytech/polkadot-sdk/blob/27fbb06d4b17178da50cc043ef5ec60b0cdfead8/substrate/client/transaction-pool/src/fork_aware_txpool/view_store.rs#L167-L169) if other methods failed.

The justification is as follows:

> The only possible argument to make it work in this stress conditions would be that, maybe you want some transactions to go through, so that if for recovering/fixing you need to apply some runtime/storage configuration changes you can do it.

Quick sketch of what happened (the real root cause was misconfiguration of collators):
```
B1f - B2f - B3f (constructed)
|
B2
 |
B3
```

Pool knows about `B3`.
Then we finalized `B1f`.
And try to build on top of `B2f`

`ready_at_light` is first computing tree route from new parent (`B2f`) to  finalized block.
And then looks for any views on enacted part. But we have no - because pool only saw `B3`.

Here is log and figures:
```
txpool: [Parachain] maintain txs=(0, 1) a=3 i=0 views=[(69018, 1, 0), (69019, 1, 0), (69020, 1, 0)] event=Finalized { hash: BLOCK69017f03, tree_route: [] } duration=70.143µs
parachain::validator-discovery: [Relaychain] New ConnectToValidators request peer_set=Collation requested=2 failed_to_resolve=0
parachain::validator-discovery: [Relaychain] New ConnectToValidators resolved request peer_set=Collation num_peers=2 removed=0
substrate: [Relaychain] 💤 Idle (3 peers), best: #73024 (RBLOCK73024), finalized #73022 (RBLOCK73022), ⬇ 0.9kiB/s ⬆ 0.7kiB/s    
substrate: [Parachain] 💤 Idle (1 peers), best: #69020 (BLOCK69020), finalized #69017 (BLOCK69017f03), ⬇ 45 B/s ⬆ 35 B/s    
substrate: [Relaychain] 🏆 Imported #73025 (RBLOCK73024 → RBLOCK73025)    
parachain::collator-protocol: [Relaychain] Removing relay parent because our view changed. relay_parent=RBLOCK73022
parachain::collator-protocol: [Relaychain] Collation was requested. candidate_hash=GOBO pov_hash=NAPE traceID=217006037283171539261327901027945344636
sc_informant: [Parachain] ♻️  Reorg on #69020,BLOCK69020 to #69021,BLOCK69021, common ancestor #69017,BLOCK69017f03    
substrate: [Parachain] 🏆 Imported #69021 (BLOCK69020f01 → BLOCK69021)    
txpool: [Parachain] maintain txs=(0, 1) a=4 i=0 views=[(69018, 1, 0), (69019, 1, 0), (69020, 1, 0), (69021, 1, 0)] event=NewBestBlock { hash: BLOCK69021, tree_route: Some(TreeRoute { route: [HashAndNumber { number: 69020, hash: BLOCK69020 }, HashAndNumber { number: 69019, hash: BLOCK69019f01 }, HashAndNumber { number: 69018, hash: BLOCK69018f02 }, HashAndNumber { number: 69017, hash: BLOCK69017f03 }, HashAndNumber { number: 69018, hash: BLOCK69018f03 }, HashAndNumber { number: 69019, hash: BLOCK69019f02 }, HashAndNumber { number: 69020, hash: BLOCK69020f01 }], pivot: 3 }) } duration=611.833µs
parachain::validator-discovery: [Relaychain] New ConnectToValidators request peer_set=Collation requested=2 failed_to_resolve=0
parachain::validator-discovery: [Relaychain] New ConnectToValidators resolved request peer_set=Collation num_peers=2 removed=0
substrate: [Relaychain] 💤 Idle (3 peers), best: #73025 (RBLOCK73025), finalized #73022 (RBLOCK73022), ⬇ 0.9kiB/s ⬆ 0.7kiB/s    
substrate: [Parachain] 💤 Idle (1 peers), best: #69021 (BLOCK69021), finalized #69017 (BLOCK69017f03), ⬇ 1.8kiB/s ⬆ 95 B/s    
substrate: [Relaychain] 🏆 Imported #73026 (RBLOCK73025 → RBLOCK73026)    
parachain::collator-protocol: [Relaychain] Removing relay parent because our view changed. relay_parent=RBLOCK73023
sc_basic_authorship::basic_authorship: [Parachain] 🙌 Starting consensus session on top of parent BLOCK69018f03 (#69018)    
txpool: [Parachain] Timeout fired waiting for transaction pool at block. Proceeding with production. at=BLOCK69018f03
basic-authorship: [Parachain] Attempting to push transactions from the pool at BLOCK69018f03.    
basic-authorship: [Parachain] No more transactions, proceeding with proposing.    
sc_basic_authorship::basic_authorship: [Parachain] 🎁 Prepared block for proposing at 69019 (168 ms) hash: ANTA; parent_hash: BLOCK69018f03; end: NoMoreTransactions; extrinsics_count: 2    
aura::cumulus: [Parachain] 🔖 Pre-sealed block for proposal at 69019. Hash now BLOCK69019f03, previously ANTA.
substrate: [Parachain] 🆕 Imported #69019 (BLOCK69018f03 → BLOCK69019f03)    
aura::cumulus: [Parachain] PoV size { header: 0.22265625kb, extrinsics: 3.76171875kb, storage_proof: 10.5107421875kb }
aura::cumulus: [Parachain] Compressed PoV size: 13.4951171875kb
parachain::collation-generation: [Relaychain] candidate is generated candidate_hash=DOER pov_hash=BICK relay_parent=RBLOCK73026 para_id=3369 core_index=CoreIndex(0) traceID=255551800300830200024247885740631521910
parachain::collator-protocol: [Relaychain] Received session info session_index=135
parachain::collator-protocol: [Relaychain] Accepted collation, connecting to validators. para_id=3369 candidate_relay_parent=RBLOCK73026 candidate_hash=DOER pov_hash=BICK core=CoreIndex(0) current_validators=[Public(d43593c715fdd31c61141abd04a99fd6822c8558854ccde39a5684e7a56da27d (XUtEtdq5...)), Public(8eaf04151687736326c9fea17e25fc5287613693c912909cb226aa4794f26a48 (XUrfjMku...))] traceID=255551800300830200024247885740631521910
sc_basic_authorship::basic_authorship: [Parachain] 🙌 Starting consensus session on top of parent BLOCK69019f03 (#69019)    
parachain::collator-protocol: [Relaychain] Advertising collation. relay_parent=RBLOCK73026 candidate_hash=DOER peer_id=12D3KooWQCkBm1BYtkHpocxCwMgR8yjitEeHGx8spzcDLGt2gkBm traceID=255551800300830200024247885740631521910
parachain::collator-protocol: [Relaychain] Advertising collation. relay_parent=RBLOCK73026 candidate_hash=DOER peer_id=12D3KooWRkZhiRhsqmrQ28rt73K7V3aCBpqKrLGSXmZ99PTcTZby traceID=255551800300830200024247885740631521910
parachain::validator-discovery: [Relaychain] New ConnectToValidators request peer_set=Collation requested=2 failed_to_resolve=0
parachain::validator-discovery: [Relaychain] New ConnectToValidators resolved request peer_set=Collation num_peers=2 removed=0
txpool: [Parachain] Timeout fired waiting for transaction pool at block. Proceeding with production. at=BLOCK69019f03
basic-authorship: [Parachain] Attempting to push transactions from the pool at BLOCK69019f03.    
basic-authorship: [Parachain] No more transactions, proceeding with proposing.    
sc_basic_authorship::basic_authorship: [Parachain] 🎁 Prepared block for proposing at 69020 (168 ms) hash: POSY; parent_hash: BLOCK69019f03; end: NoMoreTransactions; extrinsics_count: 2
```

Finalized blocks:

Known Best Blocks:

### PR DESCRIPTION
**Pull request by iulianbarbu**
# Description

Proposing a new block on top of an existing parent block considers the best ready transactions provided by the txpool to be included in the new block. Whenever the given parent hash to build on top of is part of a fork up to the finalized block which has no best block notified to the pool, it might be the case that the proposer will rely on `ready_at_light` (due to various reason not in our control), and when that's the case, the ready transactions set will be empty.

This PR adds a fallback for the `ready_at_light` where we consider the ready txs of the most recent view processed by the txpool, even if those txs might be invalid

Closes #8213 
Closes #6056

## Integration

N/A

## Review Notes

In terms of testing, I updated an existing test which already exercises `ready_at_light` in the scope of the newly added fallback.

### CODE REVIEW

**Comment by iulianbarbu** [comment]
Will address #6056 too, and will create a new test too.

File: substrate/client/transaction-pool/src/fork_aware_txpool/fork_aware_txpool.rs [hunk 1]
```diff
@@ -554,6 +554,19 @@ where
...
+			.most_recent_view
+			.read()
+			.and_then(|at| self.view_store.get_view_at(at, true))
+		{
+			// Fallback for the case of not having a best view to use
+			// for getting a ready transactions set. Even if some of
+			// the ready txs provided by the most recent view are invalid
+			// or already included in the blocks, a few of them might still
+			// be valid for `at` hash, which is still better than including
+			// nothing.
```
Comment (michalkucharczyk) [inline substrate/client/transaction-pool/src/fork_aware_txpool/fork_aware_txpool.rs:568]: I'd slightly adjust wording here, `best view` may be misleading:
```suggestion
			// Fallback for the case when `at` is not on the already known fork.
			// Falls back to the most recent view, which may include txs which 
			// are invalid or already included in the blocks but can still yield a
			// partially valid ready set, which is still better than including nothing.
```

**Comment by michalkucharczyk** [comment]
Also, new fallback might be worth mentioning in the doc here:

https://github.com/paritytech/polkadot-sdk/blob/67bc04fa348e7f3ddcafdb33411de32cdd1727e8/substrate/client/transaction-pool/src/fork_aware_txpool/mod.rs#L215C1-L219C31

**Comment by michalkucharczyk** [comment]
Some nits left, overall looks good :+1:

File: prdoc/pr_8533.prdoc [hunk 2]
```diff
@@ -0,0 +1,8 @@
+title: '`fatxpool`:  add fallback for ready at light'
+doc:
+- audience: Node Dev 
+  description: |
+     Add fallback for `ready_at_light` for the case of not finding a best view that can be used to return a set of ready transactions.
```
Comment (iulianbarbu) [inline prdoc/pr_8533.prdoc:5]:
```suggestion
     Add fallback for `ready_at_light` for the case of not finding a best view that can be used to return a set of ready transactions. Optimised as well how the best view is searched.
```

File: substrate/client/transaction-pool/src/fork_aware_txpool/fork_aware_txpool.rs [hunk 3]
```diff
@@ -487,35 +487,61 @@ where
...
+		let mut best_view = None;
+		let mut tmp_at_number = at_number;
+		let mut tmp_at = at;
+
+		// Return an empty ready transaction set if we can't find a finalized block to report to,
+		// given we can not look for a view that can provide an approximate ready transaction set
+		// on the fork ending with `at` up to the finalized block.
+		let last_finalized = self.enactment_state.lock().recent_finalized_block();
+		let Ok(last_finalized_number) = self.api.resolve_block_number(last_finalized) else {
+			return Box::new(std::iter::empty())
```
Comment (iulianbarbu) [inline substrate/client/transaction-pool/src/fork_aware_txpool/fork_aware_txpool.rs:505]: Should we return the ready txs from the most recent view though?

File: substrate/client/transaction-pool/src/fork_aware_txpool/fork_aware_txpool.rs [hunk 4]
```diff
@@ -487,35 +487,61 @@ where
...
 		};
 
-		if let Ok((Some(best_tree_route), Some(best_view))) = best_result {
+		// Search for a view that can be used to get and return an approximate ready
+		// transaction set.
+		while tmp_at_number > last_finalized_number {
+			// Found a view, now prune its pool based on the blocks in `to_process`.
```
Comment (iulianbarbu) [inline substrate/client/transaction-pool/src/fork_aware_txpool/fork_aware_txpool.rs:511]:
```suggestion
			// Found a view, stop searching..
```

File: substrate/client/transaction-pool/src/fork_aware_txpool/fork_aware_txpool.rs [hunk 5]
```diff
@@ -487,35 +487,61 @@ where
...
+			if let Some((view, _)) = self.view_store.get_view_at(tmp_at, true) {
+				best_view = Some(view);
+				break;
+			}
+
+			to_process.push(tmp_at);
```
Comment (iulianbarbu) [inline substrate/client/transaction-pool/src/fork_aware_txpool/fork_aware_txpool.rs:517]:
```suggestion
			to_process.push(tmp_at);
			// Move up the hierarchy by getting the parent block.
```

**Comment by iulianbarbu** [comment]
> Also, new fallback might be worth mentioning in the doc here:
> 
> https://github.com/paritytech/polkadot-sdk/blob/67bc04fa348e7f3ddcafdb33411de32cdd1727e8/substrate/client/transaction-pool/src/fork_aware_txpool/mod.rs#L215C1-L219C31

Specified some info here: [b858a23](https://github.com/paritytech/polkadot-sdk/pull/8533/commits/b858a23e0f6b7af39262f2813f480d6e52a32bbe). LMK if you have some more suggestions.

**Comment by iulianbarbu** [comment]
> @iulianbarbu if you are reading through this part of code, maybe you would like to address this one: #6056
> 
> Should also be easy one ;), and could be done in this PR.

Addressed it here: [6727942](https://github.com/paritytech/polkadot-sdk/pull/8533/commits/672794205186736cbfb266179e9a6692da0fb97d). Curious on your thoughts on this, since I find it reads a bit harder than the previous logic. However, if it is more optimal, not sure yet. The `sp_blockchain::tree_route` based computation relies on `HeaderMetadata::header_metadata` call, while we rely here on `block_header` & `resolve_block_number`. Do you remember why the proposed algorithm was suggested to be more optimal? Can not easily find the comment.

**Comment by michalkucharczyk** [comment]
> > @iulianbarbu if you are reading through this part of code, maybe you would like to address this one: #6056
> > Should also be easy one ;), and could be done in this PR.
> 
> Addressed it here: [6727942](https://github.com/paritytech/polkadot-sdk/pull/8533/commits/672794205186736cbfb266179e9a6692da0fb97d). Curious on your thoughts on this, since I find it reads a bit harder than the previous logic. However, if it is more optimal, not sure yet. The `sp_blockchain::tree_route` based computation relies on `HeaderMetadata::header_metadata` call, while we rely here on `block_header` & `resolve_block_number`. Do you remember why the proposed algorithm was suggested to be more optimal? Can not easily find the comment.

Original discussion here:
https://github.com/paritytech/polkadot-sdk/pull/4639#discussion_r1791663895
(link worked in chrome - PR is a bit lengthy :smiley: )

File: substrate/client/transaction-pool/src/fork_aware_txpool/fork_aware_txpool.rs [hunk 6]
```diff
@@ -487,35 +487,62 @@ where
...
-							self.view_store.get_view_at(b.hash, true).map(|(view, _)| (i, view))
-						}) {
-						let e = tree_route.enacted()[index..].to_vec();
-						(TreeRoute::new(e, 0).ok(), Some(view))
-					} else {
-						(None, None)
-					}
-				},
-			)
+		let mut to_process = Vec::new();
```
Comment (michalkucharczyk) [inline substrate/client/transaction-pool/src/fork_aware_txpool/fork_aware_txpool.rs:495]: nit, maybe:
```suggestion
		let mut enacted_blocks = Vec::new();
```

File: substrate/client/transaction-pool/src/fork_aware_txpool/fork_aware_txpool.rs (hunk 3 above)
Comment (michalkucharczyk) [reply substrate/client/transaction-pool/src/fork_aware_txpool/fork_aware_txpool.rs:505]: Yeah, that would make sense.

If we can't resolve block number - it is kinda similar to not finding the tree_route. So `best_result` in old code would be `Err`.

Comment (michalkucharczyk) [reply substrate/client/transaction-pool/src/fork_aware_txpool/fork_aware_txpool.rs:505]: Maybe we should set best_view to `None` and just follow the execution path that is below?
Then we would handle fallback in one place - flow would be easier to follow.

Comment (michalkucharczyk) [reply substrate/client/transaction-pool/src/fork_aware_txpool/fork_aware_txpool.rs:505]: Could be moved to helper function- for better readablity.

File: substrate/client/transaction-pool/src/fork_aware_txpool/fork_aware_txpool.rs [hunk 7]
```diff
@@ -487,35 +487,62 @@ where
...
+				}) else {
+					break;
+				};
+
+				tmp_at_number = parent_number;
+			} else {
+				// Not finding the header of any block on the fork means we can not continue looking
+				// for a view up to the finalized block, so we break early.
+				break;
+			}
```
Comment (michalkucharczyk) [inline substrate/client/transaction-pool/src/fork_aware_txpool/fork_aware_txpool.rs:532]: maybe sth like this will more readable - we have tmp_at_xxx assigned in one block and one break.
```suggestion
			let parent_resolved = self
				.api
				.block_header(tmp_at)
				.ok()
				.flatten()
				.and_then(|header| {
					let hash = *header.parent_hash();
					self.api.resolve_block_number(hash).ok().map(|number| (hash, number))
				})
				.map(|(parent_hash, parent_number)| {
					tmp_at = parent_hash;
					tmp_at_number = parent_number;
				});

			if parent_resolved.is_none() {
				break
			}

```

**Comment by michalkucharczyk** [comment]
> > @iulianbarbu if you are reading through this part of code, maybe you would like to address this one: #6056
> > Should also be easy one ;), and could be done in this PR.
> 
> Addressed it here: [6727942](https://github.com/paritytech/polkadot-sdk/pull/8533/commits/672794205186736cbfb266179e9a6692da0fb97d). Curious on your thoughts on this, since I find it reads a bit harder than the previous logic. However, if it is more optimal, not sure yet. The `sp_blockchain::tree_route` based computation relies on `HeaderMetadata::header_metadata` call, while we rely here on `block_header` & `resolve_block_number`. Do you remember why the proposed algorithm was suggested to be more optimal? Can not easily find the comment.

Also computing tree_route requires touching all the blocks on the way down to finalized.
What Basti proposed is a bit more optimal in case we have some view before reaching finalized block.

Also we don't need to call `resolve_block_number` - parent number is always `current -1`.

**Comment by iulianbarbu** [comment]
> > > @iulianbarbu if you are reading through this part of code, maybe you would like to address this one: #6056
> > > Should also be easy one ;), and could be done in this PR.
> > 
> > 
> > Addressed it here: [6727942](https://github.com/paritytech/polkadot-sdk/pull/8533/commits/672794205186736cbfb266179e9a6692da0fb97d). Curious on your thoughts on this, since I find it reads a bit harder than the previous logic. However, if it is more optimal, not sure yet. The `sp_blockchain::tree_route` based computation relies on `HeaderMetadata::header_metadata` call, while we rely here on `block_header` & `resolve_block_number`. Do you remember why the proposed algorithm was suggested to be more optimal? Can not easily find the comment.
> 
> Also computing tree_route requires touching all the blocks on the way down to finalized. What Basti proposed is a bit more optimal in case we have some view before reaching finalized block.
> 
> Also we don't need to call `resolve_block_number` - parent number is always `current -1`.

Makes sense! Will remove the `resolve_block_number` calls then. Will adjust soon. Thanks!

File: substrate/client/transaction-pool/src/fork_aware_txpool/fork_aware_txpool.rs (hunk 6 above)
Comment (iulianbarbu) [reply substrate/client/transaction-pool/src/fork_aware_txpool/fork_aware_txpool.rs]: Used this naming here: [d11101e](https://github.com/paritytech/polkadot-sdk/pull/8533/commits/d11101e3360100c5a95b546a8d020b3758865b97)

File: substrate/client/transaction-pool/src/fork_aware_txpool/fork_aware_txpool.rs (hunk 7 above)
Comment (iulianbarbu) [reply substrate/client/transaction-pool/src/fork_aware_txpool/fork_aware_txpool.rs]: Hmm, I actually went with something like below, which should work fine, and looks readable too.

```
   // Move up into the fork. Return with no view or enacted blocks list if
   // we can't access the header of the current block.
   let Some(header) = self.api.block_header(at_hash).ok().flatten() else {
      return (None, Vec::new());
   };
   at_hash = *header.parent_hash();
   at_number = at_number.saturating_sub(1u32.into());
```

File: substrate/client/transaction-pool/src/fork_aware_txpool/mod.rs [hunk 8]
```diff
@@ -209,14 +209,15 @@
...
 //! The [maintain](#maintain) procedure can sometimes be quite heavy, and it may not be accomplished
 //! within the time window expected by the block builder. On top of that block builder may want to
-//! build few blocks in the raw, not giving the pool enough time to accomplish possible ongoing
+//! build few blocks in the row, not giving the pool enough time to accomplish possible ongoing
 //! maintain process.
 //!
 //! To address this, there is a [light version][`ready_at_light`] of the maintain procedure. It
 //! [finds the best view][find_best_view], clones it and prunes all the transactions that were
-//! included in enacted part of [tree route][`TreeRoute`] from the base view to the block at which a
+//! included in enacted part of [tree route][`TreeRoute`] from the best view to the block at which a
```
Comment (michalkucharczyk) [inline substrate/client/transaction-pool/src/fork_aware_txpool/mod.rs:217]:
```suggestion
//! included in enacted part of [tree route][`TreeRoute`] from the base view to the block at which a
```

File: substrate/client/transaction-pool/tests/fatp.rs [hunk 9]
```diff
@@ -2328,7 +2328,12 @@ fn fatp_ready_light_long_fork_retracted_works() {
 	let header02b = api.push_block_with_parent(header01b.hash(), vec![xt1.clone()], true);
 	let header03b = api.push_block_with_parent(header02b.hash(), vec![xt2.clone()], true);
 
+	// Returns the most recent view (`header01a`) ready transactions set.
 	let mut ready_iterator = pool.ready_at_light(header03b.hash()).now_or_never().unwrap();
+	assert!(ready_iterator.next().is_some());
+	assert!(ready_iterator.next().is_some());
+	assert!(ready_iterator.next().is_some());
+	assert!(ready_iterator.next().is_some());
```
Comment (michalkucharczyk) [inline substrate/client/transaction-pool/tests/fatp.rs:2336]: Can we do sth like this:
```suggestion
	assert_eq!(ready_iterator.count(), 4);	
```

File: substrate/client/transaction-pool/src/fork_aware_txpool/fork_aware_txpool.rs [hunk 10]
```diff
@@ -469,12 +469,59 @@ where
 		self.view_store.futures_at(at)
 	}
 
+	/// Searches in the view store for a view by iterating through the fork of
+	/// the `at` block, up to the last finalized block.
+	///
+	/// Returns with a pair of a maybe view and a set of enacted blocks (possibly empty if no view
+	/// is found), usually starting at the last known block of the fork, up to the block
+	/// corresponding to the found view.
+	fn find_best_view(
```
Comment (michalkucharczyk) [inline substrate/client/transaction-pool/src/fork_aware_txpool/fork_aware_txpool.rs:478]: In my mental model best view is the view which is the base during handling new block. It is the view the we clone from. I'd prefer to stick to this naming to avoid confusion.
So I'd propose to re-name this method, maybe:
```suggestion
	fn find_view_descendant_upto_hash(
```
or just `find_view_descendant`.

File: substrate/client/transaction-pool/src/fork_aware_txpool/fork_aware_txpool.rs [hunk 11]
```diff
@@ -469,12 +469,59 @@ where
...
+		&self,
+		at: &HashAndNumber<Block>,
+	) -> (Option<Arc<View<ChainApi>>>, Vec<Block::Hash>) {
```
Comment (michalkucharczyk) [inline substrate/client/transaction-pool/src/fork_aware_txpool/fork_aware_txpool.rs:481]: why not return option instead of tuple?
```suggestion
	) -> Option<(Arc<View<ChainApi>>, Vec<Block::Hash>)> {
```

File: substrate/client/transaction-pool/src/fork_aware_txpool/fork_aware_txpool.rs [hunk 12]
```diff
@@ -469,12 +469,59 @@ where
...
 
+	/// Searches in the view store for a view by iterating through the fork of
+	/// the `at` block, up to the last finalized block.
+	///
+	/// Returns with a pair of a maybe view and a set of enacted blocks (possibly empty if no view
+	/// is found), usually starting at the last known block of the fork, up to the block
+	/// corresponding to the found view.
+	fn find_best_view(
+		&self,
+		at: &HashAndNumber<Block>,
```
Comment (michalkucharczyk) [inline substrate/client/transaction-pool/src/fork_aware_txpool/fork_aware_txpool.rs:480]:
```suggestion
		at: &HashAndNumber<Block>,
		finalized: Block::Hash
```
or `upto_hash`.
Could also be number.

File: substrate/client/transaction-pool/src/fork_aware_txpool/fork_aware_txpool.rs [hunk 13]
```diff
@@ -469,12 +469,59 @@ where
...
+	) -> (Option<Arc<View<ChainApi>>>, Vec<Block::Hash>) {
+		let mut enacted_blocks = Vec::new();
+		let mut best_view = None;
+
+		let mut at_hash = at.hash;
+		let mut at_number = at.number;
+
+		let last_finalized = self.enactment_state.lock().recent_finalized_block();
+		let Some(last_finalized_number) = self.api.resolve_block_number(last_finalized).ok() else {
+			return (None, Vec::new());
```
Comment (michalkucharczyk) [inline substrate/client/transaction-pool/src/fork_aware_txpool/fork_aware_txpool.rs:490]:
```suggestion
			return None;
```

File: substrate/client/transaction-pool/src/fork_aware_txpool/fork_aware_txpool.rs [hunk 14]
```diff
@@ -469,12 +469,59 @@ where
...
+			// Move up into the fork. Return with no view and an empty enacted blocks
+			// list if we can't access the header of the current block.
+			let Some(header) = self.api.block_header(at_hash).ok().flatten() else {
+				return (None, Vec::new());
+			};
+			at_hash = *header.parent_hash();
+			at_number = at_number.saturating_sub(1u32.into());
+		}
+
+		return (best_view, enacted_blocks);
```
Comment (michalkucharczyk) [inline substrate/client/transaction-pool/src/fork_aware_txpool/fork_aware_txpool.rs:513]:
```suggestion
		return best_view.map(|h| (h, enacted_blocks))
```

File: substrate/client/transaction-pool/src/fork_aware_txpool/fork_aware_txpool.rs (hunk 10 above)
Comment (michalkucharczyk) [reply substrate/client/transaction-pool/src/fork_aware_txpool/fork_aware_txpool.rs:478]: This method could also be moved to the `ViewStore` (assuming we pass the hash).

**Review by michalkucharczyk — COMMENTED** [review]
The logic looks good. I proposed some renaming and signature adjustments.

File: substrate/client/transaction-pool/src/fork_aware_txpool/fork_aware_txpool.rs (hunk 13 above)
Comment (iulianbarbu) [reply substrate/client/transaction-pool/src/fork_aware_txpool/fork_aware_txpool.rs]: I moved this logic up to `ready_at_light` and returned an empty tx set for it. Decided to treat this in the same way we treat not being able to resolve the `at` hash to a block number. WDYT?

[9d47e15](https://github.com/paritytech/polkadot-sdk/pull/8533/commits/9d47e15417b4cf3fe54ec942fc883f852e494b32)

File: substrate/client/transaction-pool/src/fork_aware_txpool/fork_aware_txpool.rs (hunk 12 above)
Comment (iulianbarbu) [reply substrate/client/transaction-pool/src/fork_aware_txpool/fork_aware_txpool.rs]: Decided to pass a block number as a parameter. Change here: [9d47e15](https://github.com/paritytech/polkadot-sdk/pull/8533/commits/9d47e15417b4cf3fe54ec942fc883f852e494b32).

File: substrate/client/transaction-pool/src/fork_aware_txpool/fork_aware_txpool.rs (hunk 11 above)
Comment (iulianbarbu) [reply substrate/client/transaction-pool/src/fork_aware_txpool/fork_aware_txpool.rs]: Right, this is definitely better. [9d47e15](https://github.com/paritytech/polkadot-sdk/pull/8533/commits/9d47e15417b4cf3fe54ec942fc883f852e494b32)

File: substrate/client/transaction-pool/src/fork_aware_txpool/fork_aware_txpool.rs (hunk 10 above)
Comment (iulianbarbu) [reply substrate/client/transaction-pool/src/fork_aware_txpool/fork_aware_txpool.rs]: Did it here: [9d47e15](https://github.com/paritytech/polkadot-sdk/pull/8533/commits/9d47e15417b4cf3fe54ec942fc883f852e494b32) + [5d7c1fb](https://github.com/paritytech/polkadot-sdk/pull/8533/commits/5d7c1fb93a339fe98078354f57e28b676ce44de7)

File: substrate/client/transaction-pool/src/fork_aware_txpool/fork_aware_txpool.rs [hunk 15]
```diff
@@ -539,10 +495,19 @@ where
 			return Box::new(std::iter::empty());
 		};
 
+		let at_hn = HashAndNumber { hash: at, number: at_number };
+		let last_finalized = self.enactment_state.lock().recent_finalized_block();
+		// Return an empty ready txs set as well if we can not resolve the recent finalized block
+		// number.
+		let Some(last_finalized_number) = self.api.resolve_block_number(last_finalized).ok() else {
+			return Box::new(std::iter::empty());
```
Comment (michalkucharczyk) [inline substrate/client/transaction-pool/src/fork_aware_txpool/fork_aware_txpool.rs:503]: I think we misunderstood each other, sorry for not being clear enough.
In this case we can also return recent best block - no reason to provide empty set.

File: substrate/client/transaction-pool/src/fork_aware_txpool/view_store.rs [hunk 16]
```diff
@@ -338,6 +338,40 @@ where
...
+				return Some((view, enacted_blocks));
+			}
+
+			enacted_blocks.push(at_hash);
+
+			// Move up into the fork. Return with no view and an empty enacted blocks
+			// list if we can't access the header of the current block.
+			let header = self.api.block_header(at_hash).ok().flatten()?;
+			at_hash = *header.parent_hash();
+			at_number = at_number.saturating_sub(1u32.into());
```
Comment (michalkucharczyk) [inline substrate/client/transaction-pool/src/fork_aware_txpool/view_store.rs:369]: would be good to cross-check this assumption (as I mentioned I did not find verification of this in import block / header verification code. I saw it only in builder code). Another pair of eyes appreciated (cc: @skunert )

**Review by michalkucharczyk — APPROVED** [review]

File: substrate/client/transaction-pool/tests/fatp.rs [hunk 17]
```diff
@@ -2342,6 +2344,79 @@ fn fatp_ready_light_long_fork_retracted_works() {
...
+	assert!(results.iter().all(|r| { r.is_ok() }));
+
+	// Calling `ready_at_light` now on the last block of a fork, with no block notified as best.
+	// We should still get the ready txs from the most recent view processed by the txpool,
+	// but now with a few more txs which were submitted previously.
+	let mut ready_iterator = pool.ready_at_light(header03b.hash()).now_or_never().unwrap();
+	assert!(ready_iterator.next().is_some());
+	assert!(ready_iterator.next().is_some());
+	assert!(ready_iterator.next().is_some());
+	assert!(ready_iterator.next().is_some());
```
[the remark this answers is not in the document]
Comment (iulianbarbu) [reply substrate/client/transaction-pool/tests/fatp.rs]: [897ddfb](https://github.com/paritytech/polkadot-sdk/pull/8533/commits/897ddfb7c8fa7d7b1c35f2cad1ff715ef3b031b6)

File: substrate/client/transaction-pool/src/fork_aware_txpool/fork_aware_txpool.rs (hunk 15 above)
Comment (iulianbarbu) [reply substrate/client/transaction-pool/src/fork_aware_txpool/fork_aware_txpool.rs:503]: Do you think it is worth doing the same in case we can not relsolve `at` block numer too?

Comment (iulianbarbu) [reply substrate/client/transaction-pool/src/fork_aware_txpool/fork_aware_txpool.rs]: Changed it so: [15afbb3](https://github.com/paritytech/polkadot-sdk/pull/8533/commits/15afbb349c9a4d6932c819e878ad9933febdc066). Didn't make a change for the question above.

Comment (michalkucharczyk) [reply substrate/client/transaction-pool/src/fork_aware_txpool/fork_aware_txpool.rs]: > Do you think it is worth doing the same in case we can not relsolve `at` block numer too?

Yes. If anything goes the most recent view should be returned.
But I think it is already handled - if we can't resolve `at` header - `find_view_descendent_upto_number` will return `None`. So should be good.

File: substrate/client/transaction-pool/src/fork_aware_txpool/mod.rs [hunk 18]
```diff
@@ -209,14 +209,15 @@
 //! ### Light maintain
 //! The [maintain](#maintain) procedure can sometimes be quite heavy, and it may not be accomplished
 //! within the time window expected by the block builder. On top of that block builder may want to
-//! build few blocks in the raw, not giving the pool enough time to accomplish possible ongoing
+//! build few blocks in the row, not giving the pool enough time to accomplish possible ongoing
 //! maintain process.
 //!
 //! To address this, there is a [light version][`ready_at_light`] of the maintain procedure. It
 //! [finds the best view][find_best_view], clones it and prunes all the transactions that were
```
Comment (michalkucharczyk) [inline substrate/client/transaction-pool/src/fork_aware_txpool/mod.rs:216]: Last nit, I realized that this description is a bit far from reality - my mistake. You could add here a link to newly added function from `ViewStore`.  IIRC `find_best_view` was never used in `ready_at_light`.

File: substrate/client/transaction-pool/src/fork_aware_txpool/fork_aware_txpool.rs [hunk 19]
```diff
@@ -487,35 +490,30 @@ where
 			"fatp::ready_at_light"
 		);
 
-		let Ok(block_number) = self.api.resolve_block_number(at) else {
-			return Box::new(std::iter::empty())
+		// Return an empty ready txs set if we can not resolve `at` block number.
+		let Ok(at_number) = self.api.resolve_block_number(at) else {
+			return Box::new(std::iter::empty());
```
Comment (iulianbarbu) [inline substrate/client/transaction-pool/src/fork_aware_txpool/fork_aware_txpool.rs:495]: @michalkucharczyk , I meant here. If we can't resolve `at` block number, we return earlier than calling `find_view_descendent_upto_number`. That means we'd return the most recent view ready txs in every case the API calls fail. We can do something like this:

```
self.api.resolve_block_number(at).ok()
    .and_then(|at_number|
        self.api.resolve_block_number(self.enactment_state.lock().recent_finalized_block()).ok()
           .and_then(|last_finalized_number| (at_number, last_finalized_number)))
    .and_then(|(at_number, last_finalized_number)| {
        let at_hn = HashAndNumber { hash: at, number: at_number };
        self.view_store.find_view_descendent_upto_number(&at_hn, last_finalized_number)
            .map(|(views, enacted_blocks)| (views, enacted_blocks, at_hn)));
```

File: substrate/client/transaction-pool/src/fork_aware_txpool/fork_aware_txpool.rs (hunk 15 above)
Comment (iulianbarbu) [reply substrate/client/transaction-pool/src/fork_aware_txpool/fork_aware_txpool.rs]: Resolving in favour of https://github.com/paritytech/polkadot-sdk/pull/8533#discussion_r2095889942.

File: substrate/client/transaction-pool/src/fork_aware_txpool/fork_aware_txpool.rs (hunk 19 above)
Comment (michalkucharczyk) [reply substrate/client/transaction-pool/src/fork_aware_txpool/fork_aware_txpool.rs:495]: a bit complex :see_no_evil: 
Not sure if this readable - maybe we should just return :)

But yeah, in case of this failure we also should fallback to the recent view.

File: substrate/client/transaction-pool/src/fork_aware_txpool/mod.rs (hunk 18 above)
Comment (iulianbarbu) [reply substrate/client/transaction-pool/src/fork_aware_txpool/mod.rs]: Done here: [f0bc263](https://github.com/paritytech/polkadot-sdk/pull/8533/commits/f0bc263b91fdfdd4983f8c0f69817ddc7e9b0b16).

File: substrate/client/transaction-pool/src/fork_aware_txpool/view_store.rs (hunk 16 above)
Comment (michalkucharczyk) [inline substrate/client/transaction-pool/src/fork_aware_txpool/view_store.rs:369]: Would that work?
```suggestion
			at_number = at_number.saturating_sub(One::one());
```

Comment (iulianbarbu) [reply substrate/client/transaction-pool/src/fork_aware_txpool/view_store.rs]: it works: [2570fa3](https://github.com/paritytech/polkadot-sdk/pull/8533/commits/2570fa35c3c0e202b6e3cd2719ba4ce22cb3b44d).

File: substrate/client/transaction-pool/src/fork_aware_txpool/view_store.rs [hunk 20]
```diff
@@ -338,6 +338,40 @@ where
 		self.active_views.read().is_empty() && self.inactive_views.read().is_empty()
 	}
 
+	/// Searches in the view store for the first descendant view by iterating through the fork of
+	/// the `at` block, up to the provided `block_number`.
+	///
+	/// Returns with a maybe pair of a view and a set of enacted blocks when the first view is
+	/// found.
+	pub(super) fn find_view_descendent_upto_number(
```
Comment (bkchr) [inline substrate/client/transaction-pool/src/fork_aware_txpool/view_store.rs:346]:
```suggestion
	pub(super) fn find_view_descendent_up_to_number(
```

File: substrate/client/transaction-pool/src/fork_aware_txpool/view_store.rs [hunk 21]
```diff
@@ -338,6 +338,40 @@ where
...
+		&self,
+		at: &HashAndNumber<Block>,
+		block_number: <<Block as BlockT>::Header as Header>::Number,
```
Comment (bkchr) [inline substrate/client/transaction-pool/src/fork_aware_txpool/view_store.rs:349]:
```suggestion
		up_to: <<Block as BlockT>::Header as Header>::Number,
```

File: substrate/client/transaction-pool/src/fork_aware_txpool/view_store.rs [hunk 22]
```diff
@@ -338,6 +338,40 @@ where
...
+	) -> Option<(Arc<View<ChainApi>>, Vec<Block::Hash>)> {
+		let mut enacted_blocks = Vec::new();
+		let mut at_hash = at.hash;
+		let mut at_number = at.number;
+
+		// Search for a view that can be used to get and return an approximate ready
+		// transaction set.
+		while at_number > block_number {
```
Comment (bkchr) [inline substrate/client/transaction-pool/src/fork_aware_txpool/view_store.rs:357]:
```suggestion
		while at_number >= block_number {
```

Otherwise you are not taking the finalized view?

File: substrate/client/transaction-pool/src/fork_aware_txpool/view_store.rs [hunk 23]
```diff
@@ -338,6 +338,40 @@ where
...
+			enacted_blocks.push(at_hash);
+
+			// Move up into the fork. Return with no view and an empty enacted blocks
+			// list if we can't access the header of the current block.
+			let header = self.api.block_header(at_hash).ok().flatten()?;
+			at_hash = *header.parent_hash();
+			at_number = at_number.saturating_sub(One::one());
+		}
+
+		return None;
```
Comment (bkchr) [inline substrate/client/transaction-pool/src/fork_aware_txpool/view_store.rs:372]:
```suggestion
		None
```

**Review by bkchr — APPROVED** [review]

File: substrate/client/transaction-pool/src/fork_aware_txpool/view_store.rs (hunk 21 above)
Comment (iulianbarbu) [reply substrate/client/transaction-pool/src/fork_aware_txpool/view_store.rs]: [a9a337d](https://github.com/paritytech/polkadot-sdk/pull/8533/commits/a9a337d7cc2cbb2332c24eaec4b8517ecd22aea0)

File: substrate/client/transaction-pool/src/fork_aware_txpool/view_store.rs (hunk 22 above)
Comment (iulianbarbu) [reply substrate/client/transaction-pool/src/fork_aware_txpool/view_store.rs]: [a9a337d](https://github.com/paritytech/polkadot-sdk/pull/8533/commits/a9a337d7cc2cbb2332c24eaec4b8517ecd22aea0)

File: substrate/client/transaction-pool/src/fork_aware_txpool/view_store.rs (hunk 23 above)
Comment (iulianbarbu) [reply substrate/client/transaction-pool/src/fork_aware_txpool/view_store.rs]: [a9a337d](https://github.com/paritytech/polkadot-sdk/pull/8533/commits/a9a337d7cc2cbb2332c24eaec4b8517ecd22aea0)

File: substrate/client/transaction-pool/src/fork_aware_txpool/view_store.rs (hunk 20 above)
Comment (iulianbarbu) [reply substrate/client/transaction-pool/src/fork_aware_txpool/view_store.rs]: [a9a337d](https://github.com/paritytech/polkadot-sdk/pull/8533/commits/a9a337d7cc2cbb2332c24eaec4b8517ecd22aea0)
