### PR TITLE
substrate-offchain: upgrade hyper to v1

### LINKED ISSUE #4896: offchain http: upgrade hyper to v1
Ideally, substrate shouldn't use two different versions of hyper.

There is one thing that is blocking it which isn't trivial to fix in the offchain http depends on low-level body stuff that isn't exposed anymore and needs to re-written.

Code such as [this](https://github.com/paritytech/polkadot-sdk/blob/master/substrate/client/offchain/src/api/http.rs#L145) doesn't work anymore because that Body and APIs around has been removed....

### PR DESCRIPTION
**Pull request by ShoyuVanilla**
Closes #4896

### CODE REVIEW

**Review by bkchr — APPROVED** [review]

**Comment by ShoyuVanilla** [comment]
I've fixed fmt fails with rustfmt nightly but still have to fix some tests are failing in CI (worked fine on my apple silicon mac)

File: substrate/client/offchain/src/api/http.rs [hunk 1]
```diff
@@ -48,20 +51,28 @@ use std::{
...
+pub struct SharedClient(
+	Arc<Lazy<HyperClient<HttpsConnector<client::connect::HttpConnector>, Body>>>,
+);
 
 impl SharedClient {
 	pub fn new() -> Self {
 		Self(Arc::new(Lazy::new(|| {
 			let connector = HttpsConnectorBuilder::new()
-				.with_native_roots()
+				.with_provider_and_native_roots(rustls::crypto::aws_lc_rs::default_provider())
```
Comment (ShoyuVanilla) [inline substrate/client/offchain/src/api/http.rs:69]: This might fix the previous test failures on this PR.
Or we can set process-wide crypto provider like in this example;
https://github.com/rustls/hyper-rustls/blob/4d5fe9a608a85b17acfe9fdddeca7509bb349320/examples/client.rs#L30-L33

Comment (niklasad1) [reply substrate/client/offchain/src/api/http.rs:69]: Replace `aws_lc_rc` and enable `ring` instead.
To use `aws_lc_rc` it's a big change which requires more build dependencies....

File: substrate/client/offchain/src/api/http.rs [hunk 2]
```diff
@@ -48,20 +51,28 @@ use std::{
...
+				.expect("Failed to build HttpsConnector with native roots")
```
Comment (niklasad1) [inline substrate/client/offchain/src/api/http.rs:70]: return error here instead of expect

File: Cargo.toml [hunk 3]
```diff
@@ -797,10 +797,8 @@ http = { version = "1.1" }
 http-body = { version = "1", default-features = false }
 http-body-util = { version = "0.1.2", default-features = false }
 hyper = { version = "1.3.1", default-features = false }
-hyper-rustls = { version = "0.24.2" }
+hyper-rustls = { version = "0.27.3" }
```
Comment (niklasad1) [inline Cargo.toml:800]:
```suggestion
hyper-rustls = { version = "0.27.3", default-feature = false, features = ["http1", "http2", "tls12", "logging", "ring"] }
```

File: Cargo.toml [hunk 4]
```diff
@@ -1115,6 +1113,7 @@ rstest = { version = "0.18.2" }
 rustc-hash = { version = "1.1.0" }
 rustc-hex = { version = "2.1.0", default-features = false }
 rustix = { version = "0.36.7", default-features = false }
+rustls = { version = "0.23.14" }
```
Comment (niklasad1) [inline Cargo.toml:1116]:
```suggestion
rustls = { version = "0.23.14", default-features = false, features = ["logging", "std", "tls12", "ring"]  }
```

File: substrate/client/offchain/src/api/http.rs (hunk 2 above)
Comment (ShoyuVanilla) [reply substrate/client/offchain/src/api/http.rs:70]: That would make a breaking change. Would it be okay?

Comment (niklasad1) [reply substrate/client/offchain/src/api/http.rs:70]: yes

File: substrate/client/offchain/src/api/http.rs [hunk 5]
```diff
@@ -48,21 +48,26 @@ use std::{
 
 const LOG_TARGET: &str = "offchain-worker::http";
 
+pub type Body = BoxBody<hyper::body::Bytes, hyper::Error>;
+
+type Sender = mpsc::Sender<Result<hyper::body::Frame<hyper::body::Bytes>, hyper::Error>>;
+type Receiver = mpsc::Receiver<Result<hyper::body::Frame<hyper::body::Bytes>, hyper::Error>>;
+
+type HyperClient = client::Client<HttpsConnector<client::connect::HttpConnector>, Body>;
+type LazyClient = Lazy<HyperClient, Box<dyn FnOnce() -> HyperClient + Send>>;
```
Comment (ShoyuVanilla) [inline substrate/client/offchain/src/api/http.rs:57]: Once rustc has stabilized TAIT, this boxing can be avoided.
The other option is implementing similar thing as `once_cell::Lazy` with `once_cell::OnceCell` and `std::cell::Cell`

File: substrate/client/offchain/src/api/http.rs [hunk 6]
```diff
@@ -48,21 +48,26 @@ use std::{
...
-				.build();
-			HyperClient::builder().build(connector)
-		})))
+	pub fn new() -> std::io::Result<Self> {
+		let builder = HttpsConnectorBuilder::new()
+			.with_provider_and_native_roots(rustls::crypto::ring::default_provider())?;
+		Ok(Self(Arc::new(Lazy::new(Box::new(|| {
+			let connector = builder.https_or_http().enable_http1().enable_http2().build();
+			client::Client::builder(TokioExecutor::new()).build(connector)
+		})))))
```
Comment (ShoyuVanilla) [inline substrate/client/offchain/src/api/http.rs:70]: The above boxing is needed to resolve this; This should be a `Lazy` with closure, otherwise we cannot return `std::io::Result<Self>` and `Self.0` becomes `Lazy<std::io::Result<HyperClient>>`, which is quite inconvenient to use

File: substrate/client/offchain/src/api/http.rs [hunk 7]
```diff
@@ -48,21 +48,26 @@ use std::{
...
-				.with_native_roots()
-				.https_or_http()
-				.enable_http1()
-				.enable_http2()
-				.build();
-			HyperClient::builder().build(connector)
-		})))
+	pub fn new() -> std::io::Result<Self> {
+		let builder = HttpsConnectorBuilder::new()
+			.with_provider_and_native_roots(rustls::crypto::ring::default_provider())?;
```
Comment (niklasad1) [inline substrate/client/offchain/src/api/http.rs:66]:
```suggestion
			.with_native_roots()?;
```

File: substrate/client/offchain/src/lib.rs [hunk 8]
```diff
@@ -160,7 +160,7 @@ impl<RA, Block: traits::Block, Storage> OffchainWorkers<RA, Block, Storage> {
 				"offchain-worker".into(),
 				num_cpus::get(),
 			)),
-			shared_http_client: api::SharedClient::new(),
+			shared_http_client: api::SharedClient::new().unwrap(),
```
Comment (niklasad1) [inline substrate/client/offchain/src/lib.rs:163]: Ok, this requires unwrap anyway...

@bkchr Is it ok to move the `shared_http_client` to the `OffchainWorkerOptions type` such that we can bail early from the service builder if this fails?

File: substrate/client/offchain/src/api/http.rs (hunk 7 above)
Comment (ShoyuVanilla) [reply substrate/client/offchain/src/api/http.rs:66]: It seems that recent `rustls` versions are panicking without provided or process-wide crypto provider
https://github.com/paritytech/polkadot-sdk/actions/runs/11173098681/job/31131298329

```
--- TRY 1 STDERR:        sc-offchain api::http::tests::request_add_header_invalid_call ---
thread 'tokio-runtime-worker' panicked at /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/rustls-0.23.10/src/crypto/mod.rs:259:14:
no process-level CryptoProvider available -- call CryptoProvider::install_default() before this point
```

Should I set it in test code with [CryptoProvider::install_default()](https://docs.rs/rustls/latest/rustls/crypto/struct.CryptoProvider.html#method.install_default) and leave calling it to user in the library level?

File: substrate/client/offchain/src/lib.rs (hunk 8 above)
Comment (ShoyuVanilla) [reply substrate/client/offchain/src/lib.rs:163]: Oh, I thought that all the `unwrap()` calls were inside the test codes but this was not 🙃

**Comment by niklasad1** [comment]
bot fmt

File: substrate/client/offchain/src/lib.rs (hunk 8 above)
Comment (niklasad1) [reply substrate/client/offchain/src/lib.rs:163]: I think we should handle the error [here](https://github.com/paritytech/polkadot-sdk/blob/master/substrate/bin/node/cli/src/service.rs#L785-#L806) and just pass SharedHttpClient in the OffChainWorkerOptions instead to avoid breaking this api.

but better to wait what @bkchr thinks is the best way :)

**Review by niklasad1 — APPROVED** [review]
Looks good to me modulo the unwrap stuff

**Comment by ShoyuVanilla** [comment]
Formatted `Cargo.toml`. I'll write prdoc soon

File: substrate/client/offchain/src/lib.rs (hunk 8 above)
Comment (ShoyuVanilla) [reply substrate/client/offchain/src/lib.rs:163]: Okay. I'll wait for 😃

Comment (bkchr) [reply substrate/client/offchain/src/lib.rs:163]: > I think we should handle the error [here](https://github.com/paritytech/polkadot-sdk/blob/master/substrate/bin/node/cli/src/service.rs#L785-#L806) and just pass SharedHttpClient in the OffChainWorkerOptions instead to avoid breaking this api.

We will break the API any way :see_no_evil: As we need to do it, I think returning `Result` from `new` sounds better to me

Comment (ShoyuVanilla) [reply substrate/client/offchain/src/lib.rs:163]: > > I think we should handle the error [here](https://github.com/paritytech/polkadot-sdk/blob/master/substrate/bin/node/cli/src/service.rs#L785-#L806) and just pass SharedHttpClient in the OffChainWorkerOptions instead to avoid breaking this api.
> 
> We will break the API any way 🙈 As we need to do it, I think returning `Result` from `new` sounds better to me

Do you mean this `new` method, `OffchainWorkers::new`?

**Comment by ShoyuVanilla** [comment]
I have no idea why `continuous-integration/gitlab-zombienet-polkadot-smoke-0005-precompile-pvf-smoke` fails 🤔 
https://gitlab.parity.io/parity/mirrors/polkadot-sdk/-/jobs/7556991

File: substrate/client/offchain/Cargo.toml [hunk 9]
```diff
@@ -22,15 +22,15 @@ codec = { features = ["derive"], workspace = true, default-features = true }
 fnv = { workspace = true }
 futures = { workspace = true }
 futures-timer = { workspace = true }
-hyperv14 = { features = [
-	"http2",
-	"stream",
-], workspace = true, default-features = true }
+http-body-util = { workspace = true }
+hyper = { features = ["http2"], workspace = true, default-features = true }
 hyper-rustls = { features = ["http2"], workspace = true }
```
Comment (niklasad1) [inline substrate/client/offchain/Cargo.toml:27]: we already enable http1 and http2 globally in the workspace

```suggestion
hyper-rustls = { workspace = true }
```

File: substrate/client/offchain/Cargo.toml [hunk 10]
```diff
@@ -22,15 +22,15 @@ codec = { features = ["derive"], workspace = true, default-features = true }
...
+hyper-util = { features = ["client-legacy"], workspace = true }
```
Comment (niklasad1) [inline substrate/client/offchain/Cargo.toml:28]:
```suggestion
hyper-util = { features = ["client-legacy", "http1", "http2"], workspace = true }
```

**Review by niklasad1 — APPROVED** [review]
nice work, LGTM

**Comment by ShoyuVanilla** [comment]
The CI failure seems to be caused from docker image push timeout. I wonder if I should take some action for it 🤔

File: prdoc/pr_5919.prdoc [hunk 11]
```diff
@@ -0,0 +1,19 @@
...
+doc:
+  - audience: Node Dev
+    description: |
+      Bump depencency `hyper` of `substrait-offchain` for http from `0.14` to `1`.
+      This changed APIs a bit;
+      - `sc_offchain::Offchainworker::new()` now returns `std::io::Result<Self>` (Previously was `Self`)
+
+crates:
+  - name: sc-offchain
+    bump: minor
```
Comment (bkchr) [inline prdoc/pr_5919.prdoc:15]:
```suggestion
    bump: major
```

**Review by bkchr — APPROVED** [review]

File: prdoc/pr_5919.prdoc (hunk 11 above)
Comment (ShoyuVanilla) [reply prdoc/pr_5919.prdoc]: Thanks! I've applied this change

**Comment by ShoyuVanilla** [comment]
I'm rebasing to re-trigger failed actions

**Comment by niklasad1** [comment]
> I'm rebasing to re-trigger failed required-actions

You don't have to do that, that merge queue will merge it to master before running the tests anyway. By rebasing now you removed this from the merge queue....  Some job is probably flaky but don't rebase again and let's try to add it to the merge queue again.

**Comment by ShoyuVanilla** [comment]
> > I'm rebasing to re-trigger failed required-actions
> 
> You don't have to do that, that merge queue will merge it to master before running the tests anyway. By rebasing now you removed this from the merge queue.... Some job is probably flaky but don't rebase again and let's try to add it to the merge queue again.

Oh, I thought that "required" checks were necessary 😅 Sorry

**Comment by niklasad1** [comment]
> Oh, I thought that "required" checks were necessary 😅 Sorry

Yeah, they are but these failed checks are really unrelated to your PR and "might" have been fixed on master concurrently, it's fine to rebase just avoid to do it when it's added to the merge queue.

**Comment by bkchr** [comment]
@ShoyuVanilla please merge master

**Comment by jasl** [comment]
Hi, this one seems still CI broken

**Comment by ShoyuVanilla** [comment]
> Hi, this one seems still CI broken

@jasl Is there anything that I should/could do for CI failure? I'm not familiar with CI and not sure the failure is related to this PR or not 😅

**Comment by niklasad1** [comment]
> @jasl Is there anything that I should/could do for CI failure? I'm not familiar with CI and not sure the failure is related to this PR or not 😅

try rebase one more time, sorry about this

**Comment by ShoyuVanilla** [comment]
> try to rebase one more time, sorry about this

No problem 😄
