### PR TITLE
finalization: Skip tree route calculation if no forks present

### LINKED ISSUE #4614: Cant sync a kusama-people node from scratch with 1.12, working with 1.11, regression?
Hi!

I cant sync a kusama people parachain node. I am experiencing troubles I have never seem when running all other nodes.

I am using docker distribution: polkadot-parachain:1.12.0, I use the RelayChain RPC interface. 

I vanilla start with  `docker run --rm parity/polkadot-parachain:1.12.0 --chain people-kusama` complaints about most (or all, not sure) nodes having a genesis mistmatch:

```
2024-05-28 09:37:31 [Parachain] Report 12D3KooWS7uzh62LChjfbyYGj1U5yGYaKNWMzzh6AAWHiJ5aLYLH: -2147483648 to -2147483648. Reason: Genesis mismatch. Banned, disconnecting.
```

I then restrict to boot nodes only using flags `reserved-only` and the boot nodes as reserved nodes, and then I get  parachain blocks.... however no finalizations,

eventually I reach the top of the chain, also using the RelayChain RPC interface: 

```
2024-05-28 09:40:46 [Parachain] ⚙️  Preparing  0.0 bps, target=#94115 (1 peers), best: #94015 (0x2dee…a9c6), finalized #0 (0xc1af…8b3f), ⬇ 12 B/s ⬆ 26 B/s
```
but no blocks appear to be finalized, 

and eventually I get this other warning constantly:

```
2024-05-28 09:40:42 [Parachain] Event distribution channel has reached its limit. This can lead to missed notifications. error=TrySendError { kind: Full }
```

I am not sure what is going on. I am using the new default `--prune archive-canonical` and tried also the different sync modes (fast, warp) but nothing seems to make a difference.

I have also tried to use the polkadot-collator image but does not seem to have the kusama people spec.

What am I missing?

### PR DESCRIPTION
**Pull request by skunert**
## Issue

Currently, syncing parachains from scratch can lead to a very long finalization time once they reach the tip of the chain. The problem is that we try to finalize everything from 0 to the tip, which can be thousands or even millions of blocks.

We finalize sequentially and try to compute displaced branches during finalization. So for every block on the way, we compute an expensive tree route.

## Proposed Improvements

In this PR, I propose improvements that solve this situation:

- **Skip tree route calculation if `leaves().len() == 1`:** This should be enough for 90% of cases where there is only one leaf after sync.
- **Optimize finalization for long distances:** It can happen that the parachain has imported some leaf and then receives a relay chain notification with the finalized block. In that case, the previous optimization will not trigger. A second mechanism should ensure that we do not need to compute the full tree route. If the finalization distance is long, we check the lowest common ancestor of all the leaves. If it is above the to-be-finalized block, we know that there are no displaced leaves. This is fast because forks are short and close to the tip, so we can leverage the header cache.

## Alternative Approach

- The problem was introduced in #3962. Reverting that PR is another possible strategy.
- We could store for every fork where it begins, however sounds a bit more involved to me.

fixes #4614

### CODE REVIEW

**Comment by burdges** [comment]
Around this, how do we hash headers?

It's often problematic if we do `H(big_header)` with parent in `big_header`.  It's often faster if we do `H(small_header, H(big_header))` with the parent hash in `small_header`.

File: substrate/client/db/src/lib.rs [hunk 1]
```diff
@@ -3108,6 +3108,111 @@ pub(crate) mod tests {
 		}
 	}
 
+	#[test]
+	fn lowest_common_ancestors_multiblock_works() {
+		let backend = Backend::<Block>::new_test(1000, 100);
+		let blockchain = backend.blockchain();
+		let block0 = insert_header(&backend, 0, Default::default(), None, Default::default());
+
+		// fork from genesis: 3 prong.
```
Comment (lexnv) [inline substrate/client/db/src/lib.rs:3117]: nit: Maybe a comment to quickly have the tree in view?

```
block 0 -> a1 -> a2 -> a3
       |
        -> b1 -> b2 -> c1 -> c2
              |      
              -> d1 -> d2
```

File: substrate/client/db/src/lib.rs [hunk 2]
```diff
@@ -3108,6 +3108,111 @@ pub(crate) mod tests {
...
+
+		{
+			let lca = lowest_common_ancestor_multiblock(blockchain, vec![a1, a2, a3])
+				.unwrap()
+				.unwrap();
+
+			assert_eq!(lca.hash, a1);
+			assert_eq!(lca.number, 1);
+		}
+
```
Comment (lexnv) [inline substrate/client/db/src/lib.rs:3201]: nit: could check b1, b2, d1, just to double check the b1 forked node is returned

File: substrate/primitives/blockchain/src/backend.rs [hunk 3]
```diff
@@ -229,10 +228,37 @@ pub trait Backend<Block: BlockT>:
...
 
-		if finalized_block_number == Zero::zero() {
+		let leaves = self.leaves()?;
+
+		// If we have only one leaf there are no forks, and we can return early.
+		if finalized_block_number == Zero::zero() || leaves.len() == 1 {
 			return Ok(result)
 		}
 
+		let first_leaf = leaves[0];
```
Comment (lexnv) [inline substrate/primitives/blockchain/src/backend.rs:238]: nit: `let Some(first_leaf) = leaves.get(0) else {..}` since this may panic if leaves is empty (although I think its unlikely)

**Review by lexnv — APPROVED** [review]
LGTM!

File: substrate/primitives/blockchain/src/backend.rs [hunk 4]
```diff
@@ -229,10 +228,37 @@ pub trait Backend<Block: BlockT>:
...
+				if lca.number > finalized_block_number {
+					return Ok(result)
+				} else {
+					log::warn!("The distance between leafs and finalized block is large. Finalization can take a long time.");
+				}
+			};
+		}
+
 		// For each leaf determine whether it belongs to a non-canonical branch.
 		for leaf_hash in self.leaves()? {
```
Comment (lexnv) [inline substrate/primitives/blockchain/src/backend.rs:263]: nit: should we use the same `let leaves = self.leaves()?;` here?

File: substrate/primitives/blockchain/src/backend.rs [hunk 5]
```diff
@@ -229,10 +228,37 @@ pub trait Backend<Block: BlockT>:
...
+		// tree routes can be very expensive. In that case, we will try to find the
+		// lowest common ancestor between all the leaves. The assumption here is that the forks are
+		// close to the tip and not long. So the LCA can be computed from the header cache. If the
+		// LCA is above the finalized block, we know that there are no displaced leaves by the
+		// finalization.
+		if leaf_block_header
+			.number()
+			.checked_sub(&finalized_block_number)
+			.unwrap_or(0u32.into()) >
+			header_metadata::LRU_CACHE_SIZE.into()
```
Comment (bkchr) [inline substrate/primitives/blockchain/src/backend.rs:251]: You should use the value for the forced canonicalization here.

File: substrate/primitives/blockchain/src/header_metadata.rs [hunk 6]
```diff
@@ -96,6 +96,27 @@ pub fn lowest_common_ancestor<Block: BlockT, T: HeaderMetadata<Block> + ?Sized>(
...
+		return Ok(None);
+	}
+
+	// Start with the first hash as the initial LCA
+	let cached = backend.header_metadata(hashes[0])?;
+	let mut lca = HashAndNumber { number: cached.number, hash: cached.hash };
+	for hash in hashes.iter().skip(1) {
+		// Calculate the LCA of the current LCA and the next hash
+		lca = lowest_common_ancestor(backend, lca.hash, *hash)?;
+	}
```
Comment (michalkucharczyk) [inline substrate/primitives/blockchain/src/header_metadata.rs:115]: nit: `next()` could be used instead of `[0]` and `skip(1)`.

**Review by michalkucharczyk — APPROVED** [review]

File: substrate/primitives/blockchain/src/backend.rs (hunk 5 above)
Comment (skunert) [reply substrate/primitives/blockchain/src/backend.rs:253]: Why? I am not so sure what force canonicalization has to do with this? Maybe I am missing something, but afaik it only  affects for the state-db.

The idea with the cache size was that the tree route gets expensive once we read from disk. And the cache size is lower than the force canonicalization delay, wo we would benefit earlier.

**Review by davxy — APPROVED** [review]
