### PR TITLE
fix: support `paginationStartKey` parameter for `archive_v1_storage`

### LINKED ISSUE #10185: Support `paginationStartKey` parameter in the `archive_v1_storage` JSON-RPC API
### Is there an existing issue?

- [x] I have searched the existing issues

### Experiencing problems? Have you tried our Stack Exchange first?

- [x] This is not a support question.

### Request

Per the latest [archive_v1_storage](https://paritytech.github.io/json-rpc-interface-spec/api/archive_v1_storage.html) specification, the `paginationStartKey` parameter enables specifying a starting key for fetching storage items, which facilitates paginated retrieval.

It appears that the current implementation of `archive_v1_storage` does not yet support this parameter. Do we have plans to add support for it to ensure the API aligns with the specification?

https://github.com/paritytech/polkadot-sdk/blob/fd2bfd59c5c5ddb561cb1a2d60df3dd4b4d343cc/substrate/client/rpc-spec-v2/src/archive/archive.rs#L217-L266

### PR DESCRIPTION
**Pull request by sinzii**
Fixes #10185

This PR is to add support for `paginationStartKey` parameter in `archive_v1_storage` JSON RPC API for query type: `descendantsValues` and `descendantsHashes` per [the latest specs](https://paritytech.github.io/json-rpc-interface-spec/api/archive_v1_storage.html).

### CODE REVIEW

**Review by bkchr — APPROVED** [review]
LGTM, great work!

File: substrate/client/rpc-spec-v2/src/archive/tests.rs [hunk 1]
```diff
@@ -743,6 +777,343 @@ async fn archive_storage_iterations() {
...
+		.push_storage_change(b":test:2".to_vec(), Some(b"val2".to_vec()))
+		.unwrap();
+	builder
+		.push_storage_change(b":test:3".to_vec(), Some(b"val3".to_vec()))
+		.unwrap();
+	let block = builder.build().unwrap().block;
+	let block_hash = format!("{:?}", block.header.hash());
+	client.import(BlockOrigin::Own, block.clone()).await.unwrap();
+
+	// let expected_hash_1 = format!("{:?}", Blake2Hasher::hash(b"val1"));
```
Comment (lexnv) [inline substrate/client/rpc-spec-v2/src/archive/tests.rs]: nit: Let's remove the stale comment

**Review by lexnv — APPROVED** [review]
Amazing PR! Lovely test scenarios! Thanks again for contributing 🙏

File: prdoc/pr_10329.prdoc [hunk 2]
```diff
@@ -0,0 +1,10 @@
+title: 'fix: support `paginationStartKey` parameter for `archive_v1_storage`'
+doc:
+- audience: runtime_user, node_dev
```
Comment (bkchr) [inline prdoc/pr_10329.prdoc]:
```suggestion
- audience: node-dev
```

**Comment by sinzii** [comment]
Thanks a lot @bkchr and @lexnv for the reviews and approvals, I've just pushed the updates following your suggestions!

File: prdoc/pr_10329.prdoc [hunk 3]
```diff
@@ -0,0 +1,10 @@
+title: 'fix: support `paginationStartKey` parameter for `archive_v1_storage`'
+doc:
+- audience: node-dev
```
Comment (bkchr) [inline prdoc/pr_10329.prdoc]:
```suggestion
- audience: Node Dev
```

**Comment by mhrsalehi** [comment]
I wonder why chainHead_v1_storage does not support this! Are there any plans to add support for it?

**Comment by bkchr** [comment]
@mhrsalehi there are plans, but it requires some changes to the light client protocol before.
