### PR TITLE
rpc: bump jsonrpsee v0.22 and fix race in `rpc v2 chain_head`

### LINKED ISSUE #2992: JSON-RPC messages arrive out of order
### Is there an existing issue?

- [X] I have searched the existing issues

### Experiencing problems? Have you tried our Stack Exchange first?

- [X] This is not a support question.

### Description of bug

Very often, when using the `chainHead` group of functions of new JSON-RPC API against a Polkadot-SDK node, there are "subscription" messages that come out of order. E.g:

image

What happens is that the message that announces the "opeartionId" that the client should be paying attention to, comes after the notifications for that "operationId". Since the client does not recognize those messages, then the messages get ignored.

I first experienced this against different public endpoints, and then I tried it against a local development node and I experienced the same issue. In order to further confirm that this was a problem with the implementation on the node, I tried running the same requests against smoldot while using a chainspec that had my local development node as the only bootnode, trying the same requests through smoldot (with the chainspec of a local development node) works flawlessly.

### Steps to reproduce

I have setup the [following nodejs repo](https://github.com/josepot/polkadot-sdk-json-rpc-issue) to reproduce the issue. I recommend cloning the repo and trying it out in your local environment. However, you can also try it out using [stackblitz](https://stackblitz.com/~/github.com/josepot/polkadot-sdk-json-rpc-issue).

In order to reproduce/debug what's happening:

1) clone the repo
2) run `pnpm i`
3) run `pnpm start`

Every time that the script detects a message out of order it will print these kinds of messages on the terminal:
image

The script also generates a file named `wire-logs.txt`, where you will find all the send/received messages that were seen over the WebSocket connection in the order that they happened: 
image

If you want to try against a different endpoint, then just edit [the following line](https://github.com/josepot/polkadot-sdk-json-rpc-issue/blob/2f44c6f212f53c20842bf5b7f35e002b004ed5e3/src/client/client.ts#L6).

I hope that this repo helps to investigate the issue, because it's taken me a while to set it up. 🤞

### PR DESCRIPTION
**Pull request by niklasad1**
Close #2992 

Breaking changes:
- rpc server grafana metric `substrate_rpc_requests_started` is removed (not possible to implement anymore)
- rpc server grafana metric `substrate_rpc_requests_finished` is removed  (not possible to implement anymore)
- rpc server ws ping/pong not ACK:ed within 30 seconds more than three times  then the connection will be closed

Added
- rpc server  grafana metric `substrate_rpc_sessions_time` is added to get the duration for each websocket session

### CODE REVIEW

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: cargo-clippy
**Logs**: https://gitlab.parity.io/parity/mirrors/polkadot-sdk/-/jobs/5134860

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: cargo-clippy
**Logs**: https://gitlab.parity.io/parity/mirrors/polkadot-sdk/-/jobs/5135283

File: substrate/client/rpc-servers/src/middleware/metrics.rs
Comment (niklasad1) [inline substrate/client/rpc-servers/src/middleware/metrics.rs:1]: rewrite rpc metrics as JSON-RPC middleware

File: substrate/client/rpc-servers/src/middleware/mod.rs [hunk 1]
```diff
@@ -0,0 +1,23 @@
...
+// but WITHOUT ANY WARRANTY; without even the implied warranty of
+// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
+// GNU General Public License for more details.
+
+// You should have received a copy of the GNU General Public License
+// along with this program. If not, see <https://www.gnu.org/licenses/>.
+
+//! JSON-RPC specific middleware.
+
+pub mod metrics;
```
Comment (niklasad1) [inline substrate/client/rpc-servers/src/middleware/mod.rs:21]: I plan to add rate-limit middleware here as well but I'll do it in another PR

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: cargo-clippy
**Logs**: https://gitlab.parity.io/parity/mirrors/polkadot-sdk/-/jobs/5136207

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: cargo-clippy
**Logs**: https://gitlab.parity.io/parity/mirrors/polkadot-sdk/-/jobs/5139513

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: cargo-clippy
**Logs**: https://gitlab.parity.io/parity/mirrors/polkadot-sdk/-/jobs/5141860

File: cumulus/client/relay-chain-interface/Cargo.toml [hunk 2]
```diff
@@ -22,5 +22,5 @@ sc-client-api = { path = "../../../substrate/client/api" }
 futures = "0.3.28"
 async-trait = "0.1.74"
 thiserror = "1.0.48"
-jsonrpsee-core = "0.20.3"
+jsonrpsee-core = "0.21"
```
Comment (niklasad1) [inline cumulus/client/relay-chain-interface/Cargo.toml:25]:
```suggestion
jsonrpsee-core = "0.22"
```

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: cargo-clippy
**Logs**: https://gitlab.parity.io/parity/mirrors/polkadot-sdk/-/jobs/5142011

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: cargo-clippy
**Logs**: https://gitlab.parity.io/parity/mirrors/polkadot-sdk/-/jobs/5142572

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable-int
**Logs**: https://gitlab.parity.io/parity/mirrors/polkadot-sdk/-/jobs/5142606

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: check-tracing
**Logs**: https://gitlab.parity.io/parity/mirrors/polkadot-sdk/-/jobs/5142607

File: substrate/client/rpc-servers/src/middleware/metrics.rs [hunk 3]
```diff
@@ -0,0 +1,281 @@
...
+	/// Number of calls started.
+	calls_started: CounterVec<U64>,
+	/// Number of calls completed.
+	calls_finished: CounterVec<U64>,
+	/// Number of Websocket sessions opened.
+	ws_sessions_opened: Option<Counter<U64>>,
+	/// Number of Websocket sessions closed.
+	ws_sessions_closed: Option<Counter<U64>>,
+	/// Histogram over RPC websocket sessions.
+	ws_sessions_time: HistogramVec,
```
Comment (niklasad1) [inline substrate/client/rpc-servers/src/middleware/metrics.rs:65]: I added this because I think it's useful to know the connection duration.

File: substrate/client/rpc-spec-v2/src/chain_head/chain_head.rs [hunk 4]
```diff
@@ -294,31 +308,40 @@ where
...
+			Err(err) => {
+				return ResponsePayload::error(err);
+			},
+		};
 
 		let child_trie = child_trie
 			.map(|child_trie| parse_hex_param(child_trie))
-			.transpose()?
+			.transpose()
+			.unwrap()
```
Comment (lexnv) [inline substrate/client/rpc-spec-v2/src/chain_head/chain_head.rs:330]: I think we should return `ResponsePayload::error(err)` here as well

File: substrate/client/rpc-spec-v2/src/chain_head/chain_head.rs [hunk 5]
```diff
@@ -334,16 +357,21 @@ where
 		let mut items = items;
 		items.truncate(num_operations);
 
+		let (rp, rp_is_success) = method_started_response(operation_id, Some(discarded));
+
 		let fut = async move {
+			// Events should only by generated if the response
+			// was successful.
+			if rp_is_success.await.is_err() {
```
Comment (lexnv) [inline substrate/client/rpc-spec-v2/src/chain_head/chain_head.rs:365]: Just to double check; we should propagate events only if we can propagate the  `method_started_response`, which is always a successful `ResponsePayload::success`?
In other words, the error here means we cannot send the message 🤔 

I would change this to `...if the response was successfully propagated` or something similar

File: substrate/client/rpc-servers/src/lib.rs [hunk 6]
```diff
@@ -103,33 +114,81 @@ pub async fn start_server<M: Send + Sync + 'static>(
 		.max_response_body_size(max_payload_out_mb.saturating_mul(MEGABYTE))
 		.max_connections(max_connections)
 		.max_subscriptions_per_connection(max_subs_per_conn)
-		.ping_interval(Duration::from_secs(30))
-		.set_middleware(middleware)
+		.enable_ws_ping(
+			PingConfig::new()
+				.ping_interval(Duration::from_secs(30))
+				.inactive_limit(Duration::from_secs(50)),
```
Comment (lexnv) [inline substrate/client/rpc-servers/src/lib.rs:120]: The behavior before this release was: the server sends ping frames every 30 seconds and doesn't care about pong frames.
Now the behavior is: the server sends ping frames every 30 seconds and expects at least one pong frame (or event message -- correctly me if i'm wrong here) in at most 50 seconds.

Should we bump this to 60 seconds just to be sure? Not entirely convinced myself, since most RPC apis provide a response almost immediately

File: substrate/client/rpc-servers/src/lib.rs [hunk 7]
```diff
@@ -103,33 +114,81 @@ pub async fn start_server<M: Send + Sync + 'static>(
...
+	let (stop_handle, server_handle) = stop_channel();
+	let cfg = PerConnection {
+		methods: build_rpc_api(rpc_api).into(),
+		service_builder: builder.to_service_builder().max_connections(max_connections),
+		metrics,
+		tokio_handle,
+		stop_handle: stop_handle.clone(),
 	};
 
+	let make_service = make_service_fn(move |_conn: &AddrStream| {
```
Comment (lexnv) [inline substrate/client/rpc-servers/src/lib.rs:141]: IIUC, this will go away in the next release (when bringing hyper up to date); we could then think about how to tackle this best; just to simplify a bit this function

File: substrate/client/rpc-servers/src/middleware/metrics.rs [hunk 8]
```diff
@@ -0,0 +1,281 @@
...
+	100_000.0,
+	1_000_000.0,
+	10_000_000.0,
+];
+
+/// Metrics for RPC middleware storing information about the number of requests started/completed,
+/// calls started/completed and their timings.
+#[derive(Debug, Clone)]
+pub struct RpcMetrics {
+	/// Histogram over RPC execution times.
```
Comment (lexnv) [inline substrate/client/rpc-servers/src/middleware/metrics.rs:54]: Dq; seems like we removed a couple of metrics: 

```rust
	/// Number of RPC requests received since the server started.
	requests_started: CounterVec<U64>,
	/// Number of RPC requests completed since the server started.
	requests_finished: CounterVec<U64>,
```

Do we handle them somewhere else?

**Review by lexnv — APPROVED** [review]
LGTM! From the chainHead perspective, this should handle the race! Nicely done! 🚀 

I'm not sure if we can do anything about the `requests_started` and `requests_finished` metrics; would love to hear your thoughts on this 🙏

File: substrate/client/rpc-servers/src/lib.rs [hunk 9]
```diff
@@ -103,33 +114,81 @@ pub async fn start_server<M: Send + Sync + 'static>(
...
-	let handle = if let Some(metrics) = metrics {
-		let server = builder.set_logger(metrics).build_from_tcp(std_listener)?;
-		server.start(rpc_api)
-	} else {
-		let server = builder.build_from_tcp(std_listener)?;
-		server.start(rpc_api)
+	let (stop_handle, server_handle) = stop_channel();
+	let cfg = PerConnection {
+		methods: build_rpc_api(rpc_api).into(),
+		service_builder: builder.to_service_builder().max_connections(max_connections),
```
[the remark this answers is not in the document]
Comment (niklasad1) [reply substrate/client/rpc-servers/src/lib.rs:135]:
```suggestion
		service_builder: builder.to_service_builder(),
```

File: substrate/client/rpc-servers/src/lib.rs (hunk 7 above)
Comment (niklasad1) [reply substrate/client/rpc-servers/src/lib.rs:141]: it's not a big deal, it just the we have launch the event loop and handle socket.accept() ourselves then upgrade it to towerService

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: cargo-clippy
**Logs**: https://gitlab.parity.io/parity/mirrors/polkadot-sdk/-/jobs/5152693

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable 2/3
**Logs**: https://gitlab.parity.io/parity/mirrors/polkadot-sdk/-/jobs/5152711

File: substrate/client/rpc-servers/src/middleware/metrics.rs (hunk 8 above)
Comment (niklasad1) [reply substrate/client/rpc-servers/src/middleware/metrics.rs:54]: /cc @PierreBesson any objections to break this?

File: substrate/client/rpc-servers/src/lib.rs (hunk 9 above)
[the remark this answers is not in the document]
Comment (niklasad1) [reply substrate/client/rpc-servers/src/lib.rs]: Nothing, probably just a copy-paste nit from my side

File: substrate/client/rpc-servers/src/middleware/metrics.rs (hunk 8 above)
Comment (niklasad1) [reply substrate/client/rpc-servers/src/middleware/metrics.rs:54]: Technically, before this change one could write a dashboard that actually monitored the number of batch requests by doing  `rpc_calls - rpc_requests` but I don't we are using it anyway in our dashboards.

I could add it back though I realized now because I added a tweak to know whether the response is batch or not.

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: cargo-clippy
**Logs**: https://gitlab.parity.io/parity/mirrors/polkadot-sdk/-/jobs/5213107

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: cargo-clippy
**Logs**: https://gitlab.parity.io/parity/mirrors/polkadot-sdk/-/jobs/5213353

File: prdoc/pr_3230.prdoc [hunk 10]
```diff
@@ -0,0 +1,19 @@
+# Schema: Polkadot SDK PRDoc Schema (prdoc) v1.0.0
+# See doc at https://raw.githubusercontent.com/paritytech/polkadot-sdk/master/prdoc/schema_user.json
+
+title: rpc server remove prometheus metrics substrate_rpc_requests_started/finished and refactor WS ping/pongs.
```
Comment (niklasad1) [inline prdoc/pr_3230.prdoc:4]:
```suggestion
title: rpc server remove prometheus metrics `substrate_rpc_requests_started/finished` and refactor WS ping/pongs.
```

File: prdoc/pr_3230.prdoc [hunk 11]
```diff
@@ -0,0 +1,19 @@
+# Schema: Polkadot SDK PRDoc Schema (prdoc) v1.0.0
+# See doc at https://raw.githubusercontent.com/paritytech/polkadot-sdk/master/prdoc/schema_user.json
+
+title: rpc server remove prometheus metrics `substrate_rpc_requests_started/finished` and refactor WS ping/pongs.
+
+doc:
+  - audience: Node Operator
+    description: |
+      Updates the jsonrpc library to v0.22
```
Comment (niklasad1) [inline prdoc/pr_3230.prdoc:9]:
```suggestion
      This PR updates the rpc server library to `jsonrpsee v0.22` to enable to use new APIs.
```

File: prdoc/pr_3230.prdoc [hunk 12]
```diff
@@ -0,0 +1,19 @@
...
+      This PR updates the rpc server library to `jsonrpsee v0.22` to utilize new APIs.
+
+      Breaking changes:
+      - Remove prometheus RPC metrics `substrate_rpc_requests_started` and `substrate_rpc_requests_finished`.
+      - The RPC server now disconnects inactive peers that didn't acknowledge WebSocket
+      pings more than three times in time.
+
+      Added:
+      - Add prometheus RPC `substrate_rpc_sessions_time` to collect the duration for each WebSocket
+      session in seconds.
```
Comment (niklasad1) [inline prdoc/pr_3230.prdoc:18]:
```suggestion
      session.
```

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: cargo-clippy
**Logs**: https://gitlab.parity.io/parity/mirrors/polkadot-sdk/-/jobs/5220628
