### PR TITLE
fix(collator-protocol): address unneeded collator connection issue

### LINKED ISSUE #6733: "An unneeded collator connected" when parachain runs out of core time
### Is there an existing issue?

- [X] I have searched the existing issues

### Experiencing problems? Have you tried our Stack Exchange first?

- [X] This is not a support question.

### Description of bug

Related: https://github.com/paritytech/polkadot-sdk/issues/616

I believe currently collators don't properly disconnect from validators, because I see these logs in the validators when a parachain runs out of core time:

```
2024-11-27 15:04:30.422 DEBUG tokio-runtime-worker parachain::network-bridge-rx: action="PeerConnected" peer_set=Collation version=2 peer=PeerId("12D3KooWPJT4QoqgwDWJzHZHDL8iCgkjKzswTwWGcYHHfEjBEerv") role=Full
2024-11-27 15:04:30.423 DEBUG tokio-runtime-worker parachain::collator-protocol: Declared as collator for unneeded para. Current assignments: {} peer_id=PeerId("12D3KooWPJT4QoqgwDWJzHZHDL8iCgkjKzswTwWGcYHHfEjBEerv") collator_id=Public(8e6e0feedba7494a19662e3178bc66b6801716ee4c12e304c78fde02cc96941c (14DkVhzA...)) para_id=Id(2001)
2024-11-27 15:04:30.423 DEBUG tokio-runtime-worker parachain::reputation-aggregator: Reduce reputation peer=PeerId("12D3KooWPJT4QoqgwDWJzHZHDL8iCgkjKzswTwWGcYHHfEjBEerv") rep=CostMinor("An unneeded collator connected")
2024-11-27 15:04:30.423 DEBUG tokio-runtime-worker parachain::network-bridge-rx: action="PeerDisconnected" peer_set=Collation peer=PeerId("12D3KooWPJT4QoqgwDWJzHZHDL8iCgkjKzswTwWGcYHHfEjBEerv")
2024-11-27 15:04:30.549 DEBUG tokio-runtime-worker parachain::network-bridge-rx: action="PeerConnected" peer_set=Collation version=2 peer=PeerId("12D3KooWPjcG7TYtZfkoyiTK1esowizuP48uff7RNZHR5BraMXqH") role=Full
```

It stays like this forever, with the same peer trying to connect and getting banned exactly every 1 second. Any advice on how to fix it? Although since it keeps connecting forever, the collator doesn't actually get banned so this is not a problem? Not sure.

### Steps to reproduce

Start a local testnet and remove the core assignment from the para

### PR DESCRIPTION
**Pull request by sw10pa**
## Issue
Fixes #6733.

## TODO
- [x] Fix the issue;
- [x] Add unit tests;
- [x] Add PRdoc.

### CODE REVIEW

File: polkadot/node/network/collator-protocol/src/collator_side/mod.rs [hunk 1]
```diff
@@ -1218,7 +1236,9 @@ async fn handle_our_view_change<Context>(
 
 	for leaf in added {
 		let claim_queue = fetch_claim_queue(ctx.sender(), *leaf).await?;
-		state.per_relay_parent.insert(*leaf, PerRelayParent::new(para_id, claim_queue));
+		let relay_data = PerRelayParent::new(para_id, claim_queue);
+		state.num_assigned_cores = relay_data.assignments.len();
+		state.per_relay_parent.insert(*leaf, relay_data);
```
Comment (sw10pa) [inline polkadot/node/network/collator-protocol/src/collator_side/mod.rs:1241]: There may be a better place to get the assigned cores, but this is the most optimal solution I've found so far. I'm open to suggestions for improvement.

File: polkadot/node/network/collator-protocol/src/collator_side/mod.rs [hunk 2]
```diff
@@ -1218,7 +1236,9 @@ async fn handle_our_view_change<Context>(
 
 	for leaf in added {
 		let claim_queue = fetch_claim_queue(ctx.sender(), *leaf).await?;
-		state.per_relay_parent.insert(*leaf, PerRelayParent::new(para_id, claim_queue));
+		let relay_data = PerRelayParent::new(para_id, claim_queue);
+		state.num_assigned_cores = relay_data.assignments.len();
```
Comment (sw10pa) [inline polkadot/node/network/collator-protocol/src/collator_side/mod.rs:1240]: There may be a better place to get the assigned cores, but this is the most optimal solution I've found so far. I'm open to suggestions for improvement.

File: polkadot/node/network/collator-protocol/src/collator_side/mod.rs [hunk 3]
```diff
@@ -604,9 +608,23 @@ async fn declare<Context>(ctx: &mut Context, state: &mut State, peer: &PeerId) {
 #[overseer::contextbounds(CollatorProtocol, prefix = self::overseer)]
 async fn connect_to_validators<Context>(
 	ctx: &mut Context,
+	num_assigned_cores: usize,
 	validator_groups_buf: &ValidatorGroupsBuffer,
 ) {
-	let validator_ids = validator_groups_buf.validators_to_connect();
+	// If no cores are assigned to the para, we still need to send a ConnectToValidators request to
+	// the network bridge passing an empty list of validator ids. Otherwise, it will keep connecting
+	// to the last requested validators until a new request is issued.
```
Comment (alexggh) [inline polkadot/node/network/collator-protocol/src/collator_side/mod.rs:616]: >Otherwise, it will keep connecting
// to the last requested validators until a new request is issued

Where is that happening ?

File: polkadot/node/network/collator-protocol/src/collator_side/mod.rs (hunk 2 above)
Comment (alexggh) [reply polkadot/node/network/collator-protocol/src/collator_side/mod.rs:1240]: Looks like the right place to me.

**Review by alexggh — COMMENTED** [review]
Looks like the right fix to me, gj!

File: polkadot/node/network/collator-protocol/src/collator_side/mod.rs (hunk 3 above)
Comment (alexggh) [reply polkadot/node/network/collator-protocol/src/collator_side/mod.rs:616]: The comment just tells that substrate networking doesn't disconnect those validators, it does not mean it continuously retry to connect to them, at least that's my understanding, do you see substrate doing that continuously ?

Comment (sw10pa) [reply polkadot/node/network/collator-protocol/src/collator_side/mod.rs:616]: Yes, it was continuously trying to connect to them

Comment (ordian) [reply polkadot/node/network/collator-protocol/src/collator_side/mod.rs:616]: The way it works is that we add validators to the reserved set and that tries to keep connection constantly so @sw10pa is correct

Comment (alexggh) [reply polkadot/node/network/collator-protocol/src/collator_side/mod.rs:616]: Yes, that's correct.

File: polkadot/node/network/collator-protocol/src/collator_side/mod.rs (hunk 2 above)
Comment (alindima) [reply polkadot/node/network/collator-protocol/src/collator_side/mod.rs:1240]: It looks like we only care if we have an assignment or not (not their actual number). So `num_assigned_cores` can be a bool.
However, we don't take into account forks.

When updating the connection list, I believe we should instead look at all active leaves and see if there's any assignment for our paraid (on any one of the leaves).

Comment (sw10pa) [reply polkadot/node/network/collator-protocol/src/collator_side/mod.rs]: Agree, checked all active leaves.

File: polkadot/node/network/collator-protocol/src/collator_side/mod.rs [hunk 4]
```diff
@@ -599,14 +600,44 @@ async fn declare<Context>(ctx: &mut Context, state: &mut State, peer: &PeerId) {
 	}
 }
 
+/// Checks whether there are any core assignments for our para on any active relay chain leaves.
+fn has_assigned_cores(
```
Comment (alexggh) [inline polkadot/node/network/collator-protocol/src/collator_side/mod.rs:604]: Nice!

**Review by alexggh — APPROVED** [review]

**Review by alindima — APPROVED** [review]
LGTM! Good job

**Review by eskimor — COMMENTED** [review]
LGTM
