### PR TITLE
Clamp benchmark ranks to respect MaxRank

### LINKED ISSUE #7517: Benchmarks `promote_fast` and others should support configurable ranks
### Is there an existing issue?

- [x] I have searched the existing issues

### Experiencing problems? Have you tried our Stack Exchange first?

- [x] This is not a support question.

### Description of bug

When running the `promote_fast` benchmark in `pallet_core_fellowship`, I encountered an issue where the generated rank (`r`) exceeded the configured `MaxRank`. Specifically, even when `T::MaxRank::get() == 1`, the benchmark framework sometimes assigned `r = 2`, causing the extrinsic call to fail with an `InvalidRank` error.

**Steps to Reproduce**
- Configure the runtime with `T::MaxRank::get() == 1`.
- Run the benchmark for `promote_fast`.
- Add `log::info!("Benchmark promote_fast: r={} MaxRank={}", r, T::MaxRank::get());`
- Observe that `r` is sometimes set to `2`, leading to an `InvalidRank` error.

**Expected Behavior**
The benchmark framework should respect the constraint that r must be in the range `[1, T::MaxRank::get()]`, ensuring `r` never exceeds `MaxRank`.

**Actual Behavior**
The benchmark framework assigns `r = 2` even when `MaxRank == 1`.
This causes the `promote_fast` extrinsic to fail validation.

### Steps to reproduce

_No response_

### PR DESCRIPTION
**Pull request by Doordashcon**
resolves #7517 

#### 1. Compile-Time vs Runtime Rank Mismatch
- **`promote_fast` Benchmark** uses mock runtime's `MaxRank` during benchmark generation while allowing runtime overrides. Creating potential parameter mismatch between benchmark metadata(i.e. generated `r` values) and runtime configuration(i.e. `T::MaxRank`).

#### 2. Static Rank Assumptions
- **`bump_demote` Benchmark** initialized members at rank 2, making it incompatible with `MaxRank=1` configurations
- **`promote` Benchmark** contained hardcoded rank values (1 → 2) which fails for `MaxRank=1` 

#### Dynamic Rank Clamping
```rust
// promote_fast
// Get target rank for promotion.
let max_rank = T::MaxRank::get();
let target_rank = (r as u16).min(max_rank);

// promote
// Set `to_rank` dynamically based on `max_rank`.
let to_rank = (current_rank + 1).min(max_rank);

### CODE REVIEW

**Review by bkchr — COMMENTED** [review]
The general logic looks good, just some nit improvements to make this better :)

File: substrate/frame/core-fellowship/src/benchmarking.rs [hunk 1]
```diff
@@ -195,35 +200,48 @@ mod benchmarks {
...
 		Ok(())
 	}
 
 	/// Benchmark the `promote_fast` extrinsic to promote someone up to `r`.
 	#[benchmark]
 	fn promote_fast(r: Linear<1, { T::MaxRank::get() as u32 }>) -> Result<(), BenchmarkError> {
-		let r = r.try_into().expect("r is too large");
+		// Get target rank for promotion.
+		let max_rank = T::MaxRank::get();
+		let target_rank = r.min(max_rank).try_into().unwrap();
```
[the remark this answers is not in the document]
Comment (Doordashcon) [reply substrate/frame/core-fellowship/src/benchmarking.rs]:
```rust
pub struct ConvertU16ToU32<Inner>(PhantomData<Inner>);
```

for `BoundedVec`

File: substrate/frame/core-fellowship/src/lib.rs [hunk 2]
```diff
@@ -523,7 +533,7 @@ pub mod pallet {
 		/// This is useful for out-of-band promotions, hence it has its own `FastPromoteOrigin` to
 		/// be (possibly) more restrictive than `PromoteOrigin`. Note that the member must already
 		/// be inducted.
-		#[pallet::weight(T::WeightInfo::promote_fast(*to_rank as u32))]
+		#[pallet::weight(T::WeightInfo::promote_fast(*to_rank))]
```
Comment (Doordashcon) [inline substrate/frame/core-fellowship/src/lib.rs:536]: Would need to run benchmarks for this 🙏

Comment (bkchr) [reply substrate/frame/core-fellowship/src/lib.rs:536]: Why? Generally we have now these weight updates once a week, that should be fine to be done as part of them.

File: substrate/frame/core-fellowship/src/lib.rs [hunk 3]
```diff
@@ -163,6 +163,13 @@ impl<
 	}
 }
 
+pub struct ConvertU16ToU32<Inner>(PhantomData<Inner>);
```
Comment (bkchr) [inline substrate/frame/core-fellowship/src/lib.rs:166]: Fine for now. After the pr got merged, could you do a commit to the upstream crate that has the `Get` trait to introduce some sort of `GetInto` converter type:

```
impl<T: Get<I>, I: Into<R>, R> Get<R> GetInto<I> {
       fn get() -> R {
              T::get().into()
       }
}

**Review by bkchr — APPROVED** [review]

File: substrate/frame/core-fellowship/src/lib.rs (hunk 3 above)
Comment (Doordashcon) [reply substrate/frame/core-fellowship/src/lib.rs:166]: Underway https://github.com/paritytech/parity-common/pull/909

File: substrate/frame/core-fellowship/src/lib.rs [hunk 4]
```diff
@@ -238,15 +245,18 @@ pub mod pallet {
 		///
 		/// Increasing this value is supported, but decreasing it may lead to a broken state.
 		#[pallet::constant]
-		type MaxRank: Get<u32>;
+		type MaxRank: Get<u16>;
```
Comment (ggwpez) [inline substrate/frame/core-fellowship/src/lib.rs:248]: Breaking change?  
Should be `major` in the prdoc then.

File: prdoc/pr_7720.prdoc [hunk 5]
```diff
@@ -0,0 +1,18 @@
+# Schema: Polkadot SDK PRDoc Schema (prdoc) v1.0.0
+# See doc at https://raw.githubusercontent.com/paritytech/polkadot-sdk/master/prdoc/schema_user.json
+
+title: Clamp Core Fellowship Benchmarks to Runtime MaxRank Configuration
+
+doc:
+  - audience: Runtime Dev
+    description: |      
+      Enables reliable benchmarking for constrained configurations like `MaxRank=1` while
+      maintaining compatibility with larger rank ranges.
```
Comment (ggwpez) [inline prdoc/pr_7720.prdoc:10]: Must mention the breaking change and how downstream developers integrate it.

Comment (Doordashcon) [reply prdoc/pr_7720.prdoc:15]: Done

**Review by acatangiu — COMMENTED** [review]
I like the benchmark fix, I personally don’t like the u32->u16 type change because it adds more complexity with some custom converters types and is a breaking change for runtime builders, for no strong reason/benefit.

Not blocking the PR for this, but want to get your opinion on above.

**Comment by bkchr** [comment]
> Not blocking the PR for this, but want to get your opinion on above.

The core fellowship is only used by the collectives chain. The user base of this isn't that big and also given the required change I think that the change is reasonable.

**Review by ggwpez — APPROVED** [review]

File: substrate/frame/core-fellowship/src/lib.rs (hunk 4 above)
Comment (bkontur) [reply substrate/frame/core-fellowship/src/lib.rs:248]: @Doordashcon Just out of curiosity, what was the motivation for changing this u32 to u16? And why didn't we also change other types to use u16 instead of u32 respectively - e.g. `ParamsOf` / `PartialParamsOf`?

File: substrate/frame/core-fellowship/src/weights.rs [hunk 6]
```diff
@@ -79,7 +79,7 @@ pub trait WeightInfo {
 	fn set_active() -> Weight;
 	fn induct() -> Weight;
 	fn promote() -> Weight;
-	fn promote_fast(r: u32, ) -> Weight;
+	fn promote_fast(r: u16, ) -> Weight;
```
Comment (bkontur) [inline substrate/frame/core-fellowship/src/weights.rs:82]: @Doordashcon Changed this back to `u32` because `Linear` currently supports only `u32`. Using `u16` here caused a compilation issue when generating weights, more info and fix: https://github.com/paritytech/polkadot-sdk/pull/9516.
