### PR TITLE
remove retry from backers on failed candidate validation

### LINKED ISSUE #1585: Backers retry on failed candidate validation
Loosely connected to https://github.com/paritytech/polkadot-sdk/issues/1434 where the potential issue was first recognised.

Backers seem to retry failed validation (once per error type). In general it would be better to have backing stricter than approval voting / disputes. This is currently the case for timeouts but another aspect should be respecting transient errors and not doing any retries in in the backing stage. This reduces the chance of nondeterministic blocks getting backed and honest backers getting slashed.

Call path in question:
`polkadot-sdk/polkadot/node/core/backing/src/lib.rs` always delegates backing validation to `fn request_candidate_validation` which in turn send a message `CandidateValidationMessage::ValidateFromExhaustive`. This particular message triggers a `fn validate_candidate_exhaustive` which leads directly to `fn validate_candidate_with_retry`. Backing uses the validation implementation with a retry instead of the `fn validate_candidate`.

`fn validate_candidate_with_retry` allows the validation to be retried in cases of:
- completely invalid candidate
- ambiguous worker death
- internal error

Each case can be retried once. So it is possible that multiple retires will be attempted.

This can be somewhat easily amended by passing extra details in the message and changing the behaviour in candidate validation in case of backing validation. The new behaviour will simply refer to the non retry version of the func.

### PR DESCRIPTION
**Pull request by Jpserrat**
Hey guys, as discussed I've changed the name to a more general one `PvfExecKind`, is this good or too general?
Creating this as a draft, I still have to fix the tests.

Closes #1585

Kusama address: FkB6QEo8VnV3oifugNj5NeVG3Mvq1zFbrUu4P5YwRoe5mQN

### CODE REVIEW

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable 2/3
**Logs**: https://gitlab.parity.io/parity/mirrors/polkadot-sdk/-/jobs/4232788

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable 1/3
**Logs**: https://gitlab.parity.io/parity/mirrors/polkadot-sdk/-/jobs/4232787

**Comment by s0me0ne-unkn0wn** [comment]
bot fmt

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable 3/3
**Logs**: https://gitlab.parity.io/parity/mirrors/polkadot-sdk/-/jobs/4234425

**Comment by s0me0ne-unkn0wn** [comment]
I'd go for renaming `PvfPrepTimeoutKind` as well so they say in sync. Otherwise, looks good! :+1:

File: polkadot/node/core/candidate-validation/src/lib.rs [hunk 1]
```diff
@@ -498,7 +498,7 @@ async fn validate_from_chain_state<Sender>(
 	candidate_receipt: CandidateReceipt,
 	pov: Arc<PoV>,
 	executor_params: ExecutorParams,
-	exec_timeout_kind: PvfExecTimeoutKind,
+	exec_timeout_kind: PvfExecKind,
```
Comment (mrcnski) [inline polkadot/node/core/candidate-validation/src/lib.rs:501]: Can you please fix the param names, too? And there's a few more in this file.

File: polkadot/node/subsystem-types/src/messages.rs [hunk 2]
```diff
@@ -147,8 +147,8 @@ pub enum CandidateValidationMessage {
 		CandidateReceipt,
 		Arc<PoV>,
 		ExecutorParams,
-		/// Execution timeout
-		PvfExecTimeoutKind,
+		/// Execution timeout and retry
```
Comment (mrcnski) [inline polkadot/node/subsystem-types/src/messages.rs:150]: Maybe this would be more clear:

```suggestion
		/// Execution kind, used for timeouts and retries
```

And below also.

File: polkadot/node/core/candidate-validation/src/lib.rs [hunk 3]
```diff
@@ -613,15 +613,30 @@ async fn validate_candidate_exhaustive(
...
+			);
+
+			validation_backend.validate_candidate(pvf, exec_timeout, params.encode()).await
+		},
+		PvfExecKind::Approval =>
+			validation_backend
+				.validate_candidate_with_retry(
+					raw_validation_code.to_vec(),
+					pvf_exec_timeout(&executor_params, exec_timeout_kind),
+					exec_timeout_kind,
```
Comment (mrcnski) [inline polkadot/node/core/candidate-validation/src/lib.rs:634]: This parameter can be removed now, right? And we can probably document `validate_candidate_with_retry` to say that it should only be called for the approval subsystem. :)

**Review by mrcnski — CHANGES_REQUESTED** [review]
I know the PR's still in progress, but left some comments anyway!

**Comment by mrcnski** [comment]
Remember to add your kusama address if you want a tip. Is a small one appropriate for this PR?

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: cargo-clippy
**Logs**: https://gitlab.parity.io/parity/mirrors/polkadot-sdk/-/jobs/4243747

File: polkadot/node/core/candidate-validation/src/tests.rs [hunk 4]
```diff
@@ -480,95 +480,22 @@ fn candidate_validation_bad_return_is_invalid() {
...
-		validation_code,
-		candidate_receipt,
-		Arc::new(pov),
-		ExecutorParams::default(),
-		PvfExecTimeoutKind::Backing,
-		&Default::default(),
+        validation_data,
+        validation_code,
+        candidate_receipt,
+        Arc::new(pov),
```
Comment (mrcnski) [inline polkadot/node/core/candidate-validation/src/tests.rs:489]: I think some formatting is getting messed up (tabs -> spaces). Make sure you are running `cargo +nightly fmt` with a recent nightly, you can set it as a pre-commit git hook. :)

File: polkadot/node/core/candidate-validation/src/tests.rs [hunk 5]
```diff
@@ -480,95 +480,22 @@ fn candidate_validation_bad_return_is_invalid() {
...
+        &Default::default(),
 	))
 	.unwrap();
 
 	assert_matches!(v, ValidationResult::Invalid(InvalidCandidate::Timeout));
 }
 
-// Test that we vote valid if we get `AmbiguousWorkerDeath`, retry, and then succeed.
-#[test]
-fn candidate_validation_one_ambiguous_error_is_valid() {
```
Comment (mrcnski) [inline polkadot/node/core/candidate-validation/src/tests.rs:501]: Maybe I missed it, but why remove this test? I think we just need to change it from backing -> approval for it to work.

File: polkadot/node/core/candidate-validation/src/tests.rs [hunk 6]
```diff
@@ -617,7 +543,7 @@ fn candidate_validation_multiple_ambiguous_errors_is_invalid() {
 
 // Test that we retry on internal errors.
 #[test]
-fn candidate_validation_retry_internal_errors() {
+fn candidate_validation_dont_retry_internal_errors() {
```
Comment (mrcnski) [inline polkadot/node/core/candidate-validation/src/tests.rs:546]: Can you please refactor this into two test cases, backing and approval, making sure that one retries and one doesn't.

File: polkadot/node/core/candidate-validation/src/tests.rs [hunk 7]
```diff
@@ -645,28 +571,28 @@ fn candidate_validation_retry_internal_errors() {
...
 	));
 
-	assert_matches!(v, Err(ValidationFailed(s)) if s.contains("bar"));
+	assert_matches!(v, Err(ValidationFailed(s)) if s.contains("foo"));
 }
 
 // Test that we retry on panic errors.
 #[test]
-fn candidate_validation_retry_panic_errors() {
+fn candidate_validation_dont_retry_panic_errors() {
```
Comment (mrcnski) [inline polkadot/node/core/candidate-validation/src/tests.rs:595]: Same here. Maybe you can refactor these tests into a generic helper, to avoid duplicating code.

**Review by mrcnski — CHANGES_REQUESTED** [review]
Looking good, I left some suggestions for test cases. 👍 Is it still a draft?

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable 3/3
**Logs**: https://gitlab.parity.io/parity/mirrors/polkadot-sdk/-/jobs/4245711

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable 2/3
**Logs**: https://gitlab.parity.io/parity/mirrors/polkadot-sdk/-/jobs/4245710

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable 1/3
**Logs**: https://gitlab.parity.io/parity/mirrors/polkadot-sdk/-/jobs/4245709

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable 1/3
**Logs**: https://gitlab.parity.io/parity/mirrors/polkadot-sdk/-/jobs/4264488

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable 3/3
**Logs**: https://gitlab.parity.io/parity/mirrors/polkadot-sdk/-/jobs/4264490

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable 2/3
**Logs**: https://gitlab.parity.io/parity/mirrors/polkadot-sdk/-/jobs/4278779

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable 1/3
**Logs**: https://gitlab.parity.io/parity/mirrors/polkadot-sdk/-/jobs/4278778

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable 3/3
**Logs**: https://gitlab.parity.io/parity/mirrors/polkadot-sdk/-/jobs/4278780

**Comment by mrcnski** [comment]
Can you please update our documentation as well? We have retries documented here:

https://github.com/paritytech/polkadot-sdk/blob/jpserrat-pvf-fork-instead-threads/polkadot/roadmap/implementers-guide/src/node/utility/pvf-host-and-workers.md?plain=1#L16

To test your understanding, give a go at explaining, at a high-level, why we don't retry on backing. Let me know if you have any questions. 🙂

**Review by mrcnski — CHANGES_REQUESTED** [review]
Awesome! I think `candidate_validation_one_ambiguous_error_is_valid` and `candidate_validation_multiple_ambiguous_errors_is_invalid` can also be refactored to use the new test helper. Apart from that, just need to update the doc!

**Comment by Jpserrat** [comment]
Working on that now!

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: cargo-clippy
**Logs**: https://gitlab.parity.io/parity/mirrors/polkadot-sdk/-/jobs/4334283

**Review by mrcnski — APPROVED** [review]
Awesome!

**Comment by rzadp** [comment]
> /tip medium

The referendum has been created:
https://kusama.subscan.io/referenda_v2/307

I'll be looking into why the bot didn't respond back fully, looks like it failed to update the referendum on Polkassembly.

File: polkadot/node/core/candidate-validation/src/tests.rs [hunk 8]
```diff
@@ -576,97 +591,105 @@ fn candidate_validation_multiple_ambiguous_errors_is_invalid() {
...
+		MockValidateCandidateBackend::with_hardcoded_result_list(vec![Err(
+			ValidationError::InvalidCandidate(WasmInvalidCandidate::AmbiguousWorkerDeath),
+		)]),
 		validation_data,
 		validation_code,
 		candidate_receipt,
 		Arc::new(pov),
 		ExecutorParams::default(),
-		PvfExecTimeoutKind::Backing,
+		PvfExecKind::Backing,
```
[the remark this answers is not in the document]
Comment (Jpserrat) [reply polkadot/node/core/candidate-validation/src/tests.rs:612]: Fixed, now using approval and testing multiple ambiguous errors

[the remark this answers is not in the document]
Comment (mrcnski) [reply polkadot/node/core/candidate-validation/src/tests.rs:612]: @Jpserrat I don't see the fix. Did you forget to push a commit?

[the remark this answers is not in the document]
Comment (Jpserrat) [reply polkadot/node/core/candidate-validation/src/tests.rs]: I did haha.

**Review by mrcnski — APPROVED** [review]
Looks good to me. Just need to fix the merge conflict.

**Review by s0me0ne-unkn0wn — APPROVED** [review]
Good to go! I'd still rename `Lenient` to `Prepare`, that's one comment that hasn't been addressed yet.

**Comment by Jpserrat** [comment]
Sorry, I forgot that one.

File: polkadot/node/core/candidate-validation/src/lib.rs [hunk 9]
```diff
@@ -613,15 +613,30 @@ async fn validate_candidate_exhaustive(
...
-			raw_validation_code.to_vec(),
-			pvf_exec_timeout(&executor_params, exec_timeout_kind),
-			exec_timeout_kind,
-			params,
-			executor_params,
-		)
-		.await;
+	let result = match exec_kind {
+		PvfExecKind::Backing => {
+			let prep_timeout = pvf_prep_timeout(&executor_params, PvfPrepKind::Lenient);
```
[the remark this answers is not in the document]
Comment (Jpserrat) [reply polkadot/node/core/candidate-validation/src/lib.rs:615]: Just to double-check, do you mean `PvfPrepKind::Precheck`, right?

[the remark this answers is not in the document]
Comment (mrcnski) [reply polkadot/node/core/candidate-validation/src/lib.rs:615]: No, regular preparation is more "lenient" than prechecking, which is more strict to filter out problematic PVFs. But calling it lenient doesn't match how we refer to regular preparation in the rest of the codebase. Thanks for double-checking. 👍

File: polkadot/node/core/candidate-validation/src/lib.rs [hunk 10]
```diff
@@ -612,7 +612,7 @@ async fn validate_candidate_exhaustive(
 
 	let result = match exec_kind {
 		PvfExecKind::Backing => {
-			let prep_timeout = pvf_prep_timeout(&executor_params, PvfPrepKind::Lenient);
+			let prep_timeout = pvf_prep_timeout(&executor_params, PvfPrepKind::Precheck);
```
Comment (mrcnski) [inline polkadot/node/core/candidate-validation/src/lib.rs:615]:
```suggestion
			let prep_timeout = pvf_prep_timeout(&executor_params, PvfPrepKind::Prepare);
```

**Comment by mrcnski** [comment]
@Jpserrat Was that tip sent successfully?

File: polkadot/primitives/src/v6/mod.rs [hunk 11]
```diff
@@ -1783,24 +1783,27 @@ impl<T: Encode> WellKnownKey<T> {
...
-	Lenient,
+	Prepare,
 }
 
-/// Type discriminator for PVF execution timeouts
+/// Type discriminator for PVF execution timeouts and retries
 #[derive(Encode, Decode, TypeInfo, Clone, Copy, Debug, PartialEq, Eq, Serialize, Deserialize)]
-pub enum PvfExecTimeoutKind {
+pub enum PvfExecKind {
 	/// The amount of time to spend on execution during backing.
```
Comment (mrcnski) [inline polkadot/primitives/src/v6/mod.rs:1800]: I think this comment is old.

File: polkadot/primitives/src/v6/mod.rs [hunk 12]
```diff
@@ -1783,24 +1783,27 @@ impl<T: Encode> WellKnownKey<T> {
...
+	/// Retry is disabled to reduce the chance of nondeterministic blocks getting backed and honest
+	/// backers getting slashed.
 	Backing,
 
 	/// The amount of time to spend on execution during approval or disputes.
+	/// With retry enabled.
 	///
 	/// This should be much longer than the backing execution timeout to ensure that in the
 	/// absence of extremely large disparities between hardware, blocks that pass backing are
```
Comment (mrcnski) [inline polkadot/primitives/src/v6/mod.rs:1809]: Same here.

File: polkadot/primitives/src/v6/mod.rs [hunk 13]
```diff
@@ -1783,24 +1783,27 @@ impl<T: Encode> WellKnownKey<T> {
...
 #[derive(Encode, Decode, TypeInfo, Clone, Copy, Debug, PartialEq, Eq, Serialize, Deserialize)]
-pub enum PvfPrepTimeoutKind {
+pub enum PvfPrepKind {
 	/// For prechecking requests, the time period after which the preparation worker is considered
 	/// unresponsive and will be killed.
 	Precheck,
 
 	/// For execution and heads-up requests, the time period after which the preparation worker is
 	/// considered unresponsive and will be killed. More lenient than the timeout for prechecking
 	/// to prevent honest validators from timing out on valid PVFs.
```
Comment (mrcnski) [inline polkadot/primitives/src/v6/mod.rs:1793]: Old comments.

File: polkadot/primitives/src/v6/mod.rs [hunk 14]
```diff
@@ -1783,24 +1783,27 @@ impl<T: Encode> WellKnownKey<T> {
 
 /// Type discriminator for PVF preparation timeouts
 #[derive(Encode, Decode, TypeInfo, Clone, Copy, Debug, PartialEq, Eq, Serialize, Deserialize)]
-pub enum PvfPrepTimeoutKind {
+pub enum PvfPrepKind {
```
Comment (mrcnski) [inline polkadot/primitives/src/v6/mod.rs:1786]: Same here.

Comment (Jpserrat) [reply polkadot/primitives/src/v6/mod.rs]: fixed

File: polkadot/primitives/src/v6/mod.rs (hunk 13 above)
Comment (Jpserrat) [reply polkadot/primitives/src/v6/mod.rs:1793]: This one, I don't get what has to be changed, we didn't change the behaviour of the PvfPrepKind.

File: polkadot/primitives/src/v6/mod.rs (hunk 11 above)
Comment (mrcnski) [reply polkadot/primitives/src/v6/mod.rs:1800]: Good question. :) It's not specific to timeouts anymore, so instead of "the amount of time", maybe it could just say "An execution request from Backing." or something like that.

File: polkadot/primitives/src/v6/mod.rs (hunk 13 above)
Comment (mrcnski) [reply polkadot/primitives/src/v6/mod.rs:1793]: But we did change the name. ;) You're right that we only use this type for timeouts at the moment, but the name is more general than that. Is it reasonable to remove all the docs here about timeouts, and move them to `fn pvf_prep_timeout`?

File: polkadot/primitives/src/v6/mod.rs (hunk 14 above)
Comment (mrcnski) [reply polkadot/primitives/src/v6/mod.rs]: Thanks!

File: polkadot/primitives/src/v6/mod.rs (hunk 11 above)
Comment (mrcnski) [reply polkadot/primitives/src/v6/mod.rs:1800]: And can the docs be moved to `fn pvf_exec_timeout`?

File: polkadot/primitives/src/v6/mod.rs (hunk 13 above)
Comment (Jpserrat) [reply polkadot/primitives/src/v6/mod.rs]: Oh, I see it does. I thought that centralizing everything in the enum would be a good idea, but it makes sense to leave it to the function. I've changed both.

**Comment by Jpserrat** [comment]
> @Jpserrat Was that tip sent successfully?

@mrcnski I haven't received it yet.

**Comment by mrcnski** [comment]
@Jpserrat Looks like voting is taking more time than usual, I'll keep an eye on it. 👀

**Comment by Overkillus** [comment]
Late to the party but  the changes look fine so good job @Jpserrat :+1: Happy to see this issue closed!

**Comment by mrcnski** [comment]
@Jpserrat The tip should have gone through now. 💪
