### PR TITLE
relax `XcmFeeToAccount` trait bound on `AccountId`

### LINKED ISSUE #4960: Make `XcmFeeToAccount` less restrictive
### Is there an existing issue?

- [X] I have searched the existing issues

### Experiencing problems? Have you tried our Stack Exchange first?

- [X] This is not a support question.

### Motivation

Configuring `FeeManager` enforces the boundary `Into<[u8; 32]>` for the `AccountId` type.

Here is how it works currently: 

Configuration:
```rust
    type FeeManager = XcmFeeManagerFromComponents<
        IsChildSystemParachain<primitives::Id>,
        XcmFeeToAccount<Self::AssetTransactor, AccountId, TreasuryAccount>,
    >;
```

`XcmToFeeAccount` struct:
```rust
/// A `HandleFee` implementation that simply deposits the fees into a specific on-chain
/// `ReceiverAccount`.
///
/// It reuses the `AssetTransactor` configured on the XCM executor to deposit fee assets. If
/// the `AssetTransactor` returns an error while calling `deposit_asset`, then a warning will be
/// logged and the fee burned.
pub struct XcmFeeToAccount<AssetTransactor, AccountId, ReceiverAccount>(
	PhantomData<(AssetTransactor, AccountId, ReceiverAccount)>,
);

impl<
		AssetTransactor: TransactAsset,
		AccountId: Clone + Into<[u8; 32]>,
		ReceiverAccount: Get<AccountId>,
	> HandleFee for XcmFeeToAccount<AssetTransactor, AccountId, ReceiverAccount>
{
	fn handle_fee(fee: Assets, context: Option<&XcmContext>, _reason: FeeReason) -> Assets {
		deposit_or_burn_fee::<AssetTransactor, _>(fee, context, ReceiverAccount::get());

		Assets::new()
	}
}
```

`deposit_or_burn_fee()` function:
```rust
/// Try to deposit the given fee in the specified account.
/// Burns the fee in case of a failure.
pub fn deposit_or_burn_fee<AssetTransactor: TransactAsset, AccountId: Clone + Into<[u8; 32]>>(
	fee: Assets,
	context: Option<&XcmContext>,
	receiver: AccountId,
) {
	let dest = AccountId32 { network: None, id: receiver.into() }.into();
	for asset in fee.into_inner() {
		if let Err(e) = AssetTransactor::deposit_asset(&asset, &dest, context) {
			log::trace!(
				target: "xcm::fees",
				"`AssetTransactor::deposit_asset` returned error: {:?}. Burning fee: {:?}. \
				They might be burned.",
				e, asset,
			);
		}
	}
}
```

---

In order to use **another** `AccountId` type (for example, 20 byte addresses for compatibility with Ethereum or Bitcoin), one has to duplicate the code as the following (roughly changing every `32` to `20`):
```rust
/// A `HandleFee` implementation that simply deposits the fees into a specific on-chain
/// `ReceiverAccount`.
///
/// It reuses the `AssetTransactor` configured on the XCM executor to deposit fee assets. If
/// the `AssetTransactor` returns an error while calling `deposit_asset`, then a warning will be
/// logged and the fee burned.
pub struct XcmFeeToAccount<AssetTransactor, AccountId, ReceiverAccount>(
    PhantomData<(AssetTransactor, AccountId, ReceiverAccount)>,
);
impl<
        AssetTransactor: TransactAsset,
        AccountId: Clone + Into<[u8; 20]>,
        ReceiverAccount: Get<AccountId>,
    > HandleFee for XcmFeeToAccount<AssetTransactor, AccountId, ReceiverAccount>
{
    fn handle_fee(fee: XcmAssets, context: Option<&XcmContext>, _reason: FeeReason) -> XcmAssets {
        deposit_or_burn_fee::<AssetTransactor, _>(fee, context, ReceiverAccount::get());

        XcmAssets::new()
    }
}

pub fn deposit_or_burn_fee<AssetTransactor: TransactAsset, AccountId: Clone + Into<[u8; 20]>>(
    fee: XcmAssets,
    context: Option<&XcmContext>,
    receiver: AccountId,
) {
    let dest = AccountKey20 { network: None, key: receiver.into() }.into();
    for asset in fee.into_inner() {
        if let Err(e) = AssetTransactor::deposit_asset(&asset, &dest, context) {
            log::trace!(
                target: "xcm::fees",
                "`AssetTransactor::deposit_asset` returned error: {:?}. Burning fee: {:?}. \
                They might be burned.",
                e, asset,
            );
        }
    }
}
```

---

This results in code duplication, which can be avoided simply by relaxing the trait enforced by `XcmFeeToAccount`. 

### Request

Relax the trait enforced by `XcmFeeToAccount`. 

### Solution

Submitted a #4959

### Are you willing to help with this request?

Yes!

### PR DESCRIPTION
**Pull request by ozgunozerk**
Fixes #4960 

Configuring `FeeManager` enforces the boundary `Into<[u8; 32]>` for the `AccountId` type.

Here is how it works currently: 

Configuration:
```rust
    type FeeManager = XcmFeeManagerFromComponents<
        IsChildSystemParachain<primitives::Id>,
        XcmFeeToAccount<Self::AssetTransactor, AccountId, TreasuryAccount>,
    >;
```

`XcmToFeeAccount` struct:
```rust
/// A `HandleFee` implementation that simply deposits the fees into a specific on-chain
/// `ReceiverAccount`.
///
/// It reuses the `AssetTransactor` configured on the XCM executor to deposit fee assets. If
/// the `AssetTransactor` returns an error while calling `deposit_asset`, then a warning will be
/// logged and the fee burned.
pub struct XcmFeeToAccount<AssetTransactor, AccountId, ReceiverAccount>(
	PhantomData<(AssetTransactor, AccountId, ReceiverAccount)>,
);

impl<
		AssetTransactor: TransactAsset,
		AccountId: Clone + Into<[u8; 32]>,
		ReceiverAccount: Get<AccountId>,
	> HandleFee for XcmFeeToAccount<AssetTransactor, AccountId, ReceiverAccount>
{
	fn handle_fee(fee: Assets, context: Option<&XcmContext>, _reason: FeeReason) -> Assets {
		deposit_or_burn_fee::<AssetTransactor, _>(fee, context, ReceiverAccount::get());

		Assets::new()
	}
}
```

`deposit_or_burn_fee()` function:
```rust
/// Try to deposit the given fee in the specified account.
/// Burns the fee in case of a failure.
pub fn deposit_or_burn_fee<AssetTransactor: TransactAsset, AccountId: Clone + Into<[u8; 32]>>(
	fee: Assets,
	context: Option<&XcmContext>,
	receiver: AccountId,
) {
	let dest = AccountId32 { network: None, id: receiver.into() }.into();
	for asset in fee.into_inner() {
		if let Err(e) = AssetTransactor::deposit_asset(&asset, &dest, context) {
			log::trace!(
				target: "xcm::fees",
				"`AssetTransactor::deposit_asset` returned error: {:?}. Burning fee: {:?}. \
				They might be burned.",
				e, asset,
			);
		}
	}
}
```

---

In order to use **another** `AccountId` type (for example, 20 byte addresses for compatibility with Ethereum or Bitcoin), one has to duplicate the code as the following (roughly changing every `32` to `20`):
```rust
/// A `HandleFee` implementation that simply deposits the fees into a specific on-chain
/// `ReceiverAccount`.
///
/// It reuses the `AssetTransactor` configured on the XCM executor to deposit fee assets. If
/// the `AssetTransactor` returns an error while calling `deposit_asset`, then a warning will be
/// logged and the fee burned.
pub struct XcmFeeToAccount<AssetTransactor, AccountId, ReceiverAccount>(
    PhantomData<(AssetTransactor, AccountId, ReceiverAccount)>,
);
impl<
        AssetTransactor: TransactAsset,
        AccountId: Clone + Into<[u8; 20]>,
        ReceiverAccount: Get<AccountId>,
    > HandleFee for XcmFeeToAccount<AssetTransactor, AccountId, ReceiverAccount>
{
    fn handle_fee(fee: XcmAssets, context: Option<&XcmContext>, _reason: FeeReason) -> XcmAssets {
        deposit_or_burn_fee::<AssetTransactor, _>(fee, context, ReceiverAccount::get());

        XcmAssets::new()
    }
}

pub fn deposit_or_burn_fee<AssetTransactor: TransactAsset, AccountId: Clone + Into<[u8; 20]>>(
    fee: XcmAssets,
    context: Option<&XcmContext>,
    receiver: AccountId,
) {
    let dest = AccountKey20 { network: None, key: receiver.into() }.into();
    for asset in fee.into_inner() {
        if let Err(e) = AssetTransactor::deposit_asset(&asset, &dest, context) {
            log::trace!(
                target: "xcm::fees",
                "`AssetTransactor::deposit_asset` returned error: {:?}. Burning fee: {:?}. \
                They might be burned.",
                e, asset,
            );
        }
    }
}
```

---

This results in code duplication, which can be avoided simply by relaxing the trait enforced by `XcmFeeToAccount`. 

In this PR, I propose to introduce a new trait called `IntoLocation` to be able to express both `Into<[u8; 32]>` and `Into<[u8; 20]>` should be accepted (and every other `AccountId` type as long as they implement this trait). 

Currently, `deposit_or_burn_fee()` function converts the `receiver: AccountId` to a location. I think converting an account to `Location` should not be the responsibility of `deposit_or_burn_fee()` function. 

This trait also decouples the conversion of `AccountId` to `Location`, from `deposit_or_burn_fee()` function. And exposes `IntoLocation` trait. Thus, allowing everyone to come up with their `AccountId` type and make it compatible for configuring `FeeManager`.

---

Note 1: if there is a better file/location to put `IntoLocation`, I'm all ears

Note 2: making `deposit_or_burn_fee` or `XcmToFeeAccount` generic was not possible from what I understood, due to Rust currently do not support a way to express the generic should implement either `trait A` or `trait B` (since the compiler cannot guarantee they won't overlap). In this case, they are `Into<[u8; 32]>` and `Into<[u8; 20]>`.
See [this](https://github.com/rust-lang/rust/issues/20400) and [this](https://github.com/rust-lang/rfcs/pull/1672#issuecomment-262152934). 

Note 3: I should also submit a PR to `frontier` that implements `IntoLocation` for `AccountId20` if this PR gets accepted.

### Summary 
this new trait:
- decouples the conversion of `AccountId` to `Location`, from `deposit_or_burn_fee()` function
- makes `XcmFeeToAccount` accept every possible `AccountId` type as long as they they implement `IntoLocation`
- backwards compatible
- keeps the API simple and clean while making it less restrictive

@franciscoaguirre and @gupnik are already aware of the issue, so tagging them here for visibility.

### CODE REVIEW

File: polkadot/xcm/xcm-builder/src/fee_handling.rs [hunk 1]
```diff
@@ -100,7 +101,7 @@ pub struct XcmFeeToAccount<AssetTransactor, AccountId, ReceiverAccount>(
 
 impl<
 		AssetTransactor: TransactAsset,
-		AccountId: Clone + Into<[u8; 32]>,
+		AccountId: Clone + IntoLocation,
```
Comment (bkchr) [inline polkadot/xcm/xcm-builder/src/fee_handling.rs:104]:
```suggestion
		DestLocation: Get<Location>,
```

Looks better to me instead of requiring a new trait.

**Review by bkchr — APPROVED** [review]

File: polkadot/xcm/xcm-builder/src/fee_handling.rs (hunk 1 above)
Comment (ozgunozerk) [reply polkadot/xcm/xcm-builder/src/fee_handling.rs:104]: Makes sense, will ipdate the code soon!

Comment (ozgunozerk) [reply polkadot/xcm/xcm-builder/src/fee_handling.rs:104]: Tried to update the code accordingly but encountered the following problem:
`get()` does not take `self` as a parameter in any form. And we need the address of the given account in order to convert it to `xcm::v4::Junction::AccountId32 { network: None, id: ??? }`. So, I think with the API for `Get`, it is impossible for this case to convert an `AccountId` to `Location` with `Get`.

However, I looked at the code of `XcmFeeToAccount` and `deposit_or_burn_fee`, and `AccountId` is not used anywhere for the business logic. It is just there as an intermediate step to convert the provided `ReceiverAccount` into `Location`. 

So, we can just change this:
```rust
		AccountId: Clone + IntoLocation,
		ReceiverAccount: Get<AccountId>,
```

to this:
```rust
		ReceiverAccount: Get<Location>,
```

and there won't be any intermediate `AccountId`. 

This will be a breaking change though... Hence, `IntoLocation` still seems like the way to go to me eyes in terms of backwards compatibility.

Please let me know if I missed anything 👍

Comment (bkchr) [reply polkadot/xcm/xcm-builder/src/fee_handling.rs:104]: > and there won't be any intermediate AccountId.

Yeah that sounds more reasonable.

> This will be a breaking change though... Hence, IntoLocation still seems like the way to go to me eyes in terms of backwards compatibility.

`IntoLocation` is also a breaking change. We will maybe be happy that no code breaks because everybody is using `AccountId32`, but this not really given.

We could also just introduce a new type and let this type here with the old interface and set it as deprecated.

Comment (ozgunozerk) [reply polkadot/xcm/xcm-builder/src/fee_handling.rs:104]: Yes, the cleanest way will be deprecating that. Will update the code accordingly for the new type

Comment (ozgunozerk) [reply polkadot/xcm/xcm-builder/src/fee_handling.rs]: Done! I didn't spend much time on the namings, and I'm open to suggestions.

File: polkadot/xcm/xcm-builder/src/fee_handling.rs [hunk 2]
```diff
@@ -110,3 +110,55 @@ impl<
...
+	fn handle_fee(fee: Assets, context: Option<&XcmContext>, _reason: FeeReason) -> Assets {
+		deposit_or_burn_xcm_fee::<AssetTransactor>(fee, context, ReceiverAccount::get());
+
+		Assets::new()
+	}
+}
+
+/// Try to deposit the given fee in the specified account.
+/// Burns the fee in case of a failure.
+pub fn deposit_or_burn_xcm_fee<AssetTransactor: TransactAsset>(
```
[the remark this answers is not in the document]
Comment (ozgunozerk) [reply polkadot/xcm/xcm-builder/src/fee_handling.rs:149]: I just copy pasted the old one. Didn't change the visibility settings, assuming there was a reason behind them. I can make both of them (the new and the old one) private, no worries

File: polkadot/xcm/xcm-builder/src/fee_handling.rs [hunk 3]
```diff
@@ -110,3 +110,55 @@ impl<
 		Assets::new()
```
[the remark this answers is not in the document]
Comment (ozgunozerk) [reply polkadot/xcm/xcm-builder/src/fee_handling.rs:92]: First time doing deprecation in `polkadot-sdk`. I put `???` for the time, feel free to chip in

[the remark this answers is not in the document]
Comment (franciscoaguirre) [reply polkadot/xcm/xcm-builder/src/fee_handling.rs:92]: The [deprecation checklist](https://github.com/paritytech/polkadot-sdk/blob/master/docs/contributor/DEPRECATION_CHECKLIST.md) suggests 6 months.
Also, we should create a deprecation issue to not forget about removing this.

**Review by franciscoaguirre — APPROVED** [review]

File: polkadot/xcm/xcm-builder/src/fee_handling.rs (hunk 3 above)
[the remark this answers is not in the document]
Comment (ozgunozerk) [reply polkadot/xcm/xcm-builder/src/fee_handling.rs:94]: Done!

**Comment by franciscoaguirre** [comment]
You need to put `#[allow(deprecated)]` in `xcm-builder/SRC/fee_handling.rs` to get the CI to pass

**Comment by ozgunozerk** [comment]
Hi @franciscoaguirre, what are the next steps for this PR?

**Review by franciscoaguirre — APPROVED** [review]

**Comment by franciscoaguirre** [comment]
Just some clippy errors but the PR is fine

File: polkadot/xcm/xcm-builder/src/fee_handling.rs [hunk 4]
```diff
@@ -68,45 +68,82 @@ impl<WaivedLocations: Contains<Location>, FeeHandler: HandleFee> FeeManager
...
+	context: Option<&XcmContext>,
+	dest: Location,
+) {
+	for asset in fee.into_inner() {
+		if let Err(e) = AssetTransactor::deposit_asset(&asset, &dest, context) {
+			log::trace!(
+				target: "xcm::fees",
+				"`AssetTransactor::deposit_asset` returned error: {:?}. Burning fee: {:?}. \
+				They might be burned.",
+				e, asset,
```
Comment (bkontur) [inline polkadot/xcm/xcm-builder/src/fee_handling.rs:145]:
```suggestion
				"`AssetTransactor::deposit_asset` returned error: {e:?}. Burning fee: {asset:?}. \
				They might be burned.",
```

**Review by bkontur — APPROVED** [review]

File: cumulus/parachains/runtimes/bridge-hubs/bridge-hub-rococo/src/xcm_config.rs [hunk 5]
```diff
@@ -354,30 +354,33 @@ impl<
...
-							source_para_account.clone(),
+							AccountId32 { network: None, id: source_para_account.clone().into() }
+								.into(),
 						);
 					},
 				}
 			}
 
-			return Assets::new()
+			return Assets::new();
```
Comment (acatangiu) [inline cumulus/parachains/runtimes/bridge-hubs/bridge-hub-rococo/src/xcm_config.rs:383]:
```suggestion
			return Assets::new()
```

File: cumulus/parachains/runtimes/bridge-hubs/bridge-hub-rococo/src/xcm_config.rs [hunk 6]
```diff
@@ -393,7 +396,7 @@ impl<WaivedLocations: Contains<Location>, FeeHandler: HandleFee> FeeManager
 	fn is_waived(origin: Option<&Location>, fee_reason: FeeReason) -> bool {
 		let Some(loc) = origin else { return false };
 		if let Export { network, destination: Here } = fee_reason {
-			return !(network == EthereumNetwork::get())
+			return !(network == EthereumNetwork::get());
```
Comment (acatangiu) [inline cumulus/parachains/runtimes/bridge-hubs/bridge-hub-rococo/src/xcm_config.rs:399]:
```suggestion
			return !(network == EthereumNetwork::get())
```

File: polkadot/xcm/pallet-xcm/src/mock.rs [hunk 7]
```diff
@@ -222,10 +222,10 @@ impl SendXcm for TestPaidForPara3000SendXcm {
 	) -> SendResult<(Location, Xcm<()>)> {
 		if let Some(dest) = dest.as_ref() {
 			if !dest.eq(&Para3000Location::get()) {
-				return Err(SendError::NotApplicable)
+				return Err(SendError::NotApplicable);
```
Comment (acatangiu) [inline polkadot/xcm/pallet-xcm/src/mock.rs:225]:
```suggestion
				return Err(SendError::NotApplicable)
```

File: polkadot/xcm/pallet-xcm/src/mock.rs [hunk 8]
```diff
@@ -222,10 +222,10 @@ impl SendXcm for TestPaidForPara3000SendXcm {
...
 			}
 		} else {
-			return Err(SendError::NotApplicable)
+			return Err(SendError::NotApplicable);
```
Comment (acatangiu) [inline polkadot/xcm/pallet-xcm/src/mock.rs:228]:
```suggestion
			return Err(SendError::NotApplicable)
```

**Review by acatangiu — APPROVED** [review]

**Comment by acatangiu** [comment]
bot fmt

**Comment by ozgunozerk** [comment]
I'm unsure whether a PRDoc is required for this one (saw some merged PRs without a PRDoc), but seeing the CI failed, I added one.

File: prdoc/pr_4959.prdoc [hunk 9]
```diff
@@ -0,0 +1,14 @@
...
+
+doc:
+  - audience: Runtime Dev
+    description: |
+      This PR relaxes the trait bound on AccountId for the XcmFeeToAccount struct by introducing a new struct called `SendXcmFeeToAccount`.
+      The old one (`XcmFeeToAccount`) will be deprecated at January 2025.
+
+crates:
+  - name: staging-xcm-builder
+    bump: minor
```
Comment (acatangiu) [inline prdoc/pr_4959.prdoc:14]: you should also do `minor` bumps for all runtimes where the new one is used

Comment (ozgunozerk) [reply prdoc/pr_4959.prdoc:14]: Done! Also did the same for `pallet-xcm`

**Comment by acatangiu** [comment]
> The CI pipeline was cancelled due to failure one of the required jobs. **Job name**: cargo-clippy **Logs**: https://gitlab.parity.io/parity/mirrors/polkadot-sdk/-/jobs/6718587

You still have this failing compilation ^

**Comment by acatangiu** [comment]
> > The CI pipeline was cancelled due to failure one of the required jobs. **Job name**: cargo-clippy **Logs**: https://gitlab.parity.io/parity/mirrors/polkadot-sdk/-/jobs/6718587
> 
> You still have this failing compilation ^

You should be able to reproduce locally: `cargo test -r -p pallet-xcm`

**Comment by ozgunozerk** [comment]
> You should be able to reproduce locally: cargo test -r -p pallet-xcm

Yes, sorry, I was just running `cargo clippy` to see if there is any issue. 

The issue was due to `From<Location>` is not implemented for the type `AccountId32`.  I've fixed the error by implementing it. 

Note: now `staging-xcm` imports `sp-runtime` crate to implement `From<AccountId32> for Location` trait. This way, runtime developers won't have cast between `AccountId32` and `[u8; 32]` to use benefit from this new change.
The other solution was to cast `into()` to every `AccountId32` instance in every runtime affected by this, and I believe it would be ugly.

**Comment by ozgunozerk** [comment]
@acatangiu clippy problem is fixed, also reverted the fmt changes introduced by format on save so that `fmt` workflow wouldn't fail. Should be good to go from what I can tell

File: polkadot/xcm/src/v4/location.rs [hunk 10]
```diff
@@ -285,7 +286,7 @@ impl Location {
 	/// ```
 	pub fn match_and_split(&self, prefix: &Location) -> Option<&Junction> {
 		if self.parents != prefix.parents {
-			return None
+			return None;
```
Comment (acatangiu) [inline polkadot/xcm/src/v4/location.rs:289]:
```suggestion
			return None
```

File: polkadot/xcm/src/v4/location.rs [hunk 11]
```diff
@@ -409,7 +410,7 @@ impl Location {
 	pub fn simplify(&mut self, context: &Junctions) {
 		if context.len() < self.parents as usize {
 			// Not enough context
-			return
+			return;
```
Comment (acatangiu) [inline polkadot/xcm/src/v4/location.rs:413]:
```suggestion
			return
```

File: polkadot/xcm/src/v4/location.rs [hunk 12]
```diff
@@ -21,6 +21,7 @@ use crate::{v3::MultiLocation as OldLocation, VersionedLocation};
 use codec::{Decode, Encode, MaxEncodedLen};
 use core::result;
 use scale_info::TypeInfo;
+use sp_runtime::AccountId32;
```
Comment (acatangiu) [inline polkadot/xcm/src/v4/location.rs:24]:
```suggestion
```

File: polkadot/xcm/src/v4/location.rs [hunk 13]
```diff
@@ -534,6 +535,14 @@ impl From<[u8; 32]> for Location {
 	}
 }
 
+impl From<AccountId32> for Location {
+	fn from(account: AccountId32) -> Self {
+		let bytes: [u8; 32] = account.into();
+		let junction: Junction = bytes.into();
+		junction.into()
+	}
+}
```
Comment (acatangiu) [inline polkadot/xcm/src/v4/location.rs:544]:
```suggestion
impl From<sp_runtime::AccountId32> for Location {
	fn from(id: sp_runtime::AccountId32) -> Self {
		Junction::AccountId32 { network: None, id: id.into() }.into()
	}
}
```

**Review by acatangiu — APPROVED** [review]
Changes are good, you just have to make the CI happy - you can check the failed checks on their `details` button to find out what/why's failing.

**Comment by ozgunozerk** [comment]
> Changes are good, you just have to make the CI happy - you can check the failed checks on their details button to find out what/why's failing.

Yep, I know. As I explained, my bad for previously thinking that `cargo clippy` should be good enough. And thanks for guiding me.

About `semver` [check](https://github.com/paritytech/polkadot-sdk/actions/runs/9995265484/job/27627001703?pr=4959) that is failing now: 
```
error[E0658]: `#[diagnostic]` attribute name space is experimental
```

this error seems a bit cryptic. It refers to `serde`s source files. Any idea?

**Comment by acatangiu** [comment]
> > Changes are good, you just have to make the CI happy - you can check the failed checks on their details button to find out what/why's failing.
> 
> Yep, I know. As I explained, my bad for previously thinking that `cargo clippy` should be good enough. And thanks for guiding me.
> 
> About `semver` [check](https://github.com/paritytech/polkadot-sdk/actions/runs/9995265484/job/27627001703?pr=4959) that is failing now:
> 
> ```
> error[E0658]: `#[diagnostic]` attribute name space is experimental
> ```
> 
> this error seems a bit cryptic. It refers to `serde`s source files. Any idea?

this failure is unrelated probably coming from some upstream serde change - it is currently failing on all PRs...

you can ignore this one, we'll fix it. you can check the others

**Comment by ozgunozerk** [comment]
Fixed the `docs` related failure. Aside from 5 pending ones, all the others seem to be passing 🎉
