### PR TITLE
bench all weekly - and fix for pallet_multisig lib

### LINKED ISSUE #6196: Update pallet weights every week
With changes to FRAME, the Rust compiler version, pallets and the benchmarker itself, we should try to update the pallet weights on a weekly basis to see regressions early and not just before a release.

Task: Update the weights of all pallets from all runtimes every week. It should re-use the already open MR and force-push there, to avoid spamming up new MRs if reviews are slow.

### LINKED ISSUE #7204: Multisig pallet has outdated `WeightInfo` trait
### Is there an existing issue?

- [x] I have searched the existing issues

### Experiencing problems? Have you tried our Stack Exchange first?

- [x] This is not a support question.

### Description of bug

Currently multisig pallet [benchmarks](https://github.com/paritytech/polkadot-sdk/blob/master/substrate/frame/multisig/src/benchmarking.rs#L233) include a parameter `z` that is however not reflected in the corresponding [WeightInfo](https://github.com/paritytech/polkadot-sdk/blob/master/substrate/frame/multisig/src/weights.rs#L57-L59) trait.

This can be solved by simply running the benchmarks, which will generate weights that depend on such parameter, and update the corresponding usages.

The current problem right now is that when parachains perform the corresponding benchmarks, the resulting `WeightInfo` is not the expected one and is definitely not compatible, which forces them to manually tweak the benchmarks to meet the outdated `WeightInfo` interface.

I'd happily fix the issue myself and submit the corresponding PR, but I guess there's a well-known infrastructure to run the benchmarks from a given reference hardware.

### Steps to reproduce

Simply run the benchmarks in a parachain and the resulting `WeightInfo` trait won't be compatible with the multibatching pallet.

### PR DESCRIPTION
**Pull request by mordamax**
Closes #6196 
Closes #7204

Example of PR: https://github.com/paritytech/polkadot-sdk/pull/6816

Every sunday 01:00 AM it's going to start to benchmark (with /cmd bench) all runtimes and all pallets
Then diff total will be pushed to a branch and PR open,. I assume review-bot is going assign required reviewers per changed files

I afraid each weeks will be too much to review & merge, but we can adjust later

Bonus: fix for pallet_multisig lib and substrate/.maintain/frame-weight-template.hbs , which didn't let to compile new weights

### CODE REVIEW

**Review by AndWeHaveAPlan — APPROVED** [review]

**Comment by bkchr** [comment]
The pr should be merged automatically if in the difference is not that much more. The cherry on top would be to compare multiple weeks and if it goes up, to create some sort of alarm.

**Review by alvicsam — APPROVED** [review]

**Comment by mordamax** [comment]
> The pr should be merged automatically if in the difference is not that much more. The cherry on top would be to compare multiple weeks and if it goes up, to create some sort of alarm.

There's only auto-merge feature available for automatic merging, but it will still require some (even formal) approvals, to avoid giving too much permissions for bot which would have to overcome at least github minimum requirements if we would like it to merge without approvals. Obviously we don't want it.

Given the fact that this is going to produce a diff in many folders, naturally it will assign too many people/teams for review (via Review-Bot), so I will turn this PR to draft again, and I'm going to think how to make this requirement more loose, as well as how to notify the owners of the weight files, if this went too much up

**Review by EgorPopelyaev — APPROVED** [review]

File: substrate/frame/multisig/src/lib.rs [hunk 1]
```diff
@@ -453,7 +454,7 @@ pub mod pallet {
 		/// - I/O: 1 read `O(S)`, one remove.
 		/// - Storage: removes one item.
 		#[pallet::call_index(3)]
-		#[pallet::weight(T::WeightInfo::cancel_as_multi(other_signatories.len() as u32))]
+		#[pallet::weight(T::WeightInfo::cancel_as_multi(other_signatories.len() as u32, 0))]
```
Comment (ggwpez) [inline substrate/frame/multisig/src/lib.rs:457]: @ggwpez check

File: .github/workflows/bench-all-runtimes.yml [hunk 2]
```diff
@@ -0,0 +1,165 @@
+name: Bench all runtimes
+
+on:
+  # schedule:
+    # - cron: '0 1 * * 0' # weekly on Sunday night 01:00 UTC
```
Comment (ggwpez) [inline .github/workflows/bench-all-runtimes.yml:5]: Disabled currently?

Comment (mordamax) [reply .github/workflows/bench-all-runtimes.yml:5]: yes, until we try it out few times manually, and adjust

File: substrate/frame/multisig/src/lib.rs (hunk 1 above)
Comment (ggwpez) [reply substrate/frame/multisig/src/lib.rs]: Simplified the benchmarks now. The z param does not matter since it is neither in storage or a call argument.

**Review by ggwpez — APPROVED** [review]

File: substrate/frame/multisig/src/lib.rs (hunk 1 above)
Comment (mordamax) [reply substrate/frame/multisig/src/lib.rs]: @ggwpez thanks! so need to regenerate bench for this pallet once more?

**Comment by iulianbarbu** [comment]
LGTM overall! Have two questions. Disclaimer: I do not have enough context on benchmarking.

1. Why don't we use `bench-omni`? 

2. When it comes to reviewing weights changes to all pallets/all runtimes, should we do checks against weights we committed a few weeks back too (e.g. 1/2 months ago)? I am not sure which are the thresholds we'll be accepting for regressions, and I am curious how we'd defend against constant increases below the thresholds week after week.

3. I am seeing we run `subweight compare commits` somewhere in the workflow. Can the report be added to the PR - can be done in a follow up too? I am thinking such report might be useful for the comparisons with older weights as I suggested at point 2.

Curious about your thoughts.

**Comment by mordamax** [comment]
> LGTM overall! Have a few questions. Disclaimer: I do not have enough context on benchmarking.
> 
> 1. Why don't we use `bench-omni`?

we will switch to bench-omni as default bench as soon as the https://github.com/paritytech/polkadot-sdk/issues/6797 fix is confirmed 👍 

> 2. When it comes to reviewing weights changes to all pallets/all runtimes, should we do checks against weights we committed a few weeks back too (e.g. 1/2 months ago)? I am not sure which are the thresholds we'll be accepting for regressions, and I am curious how we'd defend against constant increases below the thresholds week after week.

Yep, we discussed this too, and the way to go could be comparing with the previous stable release tag. But need to explore this more

> 3. I am seeing we run `subweight compare commits` somewhere in the workflow. Can the report be added to the PR - can be done in a follow up too? I am thinking such report might be useful for the comparisons with older weights as I suggested at point 2.
> 

Yes, my plan was to replace this with link to https://weights.tasty.limo/compare - this shows a diff dynamically to a given branch. so we could do 2 links - 1) compare with master, 2) compare with prev release and add this to a body of a PR
