### PR TITLE
XCM v5

### LINKED ISSUE #3434: Better delivery fees: PayFees
As you all know, there have been a lot of XCM related issues in Kusama lately. This is because of the new delivery fees not being integrated in the best way to the executor.

There are three problems I can identify:
1. Getting delivery fees from holding during execution
2. Estimating delivery fees
3. Fixing delivery fees for multi-hop messages

For 1. we need a system that's similar to `BuyExecution` but for delivery fees. We could have an instruction `BuyTransport` that works in a similar way. You pay once for all delivery fees and can be certain the rest of the execution will succeed.

Something like `BuyTransport` would work, but I'd like to take this opportunity to not add more must-use instructions that make XCM harder to use. It's already hard enough when people forget a `BuyExecution` instruction. I think it's worthwhile to pay for these fees transparently.

Different xcm senders can charge different prices, and we can only identify them via calling `validate_send`, which calls a tuple and each element either returns the price or fails and it tries the next one. These senders validate using the destination. So we need to know the destination of all messages that will be sent beforehand.

My proposal is to gather all destinations beforehand, and buy enough delivery fees for sending whenever we pay for them, be it on a custom instruction or on the first instruction that loads the holding register.

The size of the message is also important, so I suggest we use a worst-case message in case it doesn't increase costs too much.

I'll leave the other two for other issues.

L.E.: XCM RFC for this https://github.com/paritytech/xcm-format/pull/53

### PR DESCRIPTION
**Pull request by franciscoaguirre**
# Context

This PR aims to introduce XCMv5, for now it's in progress and will be updated over time.
This branch will serve as a milestone branch for merging in all features we want to add to XCM, roughly outlined [here](https://github.com/polkadot-fellows/xcm-format/issues/60).
More features could be added.

## TODO
- [x] Migrate foreign assets from v3 to v4
- [x] Setup v5 skeleton
- [x] Remove XCMv2
- [x] https://github.com/paritytech/polkadot-sdk/pull/5390
- [x] https://github.com/paritytech/polkadot-sdk/pull/5585
- [x] https://github.com/paritytech/polkadot-sdk/pull/5420
- [x] https://github.com/paritytech/polkadot-sdk/pull/5876
- [x] https://github.com/paritytech/polkadot-sdk/pull/5971
- [x] https://github.com/paritytech/polkadot-sdk/pull/6148
- [x] https://github.com/paritytech/polkadot-sdk/pull/6228

Fixes #3434 
Fixes https://github.com/paritytech/polkadot-sdk/issues/4190
Fixes https://github.com/paritytech/polkadot-sdk/issues/5209
Fixes https://github.com/paritytech/polkadot-sdk/issues/5241
Fixes https://github.com/paritytech/polkadot-sdk/issues/4284

### CODE REVIEW

File: cumulus/parachains/runtimes/bridge-hubs/common/src/message_queue.rs [hunk 1]
```diff
@@ -23,7 +23,7 @@ use frame_support::{
 use pallet_message_queue::OnQueueChanged;
 use scale_info::TypeInfo;
 use snowbridge_core::ChannelId;
-use xcm::v4::{Junction, Location};
+use xcm::v5::{Junction, Location};
```
Comment (yrong) [inline cumulus/parachains/runtimes/bridge-hubs/common/src/message_queue.rs:26]: Would it be better to use `prelude` or `latest` here?

Comment (bkontur) [reply cumulus/parachains/runtimes/bridge-hubs/common/src/message_queue.rs:26]: @yrong yes, sure, please, you can open PR directly to the master with fixing message_queue.rs to use latest - it will help reducing XCMv5 PR size.

and to your minor fix, it is not that correct, because pools are using `xcm::v4::Location`, we need possibly migration for that, so using there `xcm:v4` there is correct

File: cumulus/parachains/integration-tests/emulated/tests/bridges/bridge-hub-westend/src/tests/transact.rs [hunk 2]
```diff
@@ -0,0 +1,249 @@
...
+	let asset_hub_location = BridgeHubWestend::sibling_location_of(AssetHubWestend::para_id());
+
+	// TODO(https://github.com/paritytech/polkadot-sdk/issues/6197): dry-run to get local fees, for now use hardcoded value.
+	let ah_fees_amount = 90_000_000_000u128; // current exact value 79_948_099_299
+	let fees_for_ah: Asset = (weth.id.clone(), ah_fees_amount).into();
+
+	let require_weight_at_most = Weight::from_parts(1000000000, 200000);
+	// xcm to be executed at dest
+	let xcm_on_dest = Xcm(vec![
+		Transact { origin_kind: OriginKind::Xcm, require_weight_at_most, call },
```
Comment (yrong) [inline cumulus/parachains/integration-tests/emulated/tests/bridges/bridge-hub-westend/src/tests/transact.rs:53]: `require_weight_at_most` is deprecated.

File: cumulus/parachains/integration-tests/emulated/tests/assets/asset-hub-westend/src/tests/hybrid_transfers.rs [hunk 3]
```diff
@@ -819,3 +819,88 @@ fn transfer_native_asset_from_relay_to_para_through_asset_hub() {
...
+			// RefundSurplus to get back any unspent fees
+			RefundSurplus,
+			DepositAsset { assets: Wild(All), beneficiary: t.args.beneficiary },
+		]);
+		let xcm = Xcm::<()>(vec![
+			WithdrawAsset(all_assets.into()),
+			PayFees { asset: fees.clone() },
+			InitiateTransfer {
+				destination: t.args.dest,
+				remote_fees: Some(AssetTransferFilter::ReserveWithdraw(fees.into())),
```
Comment (yrong) [inline cumulus/parachains/integration-tests/emulated/tests/assets/asset-hub-westend/src/tests/hybrid_transfers.rs:852]: > Furthermore, through remote_fees: Option<AssetTransferFilter>, it shall allow specifying a single asset to be used for fees on dest chain. 

Can `remote_fees` contains multiple assets and also to allow `PayFees` with multiple assets?

Comment (acatangiu) [reply cumulus/parachains/integration-tests/emulated/tests/assets/asset-hub-westend/src/tests/hybrid_transfers.rs:852]: No, this was discussed in the ‘PayFees’ RFC and decided to keep it simple with single asset. There aren’t real examples of paying multiple fees in different assets on a single chain.

File: cumulus/parachains/integration-tests/emulated/tests/bridges/bridge-hub-westend/src/tests/transact.rs (hunk 2 above)
Comment (franciscoaguirre) [reply cumulus/parachains/integration-tests/emulated/tests/bridges/bridge-hub-westend/src/tests/transact.rs:53]: Yeah, still haven't integrated that here it seems

File: cumulus/parachains/integration-tests/emulated/tests/assets/asset-hub-westend/src/tests/hybrid_transfers.rs (hunk 3 above)
Comment (yrong) [reply cumulus/parachains/integration-tests/emulated/tests/assets/asset-hub-westend/src/tests/hybrid_transfers.rs:852]: > There aren’t real examples of paying multiple fees in different assets on a single chain.

Fee 1 in DOT dry run [here](https://github.com/yrong/polkadot-sdk/blob/0e27a22dd6a7af3130393841b0d67ca71fbf0035/bridges/snowbridge/pallets/outbound-queue-v2/runtime-api/src/lib.rs#L21) for the execution cost(i.e. merkle the message tree) on BH.

Fee 2 in WETH to dry run [submit](https://github.com/Snowfork/snowbridge/blob/fa9b8a7b3551cc9df8ee3239dc2830be5d84728e/contracts/src/Gateway.sol#L419) on Ethereum. 

We need these two kinds of fees as user input for building the transfer [xcm](https://github.com/yrong/polkadot-sdk/blob/0e27a22dd6a7af3130393841b0d67ca71fbf0035/cumulus/parachains/integration-tests/emulated/tests/bridges/bridge-hub-westend/src/tests/snowbridge_v2.rs#L271) on AH.

Comment (acatangiu) [reply cumulus/parachains/integration-tests/emulated/tests/assets/asset-hub-westend/src/tests/hybrid_transfers.rs:852]: But the XCM "executed" on Ethereum and the one executed on BH are different and can have different fee assets:

Let's assume a simple WETH transfer from AH to eth (the XCM intended for Ethereum is actually irrelevant):
```rust
XcmAtEthereum = Xcm::new(vec![
	WithdrawAsset(WETH, 10),
	PayFees(WETH, 0.01),
	DepositAsset(Wild(All), beneficiary),
]);
```

The XCM executing on BH is actually (assuming current `SovereignPaidExporter`):
```rust
XcmAtBridgeHub = Xcm::new(vec![
	WithdrawAsset(DOT, 0.01),
	PayFees(DOT, 0.01),
	ExportMessage(XcmAtEthereum),
	RefundSurplus,
	DepositAsset(Wild(All), origin),
]);
```

So you can see that BH is using `PayFees(DOT)` and Ethereum is using `PayFees(WETH)`.

----

AH executor is not aware of BH, so AH "sends directly" to Ethereum.

On AH, the instructions to be executed would have to be:

```rust
XcmAtAssetHub = Xcm::new(vec![
	WhateverInstructionsBefore,
	...,
	InitiateTransfer(
		destination: BridgeHub,
		assets: vec![AssetTransferFilter::DestinationReserve(WETH, 9.99)],
		remote_fees: Some(AssetTransferFilter::DestinationReserve(WETH, 0.01)),
		preserve_origin: false,
		remote_xcm: Xcm::new(vec![DepositAsset(Wild(All), beneficiary)]),
	),
]);
```

Then the AH exporter knows it needs to send to BH, builds `XcmAtBridgeHub` from above, charges `0.01` DOT transport fee and sends to BH.

Comment (franciscoaguirre) [reply cumulus/parachains/integration-tests/emulated/tests/assets/asset-hub-westend/src/tests/hybrid_transfers.rs:852]: But it's never two assets for fees in one chain, it's one asset in two different chains

Comment (yrong) [reply cumulus/parachains/integration-tests/emulated/tests/assets/asset-hub-westend/src/tests/hybrid_transfers.rs:852]: > charges 0.01 DOT transport fee and sends to BH with `SovereignPaidExporter`

The 0.01 DOT is only to cover the execution of xcm on BH until delivered to message queue [here](https://github.com/yrong/polkadot-sdk/blob/0e27a22dd6a7af3130393841b0d67ca71fbf0035/bridges/snowbridge/pallets/outbound-queue-v2/src/send_message_impl.rs#L53)

After that the message is async dispatched on idle with [committed to header](https://github.com/yrong/polkadot-sdk/blob/0e27a22dd6a7af3130393841b0d67ca71fbf0035/bridges/snowbridge/pallets/outbound-queue-v2/src/lib.rs#L344). This should be the main cost of the execution on BH and it's what the dry run [here](https://github.com/yrong/polkadot-sdk/blob/0e27a22dd6a7af3130393841b0d67ca71fbf0035/bridges/snowbridge/pallets/outbound-queue-v2/runtime-api/src/lib.rs#L21) estimated for.

Say it's 0.1 DOT(10x more), so the intention here is not to mix the two portions of fees together(i.e. 0.1+0.01=0.11 DOT), we minimize the static config of delivery fee [here](https://github.com/yrong/polkadot-sdk/blob/0e27a22dd6a7af3130393841b0d67ca71fbf0035/cumulus/parachains/runtimes/assets/asset-hub-westend/src/xcm_config.rs#L694) as 0.01 DOT and make the 0.1 DOT a user input.

Anyway, we can workaround it with the single fee asset. UI just convert the 0.1 DOT to WETH and added that to the [remote fee portion](https://github.com/yrong/polkadot-sdk/blob/0e27a22dd6a7af3130393841b0d67ca71fbf0035/cumulus/parachains/integration-tests/emulated/tests/bridges/bridge-hub-westend/src/tests/snowbridge_v2.rs#L271) when building xcm on AH.

File: polkadot/xcm/src/v5/junction.rs [hunk 4]
```diff
@@ -0,0 +1,322 @@
...
+
+/// The genesis hash of the Westend testnet. Used to identify it.
+pub const WESTEND_GENESIS_HASH: [u8; 32] =
+	hex!["e143f23803ac50e8f6f8e62695d1ce9e4e1d68aa36c1cd2cfd15340213f3423e"];
+
+/// The genesis hash of the Rococo testnet. Used to identify it.
+pub const ROCOCO_GENESIS_HASH: [u8; 32] =
+	hex!["6408de7737c59c238890533af25896a2c20608d8b380bb01029acb392781063e"];
+
+// TODO: What to use here?
```
Comment (franciscoaguirre) [inline polkadot/xcm/src/v5/junction.rs:114]: @acatangiu I don't know what to put here since Wococo is inactive

Comment (acatangiu) [reply polkadot/xcm/src/v5/junction.rs:114]: we should simply delete all Wococo references

Comment (acatangiu) [reply polkadot/xcm/src/v5/junction.rs:114]: https://github.com/paritytech/polkadot-sdk/pull/6361

**Comment by acatangiu** [comment]
bot fmt

File: polkadot/xcm/xcm-runtime-apis/tests/mock.rs [hunk 5]
```diff
@@ -144,7 +144,8 @@ parameter_types! {
 	pub const BaseXcmWeight: Weight = Weight::from_parts(100, 10); // Random value.
 	pub const MaxInstructions: u32 = 100;
 	pub const NativeTokenPerSecondPerByte: (AssetId, u128, u128) = (AssetId(HereLocation::get()), 1, 1);
-	pub UniversalLocation: InteriorLocation = [GlobalConsensus(NetworkId::Westend), Parachain(2000)].into();
+	pub UniversalLocation: InteriorLocation = [GlobalConsensus(NetworkId::ByGenesis(WESTEND_GENESIS_HASH)), Parachain(2000)].into();
+	pub static AdvertisedXcmVersion: XcmVersion = 4;
```
Comment (bkontur) [inline polkadot/xcm/xcm-runtime-apis/tests/mock.rs:148]: Westend is not important here, and `AdvertisedXcmVersion` is unused

```suggestion
	pub UniversalLocation: InteriorLocation = [GlobalConsensus(NetworkId::ByGenesis([0; 32)), Parachain(2000)].into();
```

File: polkadot/xcm/xcm-runtime-apis/tests/mock.rs [hunk 6]
```diff
@@ -33,7 +33,7 @@ use frame_support::{
 };
 use frame_system::{EnsureRoot, RawOrigin as SystemRawOrigin};
 use pallet_xcm::TestWeightInfo;
-use xcm::{prelude::*, Version as XcmVersion};
+use xcm::{latest::WESTEND_GENESIS_HASH, prelude::*, Version as XcmVersion};
```
Comment (bkontur) [inline polkadot/xcm/xcm-runtime-apis/tests/mock.rs:36]:
```suggestion
use xcm::{prelude::*, Version as XcmVersion};
```

File: polkadot/xcm/xcm-executor/src/lib.rs [hunk 7]
```diff
@@ -83,13 +86,17 @@ pub struct XcmExecutor<Config: config::Config> {
...
 	fees_mode: FeesMode,
+	fees: AssetsInHolding,
 	/// Asset provided in last `BuyExecution` instruction (if any) in current XCM program. Same
 	/// asset type will be used for paying any potential delivery fees incurred by the program.
-	asset_used_for_fees: Option<AssetId>,
+	asset_used_in_buy_execution: Option<AssetId>,
+	/// Stores the current message's weight.
+	message_weight: Weight,
 	_config: PhantomData<Config>,
+	asset_claimer: Option<Location>,
```
Comment (acatangiu) [inline polkadot/xcm/xcm-executor/src/lib.rs:96]: nit:

```suggestion
	asset_claimer: Option<Location>,
	_config: PhantomData<Config>,
```

File: polkadot/xcm/xcm-executor/src/lib.rs [hunk 8]
```diff
@@ -322,8 +339,11 @@ impl<Config: config::Config> XcmExecutor<Config> {
 			appendix_weight: Weight::zero(),
 			transact_status: Default::default(),
 			fees_mode: FeesMode { jit_withdraw: false },
-			asset_used_for_fees: None,
+			fees: AssetsInHolding::new(),
+			asset_used_in_buy_execution: None,
+			message_weight: Weight::zero(),
 			_config: PhantomData,
+			asset_claimer: None,
```
Comment (acatangiu) [inline polkadot/xcm/xcm-executor/src/lib.rs:346]:
```suggestion
			asset_claimer: None,
			_config: PhantomData,
```

**Review by acatangiu — APPROVED** [review]

File: cumulus/parachains/runtimes/testing/penpal/src/lib.rs [hunk 9]
```diff
@@ -494,7 +495,10 @@ impl pallet_assets::Config<ForeignAssetsInstance> for Runtime {
 	type AssetId = ForeignAssetsAssetId;
 	type AssetIdParameter = ForeignAssetsAssetId;
 	type Currency = Balances;
-	type CreateOrigin = AsEnsureOriginWithArg<EnsureSigned<AccountId>>;
+	// This is to allow any other remote location to create foreign assets. Used in tests, not
+	// recommended on real chains.
+	type CreateOrigin =
+		ForeignCreators<Everything, LocationToAccountId, AccountId, xcm::latest::Location>;
```
Comment (franciscoaguirre) [inline cumulus/parachains/runtimes/testing/penpal/src/lib.rs:501]: This change breaks existing tests. I'm planning on implementing this trait for tuples and putting a tuple here with the old value.

Comment (acatangiu) [reply cumulus/parachains/runtimes/testing/penpal/src/lib.rs:501]: Which test does it break and why?

**Review by bkontur — COMMENTED** [review]
partial review for `polkadot/xcm` subdir, just few nits so far

**Review by bkontur — APPROVED** [review]
lgtm module a few very nits and I would like to merge this [PR](https://github.com/paritytech/polkadot-sdk/pull/6383) here

File: polkadot/xcm/src/v5/junction.rs [hunk 10]
```diff
@@ -0,0 +1,322 @@
...
+pub const WOCOCO_GENESIS_HASH: [u8; 32] =
+	hex!["0000000000000000000000000000000000000000000000000000000000000000"];
+
```
Comment (acatangiu) [inline polkadot/xcm/src/v5/junction.rs:117]:
```suggestion
```

File: polkadot/xcm/src/v5/junction.rs [hunk 11]
```diff
@@ -0,0 +1,322 @@
...
+	fn from(old: OldNetworkId) -> Self {
+		use OldNetworkId::*;
+		match old {
+			ByGenesis(hash) => Self::ByGenesis(hash),
+			ByFork { block_number, block_hash } => Self::ByFork { block_number, block_hash },
+			Polkadot => Self::Polkadot,
+			Kusama => Self::Kusama,
+			Westend => Self::ByGenesis(WESTEND_GENESIS_HASH),
+			Rococo => Self::ByGenesis(ROCOCO_GENESIS_HASH),
+			Wococo => Self::ByGenesis(WOCOCO_GENESIS_HASH),
```
Comment (acatangiu) [inline polkadot/xcm/src/v5/junction.rs:176]:
```suggestion
			Wococo => unimplemented!(),
```

File: cumulus/parachains/runtimes/testing/penpal/src/lib.rs (hunk 9 above)
Comment (franciscoaguirre) [reply cumulus/parachains/runtimes/testing/penpal/src/lib.rs:501]: Tests that create foreign assets on penpal with an account origin

File: polkadot/xcm/src/v5/junction.rs (hunk 11 above)
Comment (franciscoaguirre) [reply polkadot/xcm/src/v5/junction.rs]: This will panic and it will panic in the runtime if you receive a message like this. I would instead either turn this into `TryFrom` or return a nonsensical by genesis network id

Comment (acatangiu) [reply polkadot/xcm/src/v5/junction.rs]: I was thinking nobody uses Wococo, but you are right that someone could intentionally send a malicious V4 XCM with an internal `NetworkId::Wococo` so that conversion fails and panics the runtime.
Will revert! 👍

File: cumulus/parachains/runtimes/testing/penpal/src/lib.rs (hunk 9 above)
Comment (franciscoaguirre) [reply cumulus/parachains/runtimes/testing/penpal/src/lib.rs:501]: In `bridge-hub-rococo-integration-tests` for example, `send_token_from_ethereum_to_penpal`

Comment (acatangiu) [reply cumulus/parachains/runtimes/testing/penpal/src/lib.rs:501]: looking into all emulated tests now

Comment (acatangiu) [reply cumulus/parachains/runtimes/testing/penpal/src/lib.rs:501]: this one broke it: https://github.com/paritytech/polkadot-sdk/pull/4826/commits/abb8142b2cec0538cbe50481b142f27a6b6b67a8

got messed up when you fixed conflicts, merge damage is one of the most pervasive errors - because people don't usually review merge commits and changes can be overlooked

I suggest you run integ tests before and after fixing conflicts on merges to catch errors

**Comment by franciscoaguirre** [comment]
bot fmt

File: polkadot/xcm/src/v5/junction.rs (hunk 11 above)
Comment (bkontur) [reply polkadot/xcm/src/v5/junction.rs]: oh, right, good point
