### PR TITLE
Handle `CollationSeconded` Logs Conditionally

### LINKED ISSUE #1469: Silence "unexpected CollationResult" log when no listener was registered
This log is firing constantly because the lookahead collator isn't expecting to receive notifications about seconded candidates from validators. It should be silenced when there is no listener registered.

### PR DESCRIPTION
**Pull request by BradleyOlson64**
Separating the VStaging message handling case from V1 made the most sense to me. Let me know if there was a more concise way!

Closes #1469

### CODE REVIEW

**Comment by slumber** [comment]
We could also just drop it instead of duplicating code

**Comment by rphmeier** [comment]
@slumber is right. 

This isn't a V1/VStaging difference. You could write a V1 collator which didn't rely on receiving `Seconded` messages and a `VStaging` collator which did.

The logic change needed is to expect a `CollationSeconded` statement even when no higher-level  code cares about it.

**Comment by rphmeier** [comment]
We have three variables.

1. collation submitted
2. listener registered (can only be true if (1) is true)
3. received a `CollationSeconded` message.

We want to warn when (3) is true and (1) is false. We don't want to warn when (1), (3) are true but (2) is false.
The current code assumes (1) -> (2) but that is not true.

I hope this is clear now.

**Review by rphmeier — APPROVED** [review]

File: polkadot/node/network/collator-protocol/src/collator_side/mod.rs [hunk 1]
```diff
@@ -926,16 +926,41 @@ async fn handle_incoming_peer_message<Context>(
...
+						Some(_) => { // We've seen this collation before, so a seconded statement is expected
+							gum::trace!(
+								target: LOG_TARGET,
+								?statement,
+								?origin,
+								"received a valid `CollationSeconded`",
+							);
+						}, 
+						None => {
+							gum::debug!(
```
Comment (sandreim) [inline polkadot/node/network/collator-protocol/src/collator_side/mod.rs:956]: I'd make this a warning, usually a mismatch here is likely a bug.

**Review by sandreim — APPROVED** [review]

File: polkadot/node/network/collator-protocol/src/collator_side/mod.rs (hunk 1 above)
Comment (rphmeier) [reply polkadot/node/network/collator-protocol/src/collator_side/mod.rs:956]: `debug!` logs are often for bugs, just not critical ones.

**Review by slumber — APPROVED** [review]

**Comment by rphmeier** [comment]
bot merge
