### PR TITLE
cumulus/minimal-node: added prometheus metrics for the RPC client

### LINKED ISSUE #5409: RPC Collator: Introduce Useful Metrics
When starting a collator node there is an option to connect to external relay chain nodes via `--relay-chain-rpc-urls`. 

The spawned `RelayChainRpcInterface` performs the RPC calls to the relay chain through `RelayChainRpcClient`. It is used internally by the collator as well as in the minimal-nodes subsystems.

In the past we had instances where a huge amount of requests in combination with longer answer times led to complications in the subsystems. To allow better monitoring, we need some metrics on the `RelayChainRpcClient`.

We should expose metrics for the average timing information as well as a aggregates of the counts.

A nice starting point is to spin up a network using this zombienet test: https://github.com/paritytech/polkadot-sdk/blob/master/cumulus/zombienet/tests/0006-rpc_collator_builds_blocks.toml

From there you can discover the prometheus metrics that are exposed.

### LINKED ISSUE #5689: Multiple collators started on same machine conflict on prometheus exporter default port 9616
### Is there an existing issue?

- [X] I have searched the existing issues

### Experiencing problems? Have you tried our Stack Exchange first?

- [X] This is not a support question.

## Description

I started zombienet natively with `cumulus/zombienet/tests/0006_rpc-collator-builds-blocks.toml`. The network topology has two collators with minimal relay chain nodes which try to setup prometheus by creating a thin hyper server that responds to `/metrics` requests to localhost:9616. The hyper server is separate from the similar hyper server for the parachain part of the same collator. Both collators will race towards binding to 9616, resulting in a failure for one of them, which is not necessarily obvious when looking at the logs of the collator which can not bind. The relaychain minimal node's prometheus exporter is somewhat hidden and can be found in the logs if successful when setting it up, or through open ports exploration, but either way, not very well documented and straightfoward to refer to.

## To consider for a possible fix (maybe others too)

~~1. Expose the relay chain prometheus exporter ports through a CLI arg to be able to set it to specific unused ports. This is relevant for:
a. testing with multiple collators on the same machine.
b. node operators that want to set the relaychain prometheus exporter port to something else than 9616.
c. node operators/devs who don't know the relaychain prometheus exporter exists and find it by reading the code (or by reading the logs if its setup succeeds). If this is documented a bit more clearly in public docs this point can be ignored.~~ (We have support to pass a `--prometheus-port` flag to the relaychain part of the args received by a polkadot-parachain node already, which makes this point irrelevant).

~~2. We could also bind to a random unused port, don't act on 1 and let devs/operators rely on code reading and logs. It isn't very DX friendly.  I would avoid this considering the first point would fix this the good way and it isn't very complex either.~~ (First point is not relevant and this one doesn't matter anymore).

3. Emit an error when the prometheus exporter listener binding fails with port in use. This is trivial and can be done here: https://github.com/paritytech/polkadot-sdk/pull/5572. I will strike-through this part once we merge the PR.

### Steps to reproduce

This will start only the relay chain minimal node's prometheus exporter of `dave` collator, while `eve` exporter fails with no way of telling why (and more problematic if not knowing that it should be started, given it can be found out only if reading the code* for the relay chain rpc interface setup).

```bash
zombienet -l text --dir 9 -f --provider native spawn polkadot-sdk/cumulus/zombienet/tests/0006-rpc_collator_builds_blocks.toml
```

~~* I am not completely sure if the relaychain rpc interface's prometheus exporter startup is documented clearly outside of code though.~~  (there is a way to pass relaychain args including the prometheus port when starting a polkadot-parachain node)

### PR DESCRIPTION
**Pull request by iulianbarbu**
# Description

When we start a node with connections to external RPC servers (as a minimal node), we lack metrics around how many individual calls we're doing to the remote RPC servers and their duration. This PR adds metrics that measure durations of each RPC call made by the minimal nodes, and implicitly how many calls there are.

Closes #5409 
Closes #5689

## Integration

Node operators should be able to track minimal node metrics and decide appropriate actions according to how the metrics are interpreted/felt. The added metrics can be observed by curl'ing the prometheus metrics endpoint for the ~relaychain~ parachain (it was changed based on the review). The metrics are represented by ~`polkadot_parachain_relay_chain_rpc_interface`~ `relay_chain_rpc_interface` namespace (I realized lining up `parachain_relay_chain` in the same metric might be confusing :). Excerpt from the curl:

```
relay_chain_rpc_interface_bucket{method="chain_getBlockHash",chain="rococo_local_testnet",le="0.001"} 15
relay_chain_rpc_interface_bucket{method="chain_getBlockHash",chain="rococo_local_testnet",le="0.004"} 23
relay_chain_rpc_interface_bucket{method="chain_getBlockHash",chain="rococo_local_testnet",le="0.016"} 23
relay_chain_rpc_interface_bucket{method="chain_getBlockHash",chain="rococo_local_testnet",le="0.064"} 23
relay_chain_rpc_interface_bucket{method="chain_getBlockHash",chain="rococo_local_testnet",le="0.256"} 24
relay_chain_rpc_interface_bucket{method="chain_getBlockHash",chain="rococo_local_testnet",le="1.024"} 24
relay_chain_rpc_interface_bucket{method="chain_getBlockHash",chain="rococo_local_testnet",le="4.096"} 24
relay_chain_rpc_interface_bucket{method="chain_getBlockHash",chain="rococo_local_testnet",le="16.384"} 24
relay_chain_rpc_interface_bucket{method="chain_getBlockHash",chain="rococo_local_testnet",le="65.536"} 24
relay_chain_rpc_interface_bucket{method="chain_getBlockHash",chain="rococo_local_testnet",le="+Inf"} 24
relay_chain_rpc_interface_sum{method="chain_getBlockHash",chain="rococo_local_testnet"} 0.11719075
relay_chain_rpc_interface_count{method="chain_getBlockHash",chain="rococo_local_testnet"} 24
```

## Review Notes

The way we measure durations/hits is based on `HistogramVec` struct which allows us to collect timings for each RPC client method called from the minimal node., It can be extended to measure the RPCs against other dimensions too (status codes, response sizes, etc). The timing measuring is done at the level of the `relay-chain-rpc-interface`, in the `RelayChainRpcClient` struct's method  'request_tracing'. A single entry point for all RPC requests done through the relay-chain-rpc-interface. The requests durations will fall under exponential buckets described by start `0.001`, factor `4` and count `9`.

### CODE REVIEW

File: cumulus/client/relay-chain-minimal-node/src/blockchain_rpc_client.rs [hunk 1]
```diff
@@ -28,33 +28,43 @@ use polkadot_primitives::{
...
+			metrics: prometheus_registry
+				.and_then(|registry| BlockchainRpcMetrics::register(&registry).ok()),
+		}
 	}
 
 	pub async fn chain_get_header(
 		&self,
 		hash: Option<Hash>,
 	) -> Result<Option<Header>, RelayChainError> {
+		let _timer = self.metrics.as_ref().map(|inner| inner.start_chain_get_header_timer());
```
Comment (niklasad1) [inline cumulus/client/relay-chain-minimal-node/src/blockchain_rpc_client.rs:59]: I don't understand the reasoning by exposing these timer APIs
Would be much easier to just to:

```rust
   let now = Instant::now();
   let res = self.rpc_client.chain_get_block_hash(number).await;
   self.metrics.as_ref().map(|m| m.chain_head(now));
   res
```

Comment (niklasad1) [reply cumulus/client/relay-chain-minimal-node/src/blockchain_rpc_client.rs:59]: or does this "timer" take the drop into account and emit the time on drop?

Comment (iulianbarbu) [reply cumulus/client/relay-chain-minimal-node/src/blockchain_rpc_client.rs:59]: > Would be much easier to just to:

```
   let now = Instant::now();
   let res = self.rpc_client.chain_get_block_hash(number).await;
   self.metrics.as_ref().map(|m| m.chain_head(now));
   res
```

I tried something along these line but the selling point of the timers API is that they simply return an f64 referring to seconds (with fractions of seconds included), which is observed behind the scenes by the underlying histogram (or at least that's my understanding, I still have to test it).

Using the Instant/Duration APIs looked more convoluted because of the calculations required to obtain that f64 expected by prometheus `observe` API (which requires getting the elapsed duration as seconds, but then `subsec_as_millis` maybe, and then convert their addition to f64).

Comment (niklasad1) [reply cumulus/client/relay-chain-minimal-node/src/blockchain_rpc_client.rs:59]: ok fair enough

File: cumulus/client/relay-chain-rpc-interface/src/lib.rs [hunk 2]
```diff
@@ -87,12 +88,13 @@ impl RelayChainInterface for RelayChainRpcInterface {
...
 		let hash = match block_id {
 			BlockId::Hash(hash) => hash,
-			BlockId::Number(num) =>
+			BlockId::Number(num) => {
 				if let Some(hash) = self.rpc_client.chain_get_block_hash(Some(num)).await? {
 					hash
 				} else {
-					return Ok(None)
-				},
+					return Ok(None);
```
Comment (michalkucharczyk) [inline cumulus/client/relay-chain-rpc-interface/src/lib.rs:95]: nit: I'd leave it as it was, from what I see most returns are not ';' terminated.

File: cumulus/client/relay-chain-rpc-interface/src/metrics.rs [hunk 3]
```diff
@@ -0,0 +1,49 @@
...
+// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
+// GNU General Public License for more details.
+
+// You should have received a copy of the GNU General Public License
+// along with Cumulus.  If not, see <http://www.gnu.org/licenses/>.
+
+use prometheus::{Error as PrometheusError, HistogramTimer, Registry};
+use prometheus_endpoint::{HistogramOpts, HistogramVec, Opts};
+
+// Gathers metrics about the blockchain RPC client.
```
Comment (michalkucharczyk) [inline cumulus/client/relay-chain-rpc-interface/src/metrics.rs:20]:
```suggestion
/// Gathers metrics about the blockchain RPC client.
```

File: cumulus/client/relay-chain-rpc-interface/src/metrics.rs [hunk 4]
```diff
@@ -0,0 +1,49 @@
...
+#[derive(Clone)]
+pub(crate) struct BlockchainRpcMetrics {
```
Comment (michalkucharczyk) [inline cumulus/client/relay-chain-rpc-interface/src/metrics.rs:22]: maybe `RelaychainRpcMetrics` would be better?

**Review by michalkucharczyk — APPROVED** [review]
looks good, nits only.

File: cumulus/client/relay-chain-minimal-node/src/blockchain_rpc_client.rs (hunk 1 above)
Comment (michalkucharczyk) [reply cumulus/client/relay-chain-minimal-node/src/blockchain_rpc_client.rs]: Using builtin timers looks super nice to me.

File: cumulus/client/relay-chain-rpc-interface/src/metrics.rs [hunk 5]
```diff
@@ -0,0 +1,49 @@
...
+	pub(crate) fn register(registry: &Registry) -> Result<Self, PrometheusError> {
+		Ok(Self {
+			rpc_request: prometheus_endpoint::register(
+				HistogramVec::new(
+					HistogramOpts {
+						common_opts: Opts::new(
+							"polkadot_parachain_relay_chain_rpc_interface",
+							"Tracks stats about cumulus relay chain RPC interface",
+						),
+						buckets: prometheus::exponential_buckets(0.001, 4.0, 9)
```
Comment (michalkucharczyk) [inline cumulus/client/relay-chain-rpc-interface/src/metrics.rs:36]: just curiosity - any reason for these values?

Am I right that buckets will be?
```
0.001
0.004
0.016
0.064
0.256
1.024
4.096
16.384
65.536
```

Comment (iulianbarbu) [reply cumulus/client/relay-chain-rpc-interface/src/metrics.rs:36]: Correct for the buckets.

I picked the buckets split by seeing it used for other requests timers in the code (related to substrate libp2p), although there isn't a particular relationship between them. Ideally we'll have some preliminary measurements for these first and then pick the buckets. I am ok with these values though because they correspond to some rough back of the envelope measurements for exchanging data over the network (e.g USA -> EU -> USA ~ 150 ms). I think that the higher buckets (e.g. >1s) can be considered extreme, and might correspond to super infrequent outliers (assuming the network runs fine most of the time).

File: cumulus/client/relay-chain-rpc-interface/src/metrics.rs (hunk 4 above)
Comment (iulianbarbu) [reply cumulus/client/relay-chain-rpc-interface/src/metrics.rs]: here: [4481f5e](https://github.com/paritytech/polkadot-sdk/pull/5572/commits/4481f5ebf73172752a568ed1afe81776ded9be13)

File: cumulus/client/relay-chain-rpc-interface/src/metrics.rs (hunk 3 above)
Comment (iulianbarbu) [reply cumulus/client/relay-chain-rpc-interface/src/metrics.rs]: here: [4481f5e](https://github.com/paritytech/polkadot-sdk/pull/5572/commits/4481f5ebf73172752a568ed1afe81776ded9be13)

File: cumulus/client/relay-chain-rpc-interface/src/lib.rs [hunk 6]
```diff
@@ -213,7 +215,7 @@ impl RelayChainInterface for RelayChainRpcInterface {
 		let mut head_stream = self.rpc_client.get_imported_heads_stream()?;
 
 		if self.rpc_client.chain_get_header(Some(wait_for_hash)).await?.is_some() {
-			return Ok(())
+			return Ok(());
```
Comment (michalkucharczyk) [inline cumulus/client/relay-chain-rpc-interface/src/lib.rs:218]: one more

Comment (iulianbarbu) [reply cumulus/client/relay-chain-rpc-interface/src/lib.rs]: [d465d1b](https://github.com/paritytech/polkadot-sdk/pull/5572/commits/d465d1b3b8849b5d37d5c3a709b25e2fa4698018)

File: cumulus/client/relay-chain-minimal-node/src/lib.rs [hunk 7]
```diff
@@ -127,6 +128,7 @@ pub async fn build_minimal_relay_chain_node_with_rpc(
 	let client = cumulus_relay_chain_rpc_interface::create_client_and_start_worker(
 		relay_chain_url,
 		task_manager,
+		polkadot_config.prometheus_registry(),
```
Comment (skunert) [inline cumulus/client/relay-chain-minimal-node/src/lib.rs:131]: I am thinking about whether this is better registered on the parachain side.

Technically, this is doing relay chain calls. However, the calls to the relay chain are basically done only on collators, the code lives in cumulus. As a user I would probably expect these metrics to be attached to the parachain prometheus endpoint.

Comment (iulianbarbu) [reply cumulus/client/relay-chain-minimal-node/src/lib.rs]: I looked for reasons to keep the metrics on the relay chain side but couldn't find any. To be honest, it is still not clear to me what kind of metrics should fall under the relay chain prometheus exporter (its concerns on the collator side are not crispy clear in my mind yet), but for our case I agree that these metrics seem more relevant to the internals of how parachains work, so it would be useful to expose them in the "parachain" prometheus exporter exporter.

Changed this here: [309ae23](https://github.com/paritytech/polkadot-sdk/pull/5572/commits/309ae2390d438417a264beef27933db0e5ee86c6).

Comment (skunert) [reply cumulus/client/relay-chain-minimal-node/src/lib.rs]: > To be honest, it is still not clear to me what kind of metrics should fall under the relay chain prometheus exporter

So when you don't use `--relay-chain-rpc-urls` then the collator will start an embedded node. Which is basically the same as a polkadot full node that you start with the `polkadot` binary. 

If course this internal node will export all its metrics, there is a whole bunch of them defined in substrate. So in these scenarios it can make sense to monitor the relay chain node separately. This RPC functionality however is in the end parachain specific and therefore goes to the parachain prometheus endpoint.

**Review by skunert — APPROVED** [review]
nice!
