### PR TITLE
Fix DryRunApi client-facing XCM versions

### LINKED ISSUE #7413: DryRunApi.dryRunCall always produces the latest XCM version report
The [`DryRunApi.dryRunCall`](https://github.com/paritytech/polkadot-sdk/blob/698d9ae5b32785d3a5a55b770e973bbdb59ad271/polkadot/xcm/xcm-runtime-apis/src/dry_run.rs#L67) doesn't know what version to use when reporting the XCM objects back to the client.

The [common implementation in pallet-xcm](https://github.com/paritytech/polkadot-sdk/blob/698d9ae5b32785d3a5a55b770e973bbdb59ad271/polkadot/xcm/pallet-xcm/src/lib.rs#L2509-L2544) uses the latest one. If a client is not ready to interpret the newest version, it won't be able to read the output. I ran into this when testing locally.

All client-facing APIs should use versions that a client can understand (similar to the `xcmPaymentApi.queryAcceptablePaymentAssets`) so that clients won't break immediately if a chain upgrades.

The same might go for the `dryRunXcm`.

### PR DESCRIPTION
**Pull request by mrshiposha**
# Description

Fixes #7413

## Integration

This PR updates the `DryRunApi`. The signature of the `dry_run_call` is changed, and the XCM version of the return values of `dry_run_xcm` now follows the version of the input XCM program.

## Review Notes

* **The `DryRunApi` is modified**
* **Added the `Router::clear_messages` to `dry_run_xcm` common implementation**
* **Fixed the xcmp-queue's Router's clear_messages: channels details' first_index and last_index are reset when clearing**
* **The MIN_XCM_VERSION is added**
* The common implementation in the `pallet-xcm` is modified accordingly
* The `DryRunApi` tests are modified to account for testing old XCM versions
* The implementation from the `pallet-xcm` is used where it was not used (including the `DryRunApi` tests)
* All the runtime implementations are modified according to the Runtime API change

### CODE REVIEW

File: polkadot/xcm/pallet-xcm/src/lib.rs [hunk 1]
```diff
@@ -2513,6 +2513,7 @@ impl<T: Config> Pallet<T> {
 	/// Meant to be used in the `xcm_runtime_apis::dry_run::DryRunApi` runtime API.
 	pub fn dry_run_call<Runtime, Router, OriginCaller, RuntimeCall>(
 		origin: OriginCaller,
+		xcms_version: XcmVersion,
 		call: RuntimeCall,
```
Comment (x3c41a) [inline polkadot/xcm/pallet-xcm/src/lib.rs:2517]: I am just wondering why do we pass `RuntimeCall` parameter to `dry_run_call` and `VersionedXcm<RuntimeCall>` parameter to `dry_run_xcm` function? 

Using `let xcm_version = xcm.identify_version();` looks cleaner...

File: polkadot/xcm/xcm-runtime-apis/tests/fee_estimation.rs [hunk 2]
```diff
@@ -273,7 +289,26 @@ fn dry_run_reserve_asset_transfer() {
...
+
+#[test]
+fn dry_run_reserve_asset_transfer_v4() {
+	dry_run_reserve_asset_transfer_common(4);
+}
+
+#[test]
+fn dry_run_reserve_asset_transfer_v3() {
+	dry_run_reserve_asset_transfer_common(3);
+}
```
Comment (x3c41a) [inline polkadot/xcm/xcm-runtime-apis/tests/fee_estimation.rs:309]: You can utilise table-driven tests for this matter

#[test]
fn dry_run_reserve_asset_transfer_versions() {
    let test_cases = [XCM_VERSION, 5, 4, 3];

    for &version in &test_cases {
        dry_run_reserve_asset_transfer_common(version);
    }
}


same below

**Review by x3c41a — APPROVED** [review]

File: polkadot/xcm/xcm-runtime-apis/tests/fee_estimation.rs (hunk 2 above)
Comment (mrshiposha) [reply polkadot/xcm/xcm-runtime-apis/tests/fee_estimation.rs]: Done.

Note: this uncovered another bug (although I'm not sure it can be easily reproduced in production): the Router's messages weren't cleared before XCM dry-running in the `dry_run_xcm`.

See this commit: https://github.com/paritytech/polkadot-sdk/pull/7438/commits/1d7774676de6145476f7f2b87916fa6414fecb8a

Comment (x3c41a) [reply polkadot/xcm/xcm-runtime-apis/tests/fee_estimation.rs]: Very nice!

**Review by x3c41a — APPROVED** [review]

File: polkadot/xcm/pallet-xcm/src/lib.rs (hunk 1 above)
Comment (mrshiposha) [reply polkadot/xcm/pallet-xcm/src/lib.rs:2517]: Unfortunately, I believe we can't do it due to the logic of `dry_run_call`. It is a generic API method to examine the XCM effects of any given extrinsic. We can't extract the XCM version info from an arbitrary extrinsic (we could do this only from concrete ones, but this method is generic).

The `VersionedXcm` represents not an extrinsic but an XCM program. That is why a separate API method, the `dry_run_xcm`, is used for it. It serves another use case when we already have an XCM program (e.g., one of the forwarded ones) and want to learn its effect on the destination chain.

Comment (x3c41a) [reply polkadot/xcm/pallet-xcm/src/lib.rs:2517]: No more questions. Thanks for the explanation!

**Comment by bkchr** [comment]
> This PR makes breaking changes to the `DryRunApi`. The signature of the `dry_run_call` is changed, and the XCM version of the return values of `dry_run_xcm` now follows the version of the input XCM program.

Can you not just determine the `XCM` version of input xcm program and use this for the output? Otherwise you should at least bump the version of the runtime api.

**Comment by mrshiposha** [comment]
@bkchr 

>Can you not just determine the XCM version of input xcm program and use this for the output?

I did this for the `dry_run_xcm`. It was possible there. As for the `dry_run_call`, there is no input XCM program, just an arbitrary `RuntimeCall`.

>Otherwise you should at least bump the version of the runtime API.

Sure, will do.

**Comment by bkchr** [comment]
> As for the `dry_run_call`, there is no input XCM program, just an arbitrary `RuntimeCall`.

Somewhere in this `RuntimeCall` there will be a `XCM`? If not, you could just assume the minimum XCM version?

**Comment by mrshiposha** [comment]
We could examine the call and see if it is, say, `transfer_assets` from pallet-xcm. It seems to be a good enough default for common implementation.

I only worried about alternative XCM frontends like ORML pallet-xtokens. If the common implementation only considers pallet-xcm, the pallet-xtokens users will always receive the minimum XCM version.

CC @xlc

**Comment by acatangiu** [comment]
Assuming minimum is brittle, some new instructions do not have equivalents in older versions and conversion will fail. You could start with minimum and go through them until one successfully converts, but feels like overkill.

I'm personally happy with the current PR state where an explicit version is requested by the caller.

File: polkadot/xcm/pallet-xcm/src/lib.rs [hunk 3]
```diff
@@ -2571,22 +2590,57 @@ impl<T: Config> Pallet<T> {
 			XcmDryRunApiError::VersionedConversionFailed
 		})?;
 		let mut hash = xcm.using_encoded(sp_io::hashing::blake2_256);
-		frame_system::Pallet::<Runtime>::reset_events(); // To make sure we only record events from current call.
+
+		// To make sure we only record events from current call.
+		Router::clear_messages();
```
Comment (acatangiu) [inline polkadot/xcm/pallet-xcm/src/lib.rs:2595]: nice! I see this was done for dry_run_call but not for dry_run_xcm 🤦‍♂️

**Review by acatangiu — APPROVED** [review]

**Review by raymondkfcheung — APPROVED** [review]

File: polkadot/xcm/pallet-xcm/src/lib.rs (hunk 3 above)
Comment (mrshiposha) [reply polkadot/xcm/pallet-xcm/src/lib.rs:2595]: Yet, this fix breaks penpal runtime somehow...

Comment (mrshiposha) [reply polkadot/xcm/pallet-xcm/src/lib.rs:2595]: Does it influence prod, though? I have a feeling that these storages should be empty either way when running Runtime API properly.

Maybe the issue is with the test itself?

Comment (bkchr) [reply polkadot/xcm/pallet-xcm/src/lib.rs:2595]: > Does it influence prod, though? I have a feeling that these storages should be empty either way when running Runtime API properly.

Why should it be empty? Calling `clear_messages` here is correct, as otherwise the function will return invalid messages.

Comment (bkchr) [reply polkadot/xcm/pallet-xcm/src/lib.rs:2595]: (That got send when building block the runtime api function is called on)

Comment (acatangiu) [reply polkadot/xcm/pallet-xcm/src/lib.rs:2595]: Yes, calling `clear_messages()` here is correct. Can you look into the tests and find out _why_ exactly they are failing? Is it penpal runtime config issue or test issue?

Comment (mrshiposha) [reply polkadot/xcm/pallet-xcm/src/lib.rs:2595]: >Why should it be empty?

I just thought that maybe Runtime API runs with the state of the last finalized block. And I remembered that ParachainSystem's `on_finalize` clears the XCMP storages. However, it seems it does it partially anyway. So yeah, manual clearing before dry-running is needed anyway.

I will look into that.

Comment (mrshiposha) [reply polkadot/xcm/pallet-xcm/src/lib.rs:2595]: Turned out it wasn't the Penpal. The bug appeared in the Westend/Rococo AssetHub runtimes.

See the fix: https://github.com/paritytech/polkadot-sdk/pull/7438/commits/98dea1deb2e5aab66e967de41644207ab38a3943

As to why it appeared:
1. The xcmp-queue's `OutboundXcmpMessages` and `OutboundXcmpStatus` are supposed to be in sync. It isn't enough to clear `OutboundXcmpMessages` without syncing the indices from the `OutboundXcmpStatus`. If the storages are out-of-sync, it is possible (and that is what happened in the tests) that the `have_active` flag is erroneously set and the execution goes on the wrong branch. See [here](https://github.com/UniqueNetwork/polkadot-sdk/blob/9ada758b6643da59e97a1dd54c18a84bef276269/cumulus/pallets/xcmp-queue/src/lib.rs#L522-L538).
2. How they got out-of-sync: The integration tests use an emulated environment and call runtime APIs directly as Rust functions without things like `with_transaction`. This way, the dry run turns into an actual run, and all the networks process the resulting messages. The AssetHub is the reserve chain in the test scenario and has its storages modified after the `PenpalA` chain "dry-runs" a transfer call. When we try to "dry-run" a forwarded XCM program, we run into the issue of the storage being out-of-sync if we use the `clear_messages` implementation without the provided fix. You can verify this reasoning by looking at [this code](https://github.com/UniqueNetwork/polkadot-sdk/blob/9ada758b6643da59e97a1dd54c18a84bef276269/cumulus/parachains/integration-tests/emulated/tests/assets/asset-hub-westend/src/tests/xcm_fee_estimation.rs#L145-L211)

File: polkadot/xcm/xcm-runtime-apis/tests/fee_estimation.rs [hunk 4]
```diff
@@ -354,6 +389,15 @@ fn dry_run_xcm() {
 	});
 }
 
+#[test]
+fn dry_run_xcm_versions() {
+	let tested_versions = [XCM_VERSION, 5, 4, 3];
```
[the remark this answers is not in the document]
Comment (mrshiposha) [reply polkadot/xcm/xcm-runtime-apis/tests/fee_estimation.rs:425]: I added the `MIN_XCM_VERSION`. Please take a look to see if this is okay.

File: polkadot/xcm/xcm-runtime-apis/src/dry_run.rs [hunk 5]
```diff
@@ -64,7 +64,7 @@ sp_api::decl_runtime_apis! {
 		OriginCaller: Encode
 	{
 		/// Dry run call.
-		fn dry_run_call(origin: OriginCaller, call: Call) -> Result<CallDryRunEffects<Event>, Error>;
+		fn dry_run_call(origin: OriginCaller, xcms_version: XcmVersion, call: Call) -> Result<CallDryRunEffects<Event>, Error>;
```
[the remark this answers is not in the document]
Comment (mrshiposha) [reply polkadot/xcm/xcm-runtime-apis/src/dry_run.rs]: Done

File: polkadot/xcm/pallet-xcm/src/lib.rs (hunk 3 above)
Comment (acatangiu) [reply polkadot/xcm/pallet-xcm/src/lib.rs:2595]: nice find!

File: polkadot/xcm/xcm-runtime-apis/Cargo.toml [hunk 6]
```diff
@@ -1,6 +1,6 @@
 [package]
 name = "xcm-runtime-apis"
-version = "0.1.0"
+version = "0.2.0"
```
Comment (acatangiu) [inline polkadot/xcm/xcm-runtime-apis/Cargo.toml:3]: Since the API and crate are backwards compatible, let's only bump patch number so that we can backport this change.

Bumping minor or major doesn't allow backporting this to existing stable releases.

```suggestion
version = "0.1.1"
```

File: prdoc/pr_7438.prdoc [hunk 7]
```diff
@@ -0,0 +1,14 @@
...
+    description: |-
+      Fixes https://github.com/paritytech/polkadot-sdk/issues/7413
+
+      This PR updates the DryRunApi. The signature of the dry_run_call is changed, and the XCM version of the return values of dry_run_xcm now follows the version of the input XCM program.
+
+      It also fixes xcmp-queue's Router's `clear_messages`: the channel details `first_index` and `last_index` are reset when clearing.
+
+crates:
+- name: xcm-runtime-apis
+  bump: minor
```
Comment (acatangiu) [inline prdoc/pr_7438.prdoc:14]:
```suggestion
  bump: patch
```

**Review by acatangiu — APPROVED** [review]
nice!

File: polkadot/xcm/src/lib.rs [hunk 8]
```diff
@@ -518,6 +518,9 @@ pub mod prelude {
 		VersionedAssetId, VersionedAssets, VersionedInteriorLocation, VersionedLocation,
 		VersionedResponse, VersionedXcm, WrapVersion,
 	};
+
+	/// The minimal supported XCM version
+	pub const MIN_XCM_VERSION: XcmVersion = 3;
```
Comment (bkontur) [inline polkadot/xcm/src/lib.rs:523]: @mrshiposha @raymondkfcheung @franciscoaguirre 
Why do we need this hard-coded version? Because of tests bellow: `let tested_versions = MIN_XCM_VERSION..=XCM_VERSION;`? Or do we have other usages? There is no sanity check for this at least.

There is/was a kind of rule, that we support minimum `latest-2`, so when we add XCMv6, we remove XCMv3, iirc, we should also depracate XCMv4 at this point.

If this is still valid, then we should also depreacate XCMv3 now, right?

--- 

I am proposing here to remove `MIN_XCM_VERSION` from xcm module, and when needed for tests, we can do:
```
	let tested_versions = (XCM_VERSION-2)..=XCM_VERSION;
```

Or if we really need `MIN_XCM_VERSION`, I am proposing this:
```
	/// The minimal supported XCM version
	pub const MIN_XCM_VERSION: XcmVersion = latest::VERSION - 2;
```

Comment (bkontur) [reply polkadot/xcm/src/lib.rs:523]: Let's continue here: https://github.com/paritytech/polkadot-sdk/issues/7807

File: prdoc/pr_7438.prdoc [hunk 9]
```diff
@@ -0,0 +1,22 @@
...
+    description: |-
+      Fixes https://github.com/paritytech/polkadot-sdk/issues/7413
+
+      This PR updates the DryRunApi. The signature of the dry_run_call is changed, and the XCM version of the return values of dry_run_xcm now follows the version of the input XCM program.
+
+      It also fixes xcmp-queue's Router's `clear_messages`: the channel details `first_index` and `last_index` are reset when clearing.
+
+crates:
+- name: xcm-runtime-apis
+  bump: patch
```
Comment (seadanda) [inline prdoc/pr_7438.prdoc:14]: This should have been major - the signature of `dry_run_call` was changed by this PR
