### PR TITLE
cumulus/client: added external rpc connection retry logic

### LINKED ISSUE #4278: Do not crash collator when all  relay chain RPCs drop.
When starting a collator node with `--relay-chain-rpc-urls`, we expect that at least one of the specified nodes is available at all times. 

We could look into accepting occasional disconnects and continue running. This would probably lead to error prints on the parachain side, but that should be acceptable in this case.

### LINKED ISSUE #5514: Failure in relay chain rpc interface's connection attempt to external RPC servers
I am trying to start zombienet natively based on https://github.com/paritytech/polkadot-sdk/blob/master/cumulus/zombienet/tests/0006-rpc_collator_builds_blocks.toml. The collators always fail on my machine with the following error:
```
2024-08-22 18:51:42.758  INFO tokio-runtime-worker reconnecting-websocket-client: [Parachain] Trying to connect to next external relaychain node. index=0 url="ws://127.0.0.1:43283/"
2024-08-22 18:51:42.764  INFO tokio-runtime-worker reconnecting-websocket-client: [Parachain] Trying to connect to next external relaychain node. index=1 url="ws://127.0.0.1:37583/"
2024-08-22 18:51:42.776  INFO tokio-runtime-worker reconnecting-websocket-client: [Parachain] Trying to connect to next external relaychain node. index=2 url="ws://127.0.0.1:42159/"
2024-08-22 18:51:42.776 ERROR tokio-runtime-worker reconnecting-websocket-client: [Parachain] No valid RPC url found. Stopping RPC worker.
2024-08-22 18:51:42.777 ERROR tokio-runtime-worker sc_service::task_manager: [Parachain] Essential task `relay-chain-rpc-worker` failed. Shutting down service.    
thread 'main' panicked at cumulus/test/service/src/main.rs:144:18:
could not create Cumulus test service: Application(WorkerCommunicationError("RPC worker channel closed. This can hint and connectivity issues with the supplied RPC endpoints. Message: oneshot canceled"))
stack backtrace:
2024-08-22 18:51:42.774  INFO tokio-runtime-worker prometheus: [Relaychain] 〽️ Prometheus exporter started at 127.0.0.1:9616    
   0: rust_begin_unwind
             at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23/library/std/src/panicking.rs:652:5
   1: core::panicking::panic_fmt
             at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23/library/core/src/panicking.rs:72:14
   2: core::result::unwrap_failed
             at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23/library/core/src/result.rs:1679:5
   3: core::result::Result<T,E>::expect
             at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23/library/core/src/result.rs:1059:23
   4: test_parachain::main
             at ./polkadot-sdk/cumulus/test/service/src/main.rs:103:44
   5: core::ops::function::FnOnce::call_once
             at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23/library/core/src/ops/function.rs:250:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

There are ways to fix this in zombienet through a better coordination when starting the nodes, but I feel it can lead to overengineering e.g. it asks for implementation of starting nodes based on nodes dependencies, which is something other providers have support for it in various ways (k8s/podman),  but I personally still don't find it straightforward. 

The alternative is to add retry logic in cumulus/client/relay-chain-rpc-interface logic, that is sufficiently reliable for most cases, and if it becomes relevant for cases other than zombienet related testing, we could expose it in node configuration for users to set it as they need.

### PR DESCRIPTION
**Pull request by iulianbarbu**
# Description

Adds retry logic that makes the RPC relay chain interface more reliable for the cases of a collator connecting to external RPC servers.

Closes #5514 
Closes #4278

Final solution still debated on #5514 , what this PR addresses might change (e.g. #4278 might require a more advanced approach).

## Integration

Users that start collators should barely observe differences based on this logic, since the retry logic applies only in case the collators fail to connect to the RPC servers. In practice I assume the RPC servers are already live before starting collators, and the issue isn't visible.

## Review Notes

The added retry logic is for retrying the connection to the RPC servers (which can be multiple). It is at the level of the cumulus/client/relay-chain-rpc-interface module, but more specifically relevant to the RPC clients logic (`ClientManager`). The retry logic is not configurable, it tries to connect to the RPC client for 5 times, with an exponential backoff in between each iteration starting with 1 second wait time and ending with 16 seconds. The same logic is applied in case an existing connection to an RPC is dropped. There is a `ReconnectingWebsocketWorker` who ensures there is connectivity to at least on RPC node, and the retry logic makes this stronger by insisting on trying connections to the RPC servers list for 5 times.

## Testing

- This was tested manually by starting zombienet natively based on [006-rpc_collator_builds_blocks.toml](https://github.com/paritytech/polkadot-sdk/blob/master/cumulus/zombienet/tests/0006-rpc_collator_builds_blocks.toml) and observing collators don't fail anymore:

```bash
zombienet -l text --dir zbn-run -f --provider native spawn polkadot-sdk/cumulus/zombienet/tests/0006-rpc_collator_builds_blocks.toml
```

- Added a unit test that exercises the retry logic for a client connection to a server that comes online in 10 seconds. The retry logic can wait for as long as 30 seconds, but thought that it is too much for a unit test. Just being conscious of CI time if it runs this test, but I am happy to see suggestions around it too. I am not that sure either it runs in CI, haven't figured it out entirely yet. The test can be considered an integration test too, but it exercises crate internal implementation, not the public API. 

Collators example logs after the change:
```
2024-08-29 14:28:11.730  INFO tokio-runtime-worker reconnecting-websocket-client: [Parachain] Trying to connect to next external relaychain node. current_iteration=0 index=2 url="ws://127.0.0.1:37427/"
2024-08-29 14:28:12.737  INFO tokio-runtime-worker reconnecting-websocket-client: [Parachain] Trying to connect to next external relaychain node. current_iteration=1 index=0 url="ws://127.0.0.1:43617/"
2024-08-29 14:28:12.739  INFO tokio-runtime-worker reconnecting-websocket-client: [Parachain] Trying to connect to next external relaychain node. current_iteration=1 index=1 url="ws://127.0.0.1:37965/"
2024-08-29 14:28:12.755  INFO tokio-runtime-worker reconnecting-websocket-client: [Parachain] Trying to connect to next external relaychain node. current_iteration=1 index=2 url="ws://127.0.0.1:37427/"
2024-08-29 14:28:14.758  INFO tokio-runtime-worker reconnecting-websocket-client: [Parachain] Trying to connect to next external relaychain node. current_iteration=2 index=0 url="ws://127.0.0.1:43617/"
2024-08-29 14:28:14.759  INFO tokio-runtime-worker reconnecting-websocket-client: [Parachain] Trying to connect to next external relaychain node. current_iteration=2 index=1 url="ws://127.0.0.1:37965/"
2024-08-29 14:28:14.760  INFO tokio-runtime-worker reconnecting-websocket-client: [Parachain] Trying to connect to next external relaychain node. current_iteration=2 index=2 url="ws://127.0.0.1:37427/"
2024-08-29 14:28:18.766  INFO tokio-runtime-worker reconnecting-websocket-client: [Parachain] Trying to connect to next external relaychain node. current_iteration=3 index=0 url="ws://127.0.0.1:43617/"
2024-08-29 14:28:18.768  INFO tokio-runtime-worker reconnecting-websocket-client: [Parachain] Trying to connect to next external relaychain node. current_iteration=3 index=1 url="ws://127.0.0.1:37965/"
2024-08-29 14:28:18.768  INFO tokio-runtime-worker reconnecting-websocket-client: [Parachain] Trying to connect to next external relaychain node. current_iteration=3 index=2 url="ws://127.0.0.1:37427/"
2024-08-29 14:28:26.770  INFO tokio-runtime-worker reconnecting-websocket-client: [Parachain] Trying to connect to next external relaychain node. current_iteration=4 index=0 url="ws://127.0.0.1:43617/"
```

### CODE REVIEW

File: cumulus/client/relay-chain-rpc-interface/src/reconnecting_ws_client.rs [hunk 1]
```diff
@@ -93,16 +96,45 @@ struct RelayChainSubscriptions {
...
+		.iter()
+		.cycle()
+		.skip(starting_position)
+		.take(urls.len() * DEFAULT_EXTERNAL_RPC_CONN_RETRIES)
+		.enumerate()
+	{
+		// If we reached the end of the urls list, backoff before retrying
+		// connections to the entire list once more.
+		let Ok(current_iteration) = (counter / urls.len()).try_into() else {
+			tracing::error!(target: LOG_TARGET, "Too many connection attempts to the RPC servers, aborting...");
```
Comment (michalkucharczyk) [inline cumulus/client/relay-chain-rpc-interface/src/reconnecting_ws_client.rs:121]:
```suggestion
			tracing::error!(target: LOG_TARGET, "Too many connection failed attempts to the RPC servers, aborting...");
```

File: cumulus/client/relay-chain-rpc-interface/src/reconnecting_ws_client.rs [hunk 2]
```diff
@@ -460,4 +496,48 @@ mod test {
...
+		});
+
+		// By this time the client can not make a connection because the server is not up.
+		assert!(conn_res.await.unwrap().is_err());
+
+		// Trying to connect again to the RPC with a client that stays around for sufficient
+		// time to catche the RPC server online and connect to it.
+		let conn_res = tokio::spawn(async move {
+			tokio::time::timeout(
+				Duration::from_secs(8),
```
Comment (michalkucharczyk) [inline cumulus/client/relay-chain-rpc-interface/src/reconnecting_ws_client.rs:532]: CI tests are run on quit overloaded machines. 1s margin may not be enough, but let's see how it goes.

File: cumulus/client/relay-chain-rpc-interface/src/reconnecting_ws_client.rs (hunk 1 above)
Comment (michalkucharczyk) [reply cumulus/client/relay-chain-rpc-interface/src/reconnecting_ws_client.rs:121]: hm, will this error be ever printed?

**Review by michalkucharczyk — APPROVED** [review]

File: cumulus/client/relay-chain-rpc-interface/src/reconnecting_ws_client.rs (hunk 1 above)
Comment (michalkucharczyk) [reply cumulus/client/relay-chain-rpc-interface/src/reconnecting_ws_client.rs:121]: I think we need extra check to print the error if loop concluded w/o actual connection.

File: cumulus/client/relay-chain-rpc-interface/src/reconnecting_ws_client.rs [hunk 3]
```diff
@@ -460,4 +496,48 @@ mod test {
...
+		let server = tokio::spawn(async {
+			tokio::time::sleep(Duration::from_secs(10)).await;
+			server.start(Methods::default())
+		});
+
+		// By this time the client can not make a connection because the server is not up.
+		assert!(conn_res.await.unwrap().is_err());
+
+		// Trying to connect again to the RPC with a client that stays around for sufficient
+		// time to catche the RPC server online and connect to it.
```
Comment (sandreim) [inline cumulus/client/relay-chain-rpc-interface/src/reconnecting_ws_client.rs:530]:
```suggestion
		// time for the RPC server to become online and connect to it.
```

File: cumulus/client/relay-chain-rpc-interface/src/reconnecting_ws_client.rs (hunk 1 above)
Comment (iulianbarbu) [reply cumulus/client/relay-chain-rpc-interface/src/reconnecting_ws_client.rs:121]: > hm, will this error be ever printed?

In practice it shouldn't be printed ever, but if we'll ever see the log then something's weird (either we're iterating for too many times for the retry logic or memory gets corrupted at runtime).

> I think we need extra check to print the error if loop concluded w/o actual connection.

You mean outside of the loop if not concluding with a connection? I added a log here: https://github.com/paritytech/polkadot-sdk/pull/5515/commits/d47a96553e2206d2ff51170fb09920df90c004b4. Let me know if that's what you mean.

File: cumulus/client/relay-chain-rpc-interface/src/reconnecting_ws_client.rs [hunk 4]
```diff
@@ -460,4 +497,48 @@ mod test {
...
+		let port = portpicker::pick_unused_port().unwrap();
+		let server = jsonrpsee::server::Server::builder()
+			.build(format!("0.0.0.0:{}", port))
+			.await
+			.unwrap();
+
+		// Wait three seconds while attempting connection.
+		let conn_res = tokio::spawn(async move {
+			tokio::time::timeout(
+				Duration::from_secs(3),
```
Comment (sandreim) [inline cumulus/client/relay-chain-rpc-interface/src/reconnecting_ws_client.rs:514]: Using sleep in tests has high potential to make it flaky. I don't understand why we wait here 3 seconds, only to expect the obvious, there is no server up to connect to. What can happen is that the server might actually start if CI is overloaded and this will fail.

For testing the logic here I think there are other ways to do it. I mean you just want to see it trying multiple servers in the list and increasing the back off. This stuff is not actually tested here at all.

Comment (iulianbarbu) [reply cumulus/client/relay-chain-rpc-interface/src/reconnecting_ws_client.rs:519]: Haven't seen this. It came a bit earlier than this: https://github.com/paritytech/polkadot-sdk/pull/5515/commits/71e44b47cc4514f659a3650b8125ebc7143f58c8. I agree with your points.

> I don't understand why we wait here 3 seconds, only to expect the obvious, there is no server up to connect to.

The idea of the wait is that the `ClientManager::new` call doesn't exit immediately as it should've (because of the connection refused error), but it exercises the retry logic hoping the server would be up. The error we're asserting against is the `Elapsed` error which is triggered because the `ClientManager::new` call timed out - which means retry logic worked behind the scenes.

I think though we can simplify the test by starting the server in a tokio task with a 10 second delay (10 because it is not too big/small for our usecase), and then create a client on the "main" task which exercises the retry logic until the server gets up and returns with an `Ok` result.

> I mean you just want to see it trying multiple servers in the list and increasing the back off. This stuff is not actually tested here at all.

I think testing the backoff involves some other timers with timeouts given the logic doesn't produce testable side effects, which can add more sources of flakyness. I am open to suggestions if you see it differently. As a matter of fact I wasn't interested in testing the backoff, but the fact that the collators' relay chain interface tries a few more times to connect to the external RPCs at collator startup. I heard there weren't complaints about this in practice meaning the collators usually find available RPC nodes to connect to. This is more relevant to local testing on slow/overloaded machines, so testing anything other than a slight reliability improvement brings diminishing returns.

Comment (iulianbarbu) [reply cumulus/client/relay-chain-rpc-interface/src/reconnecting_ws_client.rs]: Pushed a simpler version of the test here: [ee68d04](https://github.com/paritytech/polkadot-sdk/pull/5515/commits/ee68d040653b801897af8e646c19508a8015511d). Let me know if this changes anything!

File: cumulus/client/relay-chain-rpc-interface/src/reconnecting_ws_client.rs (hunk 3 above)
Comment (iulianbarbu) [reply cumulus/client/relay-chain-rpc-interface/src/reconnecting_ws_client.rs]: Not relevant anymore.

File: cumulus/client/relay-chain-rpc-interface/src/reconnecting_ws_client.rs (hunk 2 above)
Comment (iulianbarbu) [reply cumulus/client/relay-chain-rpc-interface/src/reconnecting_ws_client.rs]: Pushed a simpler version of the test here: [ee68d04](https://github.com/paritytech/polkadot-sdk/pull/5515/commits/ee68d040653b801897af8e646c19508a8015511d).

File: cumulus/client/relay-chain-rpc-interface/src/reconnecting_ws_client.rs [hunk 5]
```diff
@@ -112,6 +144,8 @@ async fn connect_next_available_rpc_server(
 			Err(err) => tracing::debug!(target: LOG_TARGET, url, ?err, "Unable to connect."),
 		};
 	}
+
+	tracing::error!(target: LOG_TARGET, "Retrying to connect to any external relaychain node failed.");
```
[the remark this answers is not in the document]
Comment (iulianbarbu) [reply cumulus/client/relay-chain-rpc-interface/src/reconnecting_ws_client.rs:148]: That's individually displayed with each iteration for each url. I think we should be fine.

[the remark this answers is not in the document]
Comment (michalkucharczyk) [reply cumulus/client/relay-chain-rpc-interface/src/reconnecting_ws_client.rs:148]: Assuming `info` level is enabled which may not be a case for defaults. Anyway it is minor.

File: cumulus/client/relay-chain-rpc-interface/src/reconnecting_ws_client.rs [hunk 6]
```diff
@@ -93,16 +96,45 @@ struct RelayChainSubscriptions {
...
+					DEFAULT_SLEEP_EXP_BACKOFF_BETWEEN_RETRIES.pow(prev_iteration) as u64,
+			))
+			.await;
+			prev_iteration = current_iteration;
+		}
+
 		let index = (starting_position + counter) % urls.len();
 		tracing::info!(
 			target: LOG_TARGET,
+			current_iteration,
```
Comment (skunert) [inline cumulus/client/relay-chain-rpc-interface/src/reconnecting_ws_client.rs:137]: Nit: From users perspective we should probably just print `attempt` here and summarize index and iteration.

**Review by skunert — APPROVED** [review]
Nice Job! 
I think this is really nice to have. We can run into the situation where some subsystems try to make calls and waits for a longer time due to retries. I am not sure all places handle that super graceful, but it still sounds a lot better than crashing.

**Review by lexnv — APPROVED** [review]
LGTM! Nice job here! This should make things better 👍

**Review by skunert — APPROVED** [review]

**Review by sandreim — APPROVED** [review]

**Review by skunert — APPROVED** [review]
Once we have two reviews we need to merge fast, every time you merge master it re-requests our review.

**Comment by iulianbarbu** [comment]
> Once we have two reviews we need to merge fast, every time you merge master it re-requests our review.

Yes, sorry about that. Trying to figure out how to fix it. I requested to join a few GH teams, hopefully after that's done next PRs will not have this issue.

**Review by lexnv — APPROVED** [review]

**Review by dmitry-markin — APPROVED** [review]

File: cumulus/client/relay-chain-rpc-interface/src/reconnecting_ws_client.rs (hunk 1 above)
Comment (skunert) [reply cumulus/client/relay-chain-rpc-interface/src/reconnecting_ws_client.rs:121]: We should never hit this branch since this will loop for a maximum `urls.len() * DEFAULT_EXTERNAL_RPC_CONN_RETRIES` times.

**Review by michalkucharczyk — APPROVED** [review]
