### PR TITLE
staking-async: add missing new_session_genesis

### LINKED ISSUE #8302: Polkadot node stuck in `Emergency` phase
### Is there an existing issue?

- [x] I have searched the existing issues

### Experiencing problems? Have you tried our Stack Exchange first?

- [x] This is not a support question.

### Description of bug

After https://github.com/paritytech/polkadot-sdk/pull/8127 got merged, we noticed that when  running `polkadot` binary like below:

```bash
./target/release/polkadot --chain westend-dev --tmp --alice --unsafe-force-node-key-generation --execution Native --offchain-worker=Always --rpc-cors=all
```

Logs from the polkadot node:

```bash
➜ polkadot-sdk (79b28b3185d0) ✗ ./target/release/polkadot --chain westend-dev --tmp --alice --unsafe-force-node-key-generation --execution Native --offchain-worker=Always --rpc-cors=all
CLI parameter `--execution` has no effect anymore and will be removed in the future!
2025-04-23 10:18:52.457  INFO main sc_cli::runner: Parity Polkadot
2025-04-23 10:18:52.457  INFO main sc_cli::runner: ✌️  version 1.18.0-79b28b3185d
2025-04-23 10:18:52.457  INFO main sc_cli::runner: ❤️   by Parity Technologies <admin@parity.io>, 2017-2025
2025-04-23 10:18:52.457  INFO main sc_cli::runner: 📋 Chain specification: Development
2025-04-23 10:18:52.457  INFO main sc_cli::runner: 🏷  Node name: Alice
2025-04-23 10:18:52.457  INFO main sc_cli::runner: 👤 Role: AUTHORITY
2025-04-23 10:18:52.457  INFO main sc_cli::runner: 💾 Database: RocksDb at /tmp/substrateZKIjnf/chains/westend_dev/db/full
2025-04-23 10:19:13.668 DEBUG main runtime::staking: [0] 💸 Starting the first era.
2025-04-23 10:19:13.668 DEBUG main runtime::election-provider: [#0] 🗳  closed signed phase, found solution? false, discarded 0
2025-04-23 10:19:13.668  WARN main runtime::election-provider: [#0] 🗳  No solution queued, falling back to instant fallback.
2025-04-23 10:19:13.668  WARN main runtime::election-provider: [#0] 🗳  Failed to finalize election round. reason ElectionError::Feasibility(SnapshotUnavailable)
2025-04-23 10:19:13.668 ERROR main runtime::election-provider: [#0] 🗳  Entering emergency mode: ElectionError::Feasibility(SnapshotUnavailable)
2025-04-23 10:19:13.668  INFO main runtime::election-provider: [#0] 🗳  Starting phase Emergency, round 1.
2025-04-23 10:19:13.668  INFO main runtime::election-provider: [#0] 🗳  ElectionProvider::elect(0) => Err(ElectionError::Feasibility(SnapshotUnavailable))
2025-04-23 10:19:13.668  WARN main runtime::staking: [0] 💸 election provider failed due to ElectionError::Feasibility(SnapshotUnavailable)
2025-04-23 10:19:13.668 DEBUG main runtime: No initial validator provided by `SessionManager`, use session config keys to generate initial validator set.
2025-04-23 10:19:13.668 DEBUG main runtime::staking: [0] 💸 Starting the first era.
2025-04-23 10:19:13.668 DEBUG main runtime::election-provider: [#0] 🗳  closed signed phase, found solution? false, discarded 0
2025-04-23 10:19:13.668  WARN main runtime::election-provider: [#0] 🗳  No solution queued, falling back to instant fallback.
2025-04-23 10:19:13.668  WARN main runtime::election-provider: [#0] 🗳  Failed to finalize election round. reason ElectionError::Feasibility(SnapshotUnavailable)
2025-04-23 10:19:13.668 ERROR main runtime::election-provider: [#0] 🗳  Entering emergency mode: ElectionError::Feasibility(SnapshotUnavailable)
2025-04-23 10:19:13.668  INFO main runtime::election-provider: [#0] 🗳  Starting phase Emergency, round 1.
2025-04-23 10:19:13.668  INFO main runtime::election-provider: [#0] 🗳  ElectionProvider::elect(0) => Err(ElectionError::Feasibility(SnapshotUnavailable))
2025-04-23 10:19:13.668  WARN main runtime::staking: [0] 💸 election provider failed due to ElectionError::Feasibility(SnapshotUnavailable)
```

the Phase shows up as `Emergency` and never gets into the `Signed` phase.

This cause the polkadot-staking-miner CI tests to systematically fail, see the issue [here](https://github.com/paritytech/polkadot-staking-miner/issues/1031).

Image

### Steps to reproduce

1. build `polkadot` binary vs latest and greatest SDK master
2. run `./target/release/polkadot --chain westend-dev --tmp --alice --unsafe-force-node-key-generation --execution Native --offchain-worker=Always --rpc-cors=all`

Expected:
- Phase should transition to `Signed`, `Unsigned` etc

Actual:
- Phase stuck in `Emergency`

### PR DESCRIPTION
**Pull request by sigurpol**
Fix issue #8302  (introduced by #8127), where the staking-async module could fail during genesis.

The issue was related to the staking-async module in the Polkadot SDK, specifically with the implementation of the `historical::SessionManager` trait in the `ah-client` pallet with missing implementations of the new_session_genesis method in two different places:
- In the pallet_session::SessionManager<T::AccountId> implementation
- In the historical::SessionManager<T::AccountId, sp_staking::Exposure<T::AccountId, BalanceOf<T>>> implementation

Note: the SessionManager trait requires the implementation of new_session_genesis for proper functioning, especially during chain initialization.

The pallet-staking-async/ah-client has different operating modes:
- Passive: Delegates operations to a fallback implementation
- Buffered: Buffers operations for later processing
- Active: Performs operations directly

The fix ensures that in Passive mode, the new_session_genesis method correctly delegates to the fallback implementation, while in other modes it returns None.

### CODE REVIEW

**Comment by sigurpol** [comment]
@kianenigma , @Ank4n , @niklasad1  PTAL 🙏 
And also please check that labels and prdoc make sense since I am new to this whole process 🙇

**Review by niklasad1 — APPROVED** [review]

File: substrate/frame/election-provider-multi-phase/src/lib.rs [hunk 1]
```diff
@@ -1847,18 +1870,6 @@ impl<T: Config> ElectionProvider for Pallet<T> {
 			_ => Ok(false),
 		}
 	}
-
-	#[cfg(feature = "runtime-benchmarks")]
-	fn asap() {
-		// prepare our snapshot so we can "hopefully" run a fallback.
```
Comment (kianenigma) [inline substrate/frame/election-provider-multi-phase/src/lib.rs:1853]: I think you should keep this, right? or else `<Pallet as ElectionProvider>::asap()` will be the default impl now.

You should create `fn do_asap()`, and use it here, and also call `do_asap` in the code where it is needed outside of the `#[cfg(feature = "runtime-benchmarks")]` scope.

**Comment by kianenigma** [comment]
Did you figure out why `is_genesis` is not set, while it should? This is more of a "root cause" rather than "fix symptoms" :))

**Comment by sigurpol** [comment]
> Did you figure out why `is_genesis` is not set, while it should? This is more of a "root cause" rather than "fix symptoms" :))

I know and agree, best I have found is [here](https://github.com/paritytech/polkadot-sdk/issues/8302#issuecomment-2824005376) and I haven't investigated further.  This is why I put this part in the commit message 

```
While the solution has the benefit to be limited in scope and not invasive, a better fix would be probably not to rely on the asap() method at all for genesis block but ensure that the session manager correctly calls new_session() or new_session_genesis() respectively.
```

File: substrate/frame/election-provider-multi-phase/src/lib.rs (hunk 1 above)
Comment (sigurpol) [reply substrate/frame/election-provider-multi-phase/src/lib.rs:1853]: good point! Fixed (hopefully) [here](https://github.com/paritytech/polkadot-sdk/pull/8310/commits/0d6e25415ba7836005cde6095f2c50340375ee03)

**Comment by kianenigma** [comment]
Sorry I took the liberty to investigate and push in https://github.com/paritytech/polkadot-sdk/pull/8310/commits/3525e4fc0be4bb02f580f263076dea23f30aa45f

So the root cause is this. Note that in Westend runtime, `type SessionManager = SomeUnrelatedWrapper<AhStakingClient>`, which basically means `ah-client` is the manager, and since it is in `OperatingMode::Passive` by default, it will pass everything to its `type Fallback`, which is our good 'ol `pallet-staking`. Yet, you see the danger of trait auto implementations here: `trait SessionManager` has an auto-impl for the genesis one, and we forgot about it (cc @Ank4n to also review this).

I am okay with the rest of the changes, but i am sure westend will work fine without them, if you just keep the last commit.

File: substrate/frame/staking-async/ah-client/src/lib.rs [hunk 2]
```diff
@@ -534,6 +534,16 @@ pub mod pallet {
 			<Self as pallet_session::SessionManager<_>>::start_session(start_index)
 		}
 
+		fn new_session_genesis(
```
Comment (sigurpol) [inline substrate/frame/staking-async/ah-client/src/lib.rs:537]: [nitpick] we also need to cleanup comment at line 530 since we now implement new_session_genesis :)

**Comment by sigurpol** [comment]
@kianenigma , I've reverted the rest of the changes (tested against the usual miner CI's test -> it works fine w/o).
I've also made a small change at your change since it was not compiling.

**Review by kianenigma — APPROVED** [review]
