### PR TITLE
Fix `feeless_if` in pallet section

### LINKED ISSUE #5981: `#[feeless_if(..)]` breaks when used in a `#[pallet_section]`
### Is there an existing issue?

- [X] I have searched the existing issues

### Experiencing problems? Have you tried our Stack Exchange first?

- [X] This is not a support question.

### Description of bug

Right now one of the bugs with `#[pallet_section]` is if the external pallet section has a `#[feeless_if(..)]` anywhere in it, for some reason this causes a string of compile errors. A recent example is here but it is quite easy to reproduce: https://github.com/opentensor/subtensor/actions/runs/11215301673/job/31172208884#step:6:1609

I imagine this has something to do with how `feeless_if` is implemented interfering in some way with the `macro_magic` `import_tokens_attr` call. In theory this sort of thing should never happen so my guess is there is something weird going on in the parsing/expansion code for `feeless_if`, but I have not had a chance to look at it in depth.

debugging steps I would take would be:
* check out the parsing/expansion code for `#[feeless_if(..)]`, see if you can print something to the terminal from there and use bisection to figure out where the compile error is originating from

### Steps to reproduce

* make a new pallet, dev mode is fine
* define an external `#[pallet_section]`
* import that section using `#[import_section]`
* in this pallet section, use `#[feeless_if(..)]`
* you will get a compile error saying "expected a value" with a span pointing to the `#[pallet::pallet]` macro invocation site.

### PR DESCRIPTION
**Pull request by eagr**
fixes #5981 

Could confirm the issue with the added tests:

```
test tests/split_ui/pass/split_call.rs [should pass] ... error
┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈
error[E0423]: expected value, found attribute macro `origin`
  --> tests/split_ui/pass/split_call.rs:23:1
   |
23 | #[frame_support::pallet(dev_mode)]
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ not a value
   |
   = note: this error originates in the attribute macro `frame_support::pallet` (in Nightly builds, run with -Z macro-backtrace for more info)
```

# Description

`origin` unexpectedly resolved to a macro, which is available at the span of invocation. The solution here is to use the expansion as a function instead of a call and pass in the desired values to avoid ambiguities.

### CODE REVIEW

File: substrate/frame/support/procedural/src/pallet/expand/call.rs [hunk 1]
```diff
@@ -393,7 +393,7 @@ pub fn expand_call(def: &mut Def) -> proc_macro2::TokenStream {
 					#(
 						#cfg_attrs
 						Self::#fn_name { #( #args_name_pattern_ref, )* } => {
-							#feeless_check_result
+							#feeless_check(origin, #( #args_name, )*)
```
Comment (gui1117) [inline substrate/frame/support/procedural/src/pallet/expand/call.rs:396]: There is a clippy warning:
```
Run forklift cargo clippy --all-targets --locked --workspace --quiet
   Using forklift, storage: gcs, compressor: zstd-3, uploader threads: 6
error: try not to call a closure in the expression where it is declared
   --> substrate/frame/system/src/lib.rs:649:12
    |
649 |     #[pallet::call]
    |               ^^^^
    |
    = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#redundant_closure_call
    = note: `-D clippy::redundant-closure-call` implied by `-D warnings`
    = help: to override `-D warnings` add `#[allow(clippy::redundant_closure_call)]`
```

maybe add `#[allow(clippy::redundant_closure_call)]` or use a variable for the closure: `let c = #feeless_check; c(origin, ...);`

**Review by gui1117 — APPROVED** [review]
Looks good to me, but needs to fix clippy warning (so user using clippy are not bothered).

**Review by bkchr — APPROVED** [review]

**Review by bkchr — APPROVED** [review]
