### PR TITLE
parachain-consensus: Do not pin blocks on the relay chain during syncing

### LINKED ISSUE #1662: statemine archive node need large amount of memory during startup and the synchronization speed is too slow.
### Is there an existing issue?

- [X] I have searched the existing issues

### Experiencing problems? Have you tried our Stack Exchange first?

- [X] This is not a support question.

### Description of bug

I tried running a statemine archive node using the `parity/polkadot-parachain:1.1.0` Docker image. However, I noticed that when the node synchronizes to a certain number of blocks, the memory usage increases dramatically until it is forcefully terminated. Even after restarting, the node gets terminated due to high memory usage. Below is the command I used to run the node:
```
docker run -d parity/polkadot-parachain:1.1.0 --base-path=/substrate-base --name="test" --rpc-external --rpc-cors=all --prometheus-external --chain=statemine --rpc-methods=Unsafe --rpc-max-connections=1000 --pruning=archive --execution=wasm
```
This is the log of the node container getting stuck and being killed after restart:
```
CLI parameter `--execution` has no effect anymore and will be removed in the future!
2023-09-21 11:11:28 Polkadot parachain    
2023-09-21 11:11:28 ✌️  version 1.1.0-783579b4a49    
2023-09-21 11:11:28 ❤️  by Parity Technologies <admin@parity.io>, 2017-2023    
2023-09-21 11:11:28 📋 Chain specification: Kusama Asset Hub    
2023-09-21 11:11:28 🏷  Node name: "Subscan Explorer Hosted"    
2023-09-21 11:11:28 👤 Role: FULL    
2023-09-21 11:11:28 💾 Database: RocksDb at /substrate-base/chains/asset-hub-kusama/db/full    
2023-09-21 11:11:30 Parachain id: Id(1000)    
2023-09-21 11:11:30 Parachain Account: 5Ec4AhPZk8STuex8Wsi9TwDtJQxKqzPJRCH7348Xtcs9vZLJ    
2023-09-21 11:11:30 Is collating: no
```
This is the resource information occupied by the node at runtime:
image

### Steps to reproduce

1. Run Node
```yaml
docker run -d parity/polkadot-parachain:1.1.0 --base-path=/substrate-base --name="test" --rpc-external --rpc-cors=all --prometheus-external --chain=statemine --rpc-methods=Unsafe --rpc-max-connections=1000 --pruning=archive --execution=wasm
```
Wait for a significant increase in memory usage. Currently, the exact time point when memory usage will increase rapidly cannot be predicted.

### PR DESCRIPTION
**Pull request by skunert**
We had reports in the past about `polkadot-parachain` consuming a lot of memory during syncing. I spend some time investigating this again. 

This graph shows memory consumption during sync process:
image

 We see a rise up to 50gb and then release of a lot of memory and node stabilizes at around 20gb. While I still find that relatively high, I found that the large reduction in memory towards the end was caused by finality notifications. I tracked down the culprit to be `parachain-consensus`. It is doing long-blocking finalization operations and keeps finality notifications around while doing so. 

In this PR I introduce a new task that fetches the included block and then immediately releases the finality notifications of the relay chain.

Memory is now more bounded at around ~12gb:
image

closes #1662

### CODE REVIEW

File: cumulus/client/consensus/common/src/lib.rs [hunk 1]
```diff
@@ -39,7 +39,9 @@ mod tests;
 pub use parent_search::*;
 
 pub use cumulus_relay_chain_streams::finalized_heads;
-pub use parachain_consensus::run_parachain_consensus;
+pub use parachain_consensus::{
+	finalized_head_stream_worker, run_parachain_consensus, spawn_parachain_consensus_tasks,
```
Comment (bkchr) [inline cumulus/client/consensus/common/src/lib.rs]: Why do we need to expose all these functions?
