### PR TITLE
[pallet-broker] Fix auto renew benchmarks

### LINKED ISSUE #6474: pallet broker: some benchmarks are weightless for kitchensink runtime. Resulting in substrate weight being 0
`enable_auto_renew` and `disable_auto_renew` benchmarks result in `Weightless` when run against the kitchensink runtime. And also when run against the mock runtime.

It is not very ideal as we use kitchen sink to get some default weight and some general idea of the cost of the pallet calls.

You can see the weight info resulting from CI here: https://github.com/paritytech/polkadot-sdk/pull/6418/commits/4dfe581539971010fb462ae1987cdb0a2a2ff734#diff-394c3120033a81905e5460398ad0d7245d7143d21069aeffb3cdf07b41eccc18

I believe it is weightless since: https://github.com/paritytech/polkadot-sdk/pull/4424

@Szegoo 
@seadanda

### PR DESCRIPTION
**Pull request by seadanda**
Fix the broker pallet auto-renew benchmarks which have been broken since #4424, yielding `Weightless` due to some prices being set too low, as reported in #6474.

Upon further investigation it turned out that the auto-renew contribution to `rotate_sale` was always failing but the error was mapped. This is also fixed at the cost of a bit of setup overhead.

Fixes #6474

TODO:
- [x] Re-run weights

### CODE REVIEW

File: substrate/frame/broker/src/benchmarking.rs [hunk 1]
```diff
@@ -1045,14 +1062,15 @@ mod benches {
...
 			&caller.clone(),
-			T::Currency::minimum_balance().saturating_add(100u32.into()),
+			T::Currency::minimum_balance().saturating_add(100_000_000u32.into()),
 		);
 
 		// The region for which we benchmark enable auto renew.
-		let region = Broker::<T>::do_purchase(caller.clone(), 10u32.into())
-			.map_err(|_| BenchmarkError::Weightless)?;
+		let region = Broker::<T>::do_purchase(caller.clone(), 10_000_000u32.into())
+			.expect("Offer not high enough for configuration.");
```
Comment (seadanda) [inline substrate/frame/broker/src/benchmarking.rs:1073]: Since we advance to the fixed price phase, this is independent of the price adapter implementation and depends only on the config value set earlier in this file. Therefore it's better to unwrap here so the test fails, rather than always being mapped to Weightless.

**Comment by seadanda** [comment]
bot bench cumulus-coretime --runtime=coretime-westend --pallet=pallet_broker
bot bench cumulus-coretime --runtime=coretime-rococo --pallet=pallet_broker

**Comment by seadanda** [comment]
bot bench substrate-pallet --features=runtime-benchmarks --pallet=pallet_broker

**Comment by seadanda** [comment]
bot bench cumulus-coretime --features=runtime-benchmarks --runtime=coretime-westend --pallet=pallet_broker
bot bench cumulus-coretime --features=runtime-benchmarks --runtime=coretime-rococo --pallet=pallet_broker

**Comment by seadanda** [comment]
This will affect https://github.com/polkadot-fellows/runtimes/pull/490

Until this PR is merged and backported we should filter these calls and set MaxAutoRenewals to 0

**Review by gui1117 — APPROVED** [review]

**Comment by seadanda** [comment]
bot bench cumulus-coretime --features=runtime-benchmarks --runtime=coretime-westend --pallet=pallet_broker
bot bench cumulus-coretime --features=runtime-benchmarks --runtime=coretime-rococo --pallet=pallet_broker

File: substrate/frame/broker/src/benchmarking.rs [hunk 2]
```diff
@@ -786,99 +786,115 @@ mod benches {
...
+
+		// Start sales so we can test the auto-renewals.
+		Broker::<T>::do_start_sales(
+			10_000_000u32.into(),
+			n.saturating_sub(n_reservations)
+				.saturating_sub(n_leases)
+				.try_into()
+				.expect("Upper limit of n is a u16."),
+		)
+		.map_err(|_| BenchmarkError::Weightless)?;
```
Comment (bkchr) [inline substrate/frame/broker/src/benchmarking.rs:811]:
```suggestion
		.expect("Configuration was initialized before; qed");
```

**Comment by seadanda** [comment]
bot clean

**Comment by seadanda** [comment]
bot bench substrate-pallet --features=runtime-benchmarks --pallet=pallet_broker
bot bench cumulus-coretime --features=runtime-benchmarks --runtime=coretime-westend --pallet=pallet_broker
bot bench cumulus-coretime --features=runtime-benchmarks --runtime=coretime-rococo --pallet=pallet_broker

**Review by bkchr — COMMENTED** [review]
Gnerally having all these `price_limits` hard coded is not such a great idea, but yeah it was not done differently before.

**Review by bkchr — APPROVED** [review]
