### PR TITLE
Fix: AssetTrapped event with Fungible(0) due to `SwapFirstAssetTrader::buy_weight` for exact trades

### LINKED ISSUE #11388: `SwapFirstAssetTrader::buy_weight` creates 0-amount AssetsInHolding entry, causing Fungible(0) decode failure in AssetsTrapped event
When PayFees instruction contains the exact fee amount quoted by query_weight_to_asset_fee, the swap in SwapFirstAssetTrader::buy_weight produces zero change. This zero-amount credit is unconditionally wrapped into an AssetsInHolding entry:

```rust
 let unspent = AssetsInHolding::new_from_fungible_credit(id, Box::new(credit_change));
 payment.subsume_assets(unspent);
```
 This 0-amount entry propagates:
 1. buy_weight returns it as unspent → PayFees handler puts it in self.fees
 2. refund_surplus() moves leftover fees into self.holding
 3. post_process() calls drop_assets() because holding appears non-empty
 4. drop_assets() emits AssetsTrapped event containing Fungible(0)
 5. Fungibility::decode() rejects Fungible(0): "Fungible asset of zero amount is not allowed"

Fix: Guard buy_weight against 0-amount change, matching the existing pattern in refund_weight:

```rust
 if credit_change.peek() > 0 {
     let unspent = AssetsInHolding::new_from_fungible_credit(id, Box::new(credit_change));
     payment.subsume_assets(unspent);
 }
```

 Discovered in: PR #10726, commit a2740c69f5b

### PR DESCRIPTION
**Pull request by clangenb**
When `PayFees` contained the exact quoted fee, `SwapFirstAssetTrader::buy_weight` produces zero swap change. This 0-amount credit was unconditionally wrapped into an `AssetsInHolding` entry, which propagated through `fees` → `refund_surplus` → `holding` → `drop_assets`, emitting an `AssetsTrapped` event with `Fungible(0)` that fails to decode.

This PR simply guards that by checking if value is 0 before putting it into the holding, and omitting the step if the value is 0.

Closes #11388

### CODE REVIEW

**Comment by clangenb** [comment]
/cmd prdoc --audience runtime_dev --bump patch --crate cumulus-primitives-utility

**Comment by clangenb** [comment]
@franciscoaguirre I took the liberty to tag you, as I think this falls into your domain. :)

**Comment by clangenb** [comment]
Thanks a lot for the quick reviews! I guess it can be added to the merge queue. I have no rights to do this, correct?

File: cumulus/primitives/utility/src/lib.rs [hunk 1]
```diff
@@ -501,8 +501,10 @@ where
 		};
 		self.last_fee_asset = Some(id.clone());
 
-		let unspent = AssetsInHolding::new_from_fungible_credit(id, Box::new(credit_change));
-		payment.subsume_assets(unspent);
+		if credit_change.peek() != Zero::zero() {
+			let unspent = AssetsInHolding::new_from_fungible_credit(id, Box::new(credit_change));
+			payment.subsume_assets(unspent);
```
Comment (bkontur) [inline cumulus/primitives/utility/src/lib.rs:506]: I was just thinking that this zero check could be possibly be done inside `subsume_assets` - but cannot think of consequences or expectations now, need more thinking, also maybe not a good thing :)

But here the `unspent` holds just one credit_change

**Comment by bkontur** [comment]
> @franciscoaguirre I took the liberty to tag you, as I think this falls into your domain. :)

@franciscoaguirre Could you please amen this?

File: cumulus/primitives/utility/src/lib.rs (hunk 1 above)
Comment (clangenb) [reply cumulus/primitives/utility/src/lib.rs:506]: We could look into this, but this is the pattern that is already used elsewhere, so if we change the `subsume_assets` we could/should update this throughout the codebase (I don't know yet if this is much - I only know of one other case so far).

Comment (bkontur) [reply cumulus/primitives/utility/src/lib.rs:506]: I remember some "zero checks for assets", maybe these: https://github.com/paritytech/polkadot-sdk/blob/20311a9465b9ea0e28edd480cbfce8c3daa6b903/polkadot/xcm/src/v5/asset.rs#L281-L285 
but here we are talking about xcm-executor's AssetsInHolding, maybe very very low prio to continue investigations
